import LeanLCAExactChallenge.LCA.StrictExact
import LeanLCAExactChallenge.LCA.Quotient
import Mathlib.CategoryTheory.Limits.Shapes.Pullback.PullbackCone

/-!
Explicit algebraic pushouts in the local `MetrizableLCA` category.

For a span `X₁ ⟶ X₂` and `X₁ ⟶ Y`, the algebraic pushout is modelled as
`(X₂ × Y) / range (x ↦ (f x, -a x))`.  This file builds the quotient object and
its universal property assuming the relation subgroup is closed.  Proving that
closedness from strictness of `f` is the remaining topological input for the
pushout half of the exact-category condition.
-/

set_option autoImplicit false

universe u

namespace LeanLCAExactChallenge

open CategoryTheory
open CategoryTheory.Limits
open Topology

namespace MetrizableLCA

variable {S : ShortComplex MetrizableLCA.{u}} {Y Z : MetrizableLCA.{u}}

/-- The product LCA group used before quotienting in the explicit pushout. -/
abbrev pushoutProductObj (S : ShortComplex MetrizableLCA.{u}) (Y : MetrizableLCA.{u}) :
    MetrizableLCA.{u} :=
  MetrizableLCA.of (S.X₂ × Y)

/-- The relation map `x ↦ (f x, -a x)` whose range is quotiented out. -/
def pushoutRelationMap (a : S.X₁ ⟶ Y) : S.X₁ →ₜ+ S.X₂ × Y where
  toFun x := (S.f x, -a x)
  map_zero' := by
    ext <;> simp
  map_add' := by
    intro x y
    ext
    · simp [map_add]
    · simp [map_add, add_comm]
  continuous_toFun := S.f.hom.continuous.prodMk (continuous_neg.comp a.hom.continuous)

/-- The additive subgroup generated by the pushout relation. -/
def pushoutSubgroup (a : S.X₁ ⟶ Y) : AddSubgroup (S.X₂ × Y) :=
  (pushoutRelationMap a).toAddMonoidHom.range

/-- The explicit pushout object, assuming the relation subgroup is closed. -/
noncomputable def pushoutObj (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) : MetrizableLCA.{u} :=
  quotientObj (pushoutProductObj S Y) (pushoutSubgroup a) hN

/-- The quotient map from the product to the explicit pushout. -/
noncomputable def pushoutQuotientMap (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    pushoutProductObj S Y ⟶ pushoutObj a hN :=
  quotientMap (pushoutProductObj S Y) (pushoutSubgroup a) hN

/-- The left product inclusion `X₂ ⟶ X₂ × Y`. -/
def pushoutProductInl (S : ShortComplex MetrizableLCA.{u}) (Y : MetrizableLCA.{u}) :
    S.X₂ ⟶ pushoutProductObj S Y where
  hom' :=
    { toFun := fun x => (x, (0 : Y))
      map_zero' := by ext <;> simp
      map_add' := by intro x y; ext <;> simp
      continuous_toFun := continuous_id.prodMk continuous_const }

/-- The right product inclusion `Y ⟶ X₂ × Y`. -/
def pushoutProductInr (S : ShortComplex MetrizableLCA.{u}) (Y : MetrizableLCA.{u}) :
    Y ⟶ pushoutProductObj S Y where
  hom' :=
    { toFun := fun y => ((0 : S.X₂), y)
      map_zero' := by ext <;> simp
      map_add' := by intro x y; ext <;> simp
      continuous_toFun := continuous_const.prodMk continuous_id }

/-- The canonical map `X₂ ⟶ pushoutObj`. -/
noncomputable def pushoutInl (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    S.X₂ ⟶ pushoutObj a hN :=
  pushoutProductInl S Y ≫ pushoutQuotientMap a hN

/-- The canonical map `Y ⟶ pushoutObj`. -/
noncomputable def pushoutInr (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    Y ⟶ pushoutObj a hN :=
  pushoutProductInr S Y ≫ pushoutQuotientMap a hN

@[simp]
lemma pushoutInl_apply (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) (x : S.X₂) :
    pushoutInl a hN x = ((x, (0 : Y)) : (S.X₂ × Y) ⧸ pushoutSubgroup a) :=
  rfl

@[simp]
lemma pushoutInr_apply (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) (y : Y) :
    pushoutInr a hN y = (((0 : S.X₂), y) : (S.X₂ × Y) ⧸ pushoutSubgroup a) :=
  rfl

lemma pushout_condition (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    S.f ≫ pushoutInl a hN = a ≫ pushoutInr a hN := by
  ext x
  apply QuotientAddGroup.eq_iff_sub_mem.mpr
  change (((S.f x, (0 : Y)) : S.X₂ × Y) - ((0 : S.X₂), a x)) ∈ pushoutSubgroup a
  have hsub : (((S.f x, (0 : Y)) - ((0 : S.X₂), a x) : S.X₂ × Y)) =
      (S.f x, -a x) := by
    ext <;> simp
  rw [hsub]
  exact ⟨x, rfl⟩

/-- The product map induced by a compatible cocone. -/
def pushoutProductDesc (b : S.X₂ ⟶ Z) (c : Y ⟶ Z) :
    pushoutProductObj S Y ⟶ Z where
  hom' :=
    { toFun := fun p => b p.1 + c p.2
      map_zero' := by simp
      map_add' := by intro x y; simp [map_add, add_assoc, add_left_comm, add_comm]
      continuous_toFun := (b.hom.continuous.comp continuous_fst).add
        (c.hom.continuous.comp continuous_snd) }

lemma pushoutProductDesc_relation_le_ker (a : S.X₁ ⟶ Y)
    {b : S.X₂ ⟶ Z} {c : Y ⟶ Z} (w : S.f ≫ b = a ≫ c) :
    pushoutSubgroup a ≤ (pushoutProductDesc b c).hom.toAddMonoidHom.ker := by
  intro p hp
  rcases hp with ⟨x, rfl⟩
  change b (S.f x) + c (-a x) = 0
  have hw : b (S.f x) = c (a x) :=
    congrArg (fun h : S.X₁ ⟶ Z => h x) w
  rw [map_neg, hw]
  simp

/-- The universal map out of the explicit pushout. -/
noncomputable def pushoutDesc (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y)))
    (b : S.X₂ ⟶ Z) (c : Y ⟶ Z) (w : S.f ≫ b = a ≫ c) :
    pushoutObj a hN ⟶ Z :=
  quotientLift (pushoutProductObj S Y) (pushoutSubgroup a) hN
    (pushoutProductDesc b c) (pushoutProductDesc_relation_le_ker a w)

@[simp]
lemma pushoutInl_desc (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y)))
    (b : S.X₂ ⟶ Z) (c : Y ⟶ Z) (w : S.f ≫ b = a ≫ c) :
    pushoutInl a hN ≫ pushoutDesc a hN b c w = b := by
  ext x
  change quotientLift (pushoutProductObj S Y) (pushoutSubgroup a) hN
    (pushoutProductDesc b c) (pushoutProductDesc_relation_le_ker a w)
      ((x, (0 : Y)) : (S.X₂ × Y) ⧸ pushoutSubgroup a) = b x
  rw [quotientLift_apply_mk]
  change b x + c (0 : Y) = b x
  simp

@[simp]
lemma pushoutInr_desc (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y)))
    (b : S.X₂ ⟶ Z) (c : Y ⟶ Z) (w : S.f ≫ b = a ≫ c) :
    pushoutInr a hN ≫ pushoutDesc a hN b c w = c := by
  ext y
  change quotientLift (pushoutProductObj S Y) (pushoutSubgroup a) hN
    (pushoutProductDesc b c) (pushoutProductDesc_relation_le_ker a w)
      (((0 : S.X₂), y) : (S.X₂ × Y) ⧸ pushoutSubgroup a) = c y
  rw [quotientLift_apply_mk]
  change b (0 : S.X₂) + c y = c y
  simp

lemma pushoutQuotientMap_eq_inl_add_inr (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) (p : S.X₂ × Y) :
    pushoutQuotientMap a hN p = pushoutInl a hN p.1 + pushoutInr a hN p.2 := by
  change ((p.1, p.2) : (S.X₂ × Y) ⧸ pushoutSubgroup a) =
    ((p.1, (0 : Y)) : (S.X₂ × Y) ⧸ pushoutSubgroup a) +
      (((0 : S.X₂), p.2) : (S.X₂ × Y) ⧸ pushoutSubgroup a)
  rw [← QuotientAddGroup.mk_add]
  have hp : (((p.1, (0 : Y)) + ((0 : S.X₂), p.2) : S.X₂ × Y)) = (p.1, p.2) := by
    ext <;> simp
  simp [hp]

lemma pushout_hom_ext (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y)))
    {T : MetrizableLCA.{u}} {k l : pushoutObj a hN ⟶ T}
    (hinl : pushoutInl a hN ≫ k = pushoutInl a hN ≫ l)
    (hinr : pushoutInr a hN ≫ k = pushoutInr a hN ≫ l) : k = l := by
  apply MetrizableLCA.ext
  intro q
  rcases quotientMap_surjective (pushoutProductObj S Y) (pushoutSubgroup a) hN q with ⟨p, rfl⟩
  change k (pushoutQuotientMap a hN p) = l (pushoutQuotientMap a hN p)
  rw [pushoutQuotientMap_eq_inl_add_inr a hN p]
  rw [map_add, map_add]
  congr 1
  · exact congrArg (fun h : S.X₂ ⟶ T => h p.1) hinl
  · exact congrArg (fun h : Y ⟶ T => h p.2) hinr

/-- The explicit pushout cocone. -/
noncomputable def pushoutCocone (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) : PushoutCocone S.f a :=
  PushoutCocone.mk (pushoutInl a hN) (pushoutInr a hN) (pushout_condition a hN)

/-- The explicit pushout cocone is colimiting, assuming the relation subgroup is closed. -/
noncomputable def pushoutIsColimit (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    IsColimit (pushoutCocone a hN) :=
  PushoutCocone.IsColimit.mk (pushout_condition a hN)
    (fun s => pushoutDesc a hN s.inl s.inr s.condition)
    (fun s => pushoutInl_desc a hN s.inl s.inr s.condition)
    (fun s => pushoutInr_desc a hN s.inl s.inr s.condition)
    (fun s m hleft hright => by
      apply pushout_hom_ext a hN
      · rw [hleft, pushoutInl_desc]
      · rw [hright, pushoutInr_desc])

/-- A `HasPushout` witness supplied by the explicit quotient construction. -/
@[reducible]
noncomputable def hasPushout_of_pushoutSubgroup_closed (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) : HasPushout S.f a where
  exists_colimit := ⟨⟨pushoutCocone a hN, pushoutIsColimit a hN⟩⟩

/-- The product map `(x₂, y) ↦ g x₂` used to descend the cokernel map from the pushout. -/
def pushoutProductToCokernel (S : ShortComplex MetrizableLCA.{u}) (Y : MetrizableLCA.{u}) :
    pushoutProductObj S Y ⟶ S.X₃ where
  hom' :=
    { toFun := fun p => S.g p.1
      map_zero' := by simp
      map_add' := by intro x y; simp [map_add]
      continuous_toFun := S.g.hom.continuous.comp continuous_fst }

lemma pushoutProductToCokernel_relation_le_ker (a : S.X₁ ⟶ Y) :
    pushoutSubgroup a ≤ (pushoutProductToCokernel S Y).hom.toAddMonoidHom.ker := by
  intro p hp
  rcases hp with ⟨x, rfl⟩
  change S.g (S.f x) = 0
  exact congrArg (fun h : S.X₁ ⟶ S.X₃ => h x) S.zero

/-- The induced map from the explicit pushout to the original cokernel term. -/
noncomputable def pushoutCokernelMap (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    pushoutObj a hN ⟶ S.X₃ :=
  quotientLift (pushoutProductObj S Y) (pushoutSubgroup a) hN
    (pushoutProductToCokernel S Y) (pushoutProductToCokernel_relation_le_ker a)

@[simp]
lemma pushoutQuotientMap_cokernel (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    pushoutQuotientMap a hN ≫ pushoutCokernelMap a hN =
      pushoutProductToCokernel S Y := by
  exact quotientLift_quotientMap (pushoutProductObj S Y) (pushoutSubgroup a) hN
    (pushoutProductToCokernel S Y) (pushoutProductToCokernel_relation_le_ker a)

@[simp]
lemma pushoutInl_cokernel (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    pushoutInl a hN ≫ pushoutCokernelMap a hN = S.g := by
  ext x
  rfl

@[simp]
lemma pushoutInr_cokernel (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    pushoutInr a hN ≫ pushoutCokernelMap a hN = 0 := by
  ext y
  change quotientLift (pushoutProductObj S Y) (pushoutSubgroup a) hN
    (pushoutProductToCokernel S Y) (pushoutProductToCokernel_relation_le_ker a)
      (((0 : S.X₂), y) : (S.X₂ × Y) ⧸ pushoutSubgroup a) = 0
  rw [quotientLift_apply_mk]
  change S.g (0 : S.X₂) = 0
  simp

lemma pushoutProductToCokernel_openMap (hS : strictShortExact S) (Y : MetrizableLCA.{u}) :
    IsOpenMap (pushoutProductToCokernel S Y : pushoutProductObj S Y → S.X₃) := by
  have h : IsOpenMap (fun p : S.X₂ × Y => S.g p.1) :=
    hS.open_map.comp isOpenMap_fst
  simpa [pushoutProductToCokernel] using h

lemma pushoutCokernelMap_openMap (hS : strictShortExact S) (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    IsOpenMap (pushoutCokernelMap a hN : pushoutObj a hN → S.X₃) := by
  intro U hU
  let q : pushoutProductObj S Y ⟶ pushoutObj a hN := pushoutQuotientMap a hN
  let e : pushoutObj a hN ⟶ S.X₃ := pushoutCokernelMap a hN
  have hpre : IsOpen ((q : pushoutProductObj S Y → pushoutObj a hN) ⁻¹' U) :=
    q.hom.continuous.isOpen_preimage U hU
  have himage : (e : pushoutObj a hN → S.X₃) '' U =
      (pushoutProductToCokernel S Y : pushoutProductObj S Y → S.X₃) ''
        ((q : pushoutProductObj S Y → pushoutObj a hN) ⁻¹' U) := by
    ext z
    constructor
    · rintro ⟨u, huU, rfl⟩
      rcases quotientMap_surjective (pushoutProductObj S Y) (pushoutSubgroup a) hN u with
        ⟨p, hp⟩
      refine ⟨p, ?_, ?_⟩
      · have hpq : q p = u := by
          simpa [q] using hp
        change q p ∈ U
        rw [hpq]
        exact huU
      · have hpq : q p = u := by
          simpa [q] using hp
        have hcomp' : e (q p) = (pushoutProductToCokernel S Y) p := by
          exact congrArg (fun h : pushoutProductObj S Y ⟶ S.X₃ => h p)
            (pushoutQuotientMap_cokernel a hN)
        rw [← hcomp', hpq]
    · rintro ⟨p, hpU, hpz⟩
      refine ⟨q p, hpU, ?_⟩
      have hcomp' : e (q p) = (pushoutProductToCokernel S Y) p := by
        exact congrArg (fun h : pushoutProductObj S Y ⟶ S.X₃ => h p)
          (pushoutQuotientMap_cokernel a hN)
      exact hcomp'.trans hpz
  rw [himage]
  exact pushoutProductToCokernel_openMap hS Y _ hpre

lemma pushoutCokernelMap_surjective (hS : strictShortExact S) (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    Function.Surjective (pushoutCokernelMap a hN : pushoutObj a hN → S.X₃) := by
  intro z
  rcases hS.surjective z with ⟨x, hx⟩
  refine ⟨pushoutInl a hN x, ?_⟩
  change S.g x = z
  exact hx

lemma pushoutCokernelMap_algebraic_exact (hS : strictShortExact S) (a : S.X₁ ⟶ Y)
    (hN : IsClosed (pushoutSubgroup a : Set (S.X₂ × Y))) :
    ∀ q : pushoutObj a hN, pushoutCokernelMap a hN q = 0 →
      ∃ y : Y, pushoutInr a hN y = q := by
  intro q hq
  rcases quotientMap_surjective (pushoutProductObj S Y) (pushoutSubgroup a) hN q with ⟨p, rfl⟩
  have hg : S.g p.1 = 0 := by
    have hcomp := congrArg (fun h : pushoutProductObj S Y ⟶ S.X₃ => h p)
      (pushoutQuotientMap_cokernel a hN)
    simpa [pushoutProductToCokernel] using hcomp.symm.trans hq
  rcases hS.algebraic_exact p.1 hg with ⟨x, hx⟩
  refine ⟨p.2 + a x, ?_⟩
  apply QuotientAddGroup.eq_iff_sub_mem.mpr
  change ((((0 : S.X₂), p.2 + a x) : S.X₂ × Y) - (p.1, p.2)) ∈ pushoutSubgroup a
  have hdiff : ((((0 : S.X₂), p.2 + a x) : S.X₂ × Y) - (p.1, p.2)) =
      -((S.f x, -a x) : S.X₂ × Y) := by
    ext
    · simp [hx]
    · simp
  rw [hdiff]
  exact AddSubgroup.neg_mem _ ⟨x, rfl⟩

end MetrizableLCA

end LeanLCAExactChallenge
