import LeanLCAExactChallenge

set_option autoImplicit false

/-!
Lean-native original four-task contract audit surface.

This file is intentionally nonterminal for the current source tree: it checks the public names from
the immutable contract and records, in Lean, that the current task-4 surface still has not supplied a
contract-completing stable bounded derived infinity-category witness.
-/

#check LeanLCAExactChallenge.QuillenExactCategory
#check LeanLCAExactChallenge.QuillenExactCategory.Conflation
#check LeanLCAExactChallenge.QuillenExactCategory.inflation
#check LeanLCAExactChallenge.QuillenExactCategory.deflation
#check LeanLCAExactChallenge.QuillenExactCategory.split_conflation
#check LeanLCAExactChallenge.QuillenExactCategory.pushout_inflation
#check LeanLCAExactChallenge.QuillenExactCategory.pullback_deflation

#check LeanLCAExactChallenge.MetrizableLCA
#check LeanLCAExactChallenge.MetrizableLCA.Hom
#check LeanLCAExactChallenge.MetrizableLCA.strictShortExact
#check LeanLCAExactChallenge.MetrizableLCA.closed_inclusion_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.open_surjection_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.algebraic_kernel_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.algebraic_cokernel_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.quillenExactCategory

#check LeanLCAExactChallenge.YonedaExt
#check LeanLCAExactChallenge.YonedaExt.zero_equiv_hom
#check LeanLCAExactChallenge.YonedaExt.baer_sum
#check LeanLCAExactChallenge.YonedaExt.instAddCommGroup

#check LeanLCAExactChallenge.BoundedDerivedInfinityCategory
#check LeanLCAExactChallenge.Dbounded
#check LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfMetrizableStableInstances
#check LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfMetrizableLeftCalculusStableRoute
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfKernelCokernelComparisonW830
#check LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfMetrizableDirectLeftCalculusRouteW830
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfComparisonBijectivityW831
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfComparisonBijectivityLeftCalculusW831
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfTargetExactAtW832
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfTargetExactAtLeftCalculusW832
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfTargetIsoW833
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfTargetIsoLeftCalculusW833

namespace LeanLCAExactChallenge

theorem originalFourTaskContract_currentOrdinaryRouteRejected :
    Dbounded.StableRouteAttempt.accepted
      (Dbounded.currentOrdinaryStableRouteAttempt MetrizableLCA.{0}) = false :=
  Dbounded.currentOrdinaryStableRouteAttempt_rejected MetrizableLCA.{0}

theorem originalFourTaskContract_currentSemanticRouteNonterminal :
    Dbounded.currentMetrizableSemanticStableRouteState.productSuccessClaimed = false :=
  Dbounded.currentMetrizableSemanticStableRouteState_productSuccess

theorem originalFourTaskContract_typeclassStableRoute_remainingFieldCount :
    Dbounded.metrizableStableInstanceFieldNames.length = 7 :=
  Dbounded.metrizableStableInstanceFieldNames_count

theorem originalFourTaskContract_leftCalculusStableRoute_requiredFieldCount :
    Dbounded.metrizableLeftCalculusStableRouteRequiredFieldNames.length = 5 :=
  Dbounded.metrizableLeftCalculusStableRouteRequiredFieldNames_count

theorem originalFourTaskContract_directLeftCalculusRoute_concreteInputCount :
    Dbounded.metrizableDirectBoundedLeftCalculusInputNamesW830.length = 4 :=
  Dbounded.metrizableDirectBoundedLeftCalculusInputNamesW830_count

theorem originalFourTaskContract_directLeftCalculusStableRoute_expandedRequiredFieldCount :
    Dbounded.metrizableDirectLeftCalculusStableRouteExpandedRequiredFieldNamesW830.length =
      8 :=
  Dbounded.metrizableDirectLeftCalculusStableRouteExpandedRequiredFieldNamesW830_count

theorem originalFourTaskContract_comparisonBijectivityLeftCalculusRoute_concreteInputCount :
    Dbounded.metrizableComparisonBijectivityLeftCalculusInputNamesW831.length = 3 :=
  Dbounded.metrizableComparisonBijectivityLeftCalculusInputNamesW831_count

theorem originalFourTaskContract_comparisonBijectivityLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.metrizableComparisonBijectivityLeftCalculusStableRouteExpandedRequiredFieldNamesW831.length =
      7 :=
  Dbounded.metrizableComparisonBijectivityLeftCalculusStableRouteExpandedRequiredFieldNamesW831_count

theorem originalFourTaskContract_targetExactAtLeftCalculusRoute_concreteInputCount :
    Dbounded.targetExactAtLeftCalculusInputNamesW832.length = 3 :=
  Dbounded.targetExactAtLeftCalculusInputNamesW832_count

theorem originalFourTaskContract_targetExactAtLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.targetExactAtLeftCalculusExpandedRequiredFieldNamesW832.length = 7 :=
  Dbounded.targetExactAtLeftCalculusExpandedRequiredFieldNamesW832_count

theorem originalFourTaskContract_targetIsoLeftCalculusRoute_concreteInputCount :
    Dbounded.targetIsoLeftCalculusInputNamesW833.length = 3 :=
  Dbounded.targetIsoLeftCalculusInputNamesW833_count

theorem originalFourTaskContract_targetIsoLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.targetIsoLeftCalculusExpandedRequiredFieldNamesW833.length = 7 :=
  Dbounded.targetIsoLeftCalculusExpandedRequiredFieldNamesW833_count

end LeanLCAExactChallenge
