import LeanLCAExactChallenge
import LeanLCAExactChallenge.Derived.TargetHomologyZeroFiniteShapeStableRoute
import LeanLCAExactChallenge.Derived.TargetHomologyZeroDirectLocalizationStableRoute
import LeanLCAExactChallenge.Derived.TargetHomologyZeroDirectSourceStableRoute
import LeanLCAExactChallenge.Derived.TargetExactAtDirectSourceStableRoute
import LeanLCAExactChallenge.Derived.TargetIsoDirectSourceStableRoute
import LeanLCAExactChallenge.Derived.IsoClosureDirectSourceStableRoute
import LeanLCAExactChallenge.Derived.StrictRealizationDirectSourceStableRoute
import LeanLCAExactChallenge.Derived.ExactAcyclicSelectedCochainStrictificationRoute
import LeanLCAExactChallenge.Derived.ExactAcyclicSelectedCochainClosed2Route
import LeanLCAExactChallenge.Derived.ExactAcyclicSelectedCochainExactInputsRoute
import LeanLCAExactChallenge.Derived.ExactInputsSelectedCochainDirectSourceStableRoute
import LeanLCAExactChallenge.Derived.ExactInputsComparisonSelectedCochainStableRoute
import LeanLCAExactChallenge.Derived.RouteDataSelectedCochainStableRoute
import LeanLCAExactChallenge.Derived.HomologyFreeSelectedCochainStableRoute
import LeanLCAExactChallenge.Derived.HomologyFreeRouteDataProviderFromRouteData
import LeanLCAExactChallenge.Derived.RouteDataProviderFromComparisonBijectivity
import LeanLCAExactChallenge.Derived.EndpointTopologyFromClosednessBranch
import LeanLCAExactChallenge.Derived.EndpointKernelCokernelFromClosednessBranch
import LeanLCAExactChallenge.Derived.EndpointKernelCokernelLocalizedFromClosednessBranch
import LeanLCAExactChallenge.Derived.TargetExactAtFromClosednessBranch
import LeanLCAExactChallenge.Derived.TargetExactAtEndpointLocalizedFromClosednessBranch
import LeanLCAExactChallenge.Derived.TargetExactAtConcreteLeavesFromClosednessBranch
import LeanLCAExactChallenge.Derived.TargetExactAtConcreteLeavesFromTargetHomologyZero
import LeanLCAExactChallenge.Derived.TargetExactAtConcreteLeavesStableFromTargetHomologyZero
import LeanLCAExactChallenge.Derived.TargetExactAtDirectSourceStableExactAtRoute
import LeanLCAExactChallenge.Derived.TargetIsoDirectSourceStableExactAtRoute
import LeanLCAExactChallenge.Derived.IsoClosureDirectSourceStableExactAtRoute
import LeanLCAExactChallenge.Derived.StrictRealizationDirectSourceStableExactAtRoute
import LeanLCAExactChallenge.Derived.ExactAcyclicSelectedCochainDirectSourceStableExactAtRoute
import LeanLCAExactChallenge.Derived.ExactInputsSelectedCochainDirectSourceStableExactAtRoute
import LeanLCAExactChallenge.Derived.ExactInputsComparisonSelectedCochainStableExactAtRoute
import LeanLCAExactChallenge.Derived.RouteDataSelectedCochainStableExactAtRoute
import LeanLCAExactChallenge.Derived.HomologyFreeSelectedCochainStableExactAtRoute
import LeanLCAExactChallenge.Derived.EndpointFactsHomologyFreeSelectedCochainStableExactAtRoute
import LeanLCAExactChallenge.Derived.EndpointLocalizedHomologyFreeSelectedCochainStableExactAtRoute
import LeanLCAExactChallenge.Derived.W732SelectedCochainStableExactAtRoute
import LeanLCAExactChallenge.Derived.W735W732SelectedCochainStableExactAtRoute
import LeanLCAExactChallenge.Derived.W733ConcreteLeavesSelectedCochainStableExactAtRoute
import LeanLCAExactChallenge.Derived.SelectedCochainConcreteLeavesStableExactAtRoute
import LeanLCAExactChallenge.Derived.ComparisonSelectedCochainConcreteLeavesStableExactAtRoute
import LeanLCAExactChallenge.Derived.HomologyFreeComparisonConcreteLeavesStableExactAtRoute
import LeanLCAExactChallenge.Derived.EndpointLocalizedComparisonConcreteLeavesStableExactAtRoute
import LeanLCAExactChallenge.Derived.W732ComparisonConcreteLeavesStableExactAtRoute
import LeanLCAExactChallenge.Derived.W733ConcreteLeavesComparisonConcreteLeavesStableExactAtRoute
import LeanLCAExactChallenge.Derived.SourceTriangulationComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.SourceTriangulationFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.EndpointStrictTopologyFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.LocalizedRightAdjointFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.NormalizedFixedTargetFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.NormalizedLiftBlueprintFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.StrictRepresentativeLiftFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.StrictPreimageObjectFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.StrictPreimageMapFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.BoundaryFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.RelationFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.TargetSurjectiveCompactFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedMapClosednessFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedEmbeddingClosednessFieldsComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedEmbeddingEndpointHomologyFreeComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedMapEndpointHomologyFreeComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedMapEndpointFactsLocalizedRightAdjointComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedMapSourceTriangulationEndpointFactsLocalizedRightAdjointComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryDataSourceTriangulationEndpointFactsLocalizedRightAdjointComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedMapRelationDataBoundaryDataSourceTriangulationEndpointFactsLocalizedRightAdjointComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedMapTargetSurjectiveCompactRelationDataBoundaryDataSourceTriangulationEndpointFactsLocalizedRightAdjointComparisonStableExactAtRoute
import LeanLCAExactChallenge.Derived.ClosedMapMappedCokernelFieldTargetDataEndpointFactsRoute
import LeanLCAExactChallenge.Derived.ClosedMapComponentFieldsMappedCokernelFieldTargetDataEndpointFactsRoute
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryFieldsComponentFieldsMappedCokernelFieldTargetDataEndpointFactsRoute
import LeanLCAExactChallenge.Derived.ClosedMapRelationFieldsBoundaryFieldsComponentFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapTargetFieldsRelationFieldsBoundaryFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapSourceFieldsTargetFieldsRelationFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapEndpointFieldsSourceFieldsTargetFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapLocalizedRightAdjointFieldsEndpointFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapFixedTargetUniqFieldsLocalizedRightAdjointFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapSelectedDifferenceFieldsFixedTargetUniqFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapTargetRawFieldsSelectedDifferenceFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapRelationRawFieldsTargetRawFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRawFieldsRelationRawFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapTriangleCompletionRawFieldBoundaryRawFieldsRoute
import LeanLCAExactChallenge.Derived.ClosedMapSourceRawFieldsTriangleCompletionRawFieldRoute
import LeanLCAExactChallenge.Derived.ClosedMapRelationPrimitiveFieldsSourceRawFieldsRoute

set_option autoImplicit false

/-!
Lean-native original four-task contract audit surface.

This file is intentionally nonterminal for the current source tree: it checks the public names from
the immutable contract and records, in Lean, that the current task-4 surface still has not supplied a
contract-completing stable bounded derived infinity-category witness.
-/

#check LeanLCAExactChallenge.QuillenExactCategory
#check LeanLCAExactChallenge.QuillenExactCategory.Conflation
#check LeanLCAExactChallenge.QuillenExactCategory.inflation
#check LeanLCAExactChallenge.QuillenExactCategory.deflation
#check LeanLCAExactChallenge.QuillenExactCategory.split_conflation
#check LeanLCAExactChallenge.QuillenExactCategory.pushout_inflation
#check LeanLCAExactChallenge.QuillenExactCategory.pullback_deflation

#check LeanLCAExactChallenge.MetrizableLCA
#check LeanLCAExactChallenge.MetrizableLCA.Hom
#check LeanLCAExactChallenge.MetrizableLCA.strictShortExact
#check LeanLCAExactChallenge.MetrizableLCA.closed_inclusion_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.open_surjection_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.algebraic_kernel_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.algebraic_cokernel_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.quillenExactCategory

#check LeanLCAExactChallenge.YonedaExt
#check LeanLCAExactChallenge.YonedaExt.zero_equiv_hom
#check LeanLCAExactChallenge.YonedaExt.baer_sum
#check LeanLCAExactChallenge.YonedaExt.instAddCommGroup

#check LeanLCAExactChallenge.BoundedDerivedInfinityCategory
#check LeanLCAExactChallenge.Dbounded
#check LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfMetrizableStableInstances
#check LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfMetrizableLeftCalculusStableRoute
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfKernelCokernelComparisonW830
#check LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfMetrizableDirectLeftCalculusRouteW830
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfComparisonBijectivityW831
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfComparisonBijectivityLeftCalculusW831
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfTargetExactAtW832
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfTargetExactAtLeftCalculusW832
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfTargetIsoW833
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfTargetIsoLeftCalculusW833
#check LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfIsoClosureRealizationW834
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfIsoClosureLeftCalculusW834
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapExactInputsIsoClosureW835
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingExactInputsIsoClosureW835
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapExactInputsIsoClosureW835
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingExactInputsIsoClosureW835
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapBranchLocalizedW836
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingBranchLocalizedW836
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapBranchLocalizedW836
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingBranchLocalizedW836
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapStrictRealizationW837
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingStrictRealizationW837
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapStrictRealizationW837
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingStrictRealizationW837
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapComparisonBijectivityStrictRealizationW838
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingComparisonBijectivityStrictRealizationW838
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapComparisonBijectivityStrictRealizationW838
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingComparisonBijectivityStrictRealizationW838
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapTargetHomologyZeroW839
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingTargetHomologyZeroW839
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetHomologyZeroW839
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingTargetHomologyZeroW839
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapTargetHomologyZeroFiniteShapeW840
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingTargetHomologyZeroFiniteShapeW840
#check
  LeanLCAExactChallenge.Dbounded.finiteLimitsOfClosedMapTargetHomologyZeroFiniteShapeW840
#check
  LeanLCAExactChallenge.Dbounded.finiteColimitsOfClosedMapTargetHomologyZeroFiniteShapeW840
#check
  LeanLCAExactChallenge.Dbounded.finiteLimitsOfClosedEmbeddingTargetHomologyZeroFiniteShapeW840
#check
  LeanLCAExactChallenge.Dbounded.finiteColimitsOfClosedEmbeddingTargetHomologyZeroFiniteShapeW840
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetHomologyZeroFiniteShapeW840
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingTargetHomologyZeroFiniteShapeW840
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapTargetHomologyZeroDirectLocalizationW841
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingTargetHomologyZeroDirectLocalizationW841
#check
  LeanLCAExactChallenge.Dbounded.pretriangulatedOfClosedMapTargetHomologyZeroDirectLocalizationW841
#check
  LeanLCAExactChallenge.Dbounded.triangulatedOfClosedMapTargetHomologyZeroDirectLocalizationW841
#check
  LeanLCAExactChallenge.Dbounded.remainingStableFieldsOfClosedMapTargetHomologyZeroDirectLocalizationW841
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetHomologyZeroDirectLocalizationW841
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingTargetHomologyZeroDirectLocalizationW841
#check
  LeanLCAExactChallenge.Dbounded.closedMapDirectSourceOfTargetHomologyZeroW842
#check
  LeanLCAExactChallenge.Dbounded.closedMapDirectLocalizationOfTargetHomologyZeroW842
#check
  LeanLCAExactChallenge.Dbounded.remainingStableFieldsOfClosedMapTargetHomologyZeroDirectSourceW842
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetHomologyZeroDirectSourceW842
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingTargetHomologyZeroDirectSourceW842
#check LeanLCAExactChallenge.Dbounded.closedMapW803DataOfTargetExactAtW843
#check
  LeanLCAExactChallenge.Dbounded.closedMapTargetHomologyZeroDataOfTargetExactAtW843
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetExactAtDirectSourceW843
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingTargetExactAtDirectSourceW843
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapTargetExactAtDirectSourceStableExactAtW864
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetExactAtDirectSourceStableExactAtW864
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapTargetIsoDirectSourceStableExactAtW865
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetIsoDirectSourceStableExactAtW865
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapIsoClosureDirectSourceStableExactAtW866
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapIsoClosureDirectSourceStableExactAtW866
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapStrictRealizationDirectSourceStableExactAtW867
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapStrictRealizationDirectSourceStableExactAtW867
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapSelectedCochainDirectSourceStableExactAtW868
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapSelectedCochainDirectSourceStableExactAtW868
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapExactInputsSelectedCochainStableExactAtW869
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapExactInputsSelectedCochainStableExactAtW869
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapComparisonSelectedCochainStableExactAtW870
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapComparisonSelectedCochainStableExactAtW870
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfRouteDataComparisonSelectedCochainStableExactAtW871
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfRouteDataComparisonSelectedCochainStableExactAtW871
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfHomologyFreeComparisonSelectedCochainStableExactAtW872
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfHomologyFreeComparisonSelectedCochainStableExactAtW872
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfEndpointFactsHomologyFreeSelectedCochainStableExactAtW873
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfEndpointFactsHomologyFreeSelectedCochainStableExactAtW873
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfEndpointLocalizedHomologyFreeSelectedCochainStableExactAtW874
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfEndpointLocalizedHomologyFreeSelectedCochainStableExactAtW874
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfW732SelectedCochainStableExactAtW875
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfW732SelectedCochainStableExactAtW875
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapW735W732SelectedCochainStableExactAtW876
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingW735W732SelectedCochainStableExactAtW876
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapW735W732SelectedCochainStableExactAtW876
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingW735W732SelectedCochainStableExactAtW876
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfConcreteLeavesSelectedCochainStableExactAtW877
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfConcreteLeavesSelectedCochainStableExactAtW877
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapSelectedCochainConcreteLeavesStableExactAtW878
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingSelectedCochainConcreteLeavesStableExactAtW878
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapSelectedCochainConcreteLeavesStableExactAtW878
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingSelectedCochainConcreteLeavesStableExactAtW878
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedMapComparisonConcreteLeavesStableExactAtW879
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfClosedEmbeddingComparisonConcreteLeavesStableExactAtW879
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapComparisonConcreteLeavesStableExactAtW879
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingComparisonConcreteLeavesStableExactAtW879
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfHomologyFreeComparisonConcreteLeavesStableExactAtW880
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfHomologyFreeComparisonConcreteLeavesStableExactAtW880
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfEndpointLocalizedComparisonConcreteLeavesStableExactAtW881
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfEndpointLocalizedComparisonConcreteLeavesStableExactAtW881
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfW732ComparisonConcreteLeavesStableExactAtW882
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfW732ComparisonConcreteLeavesStableExactAtW882
#check
  LeanLCAExactChallenge.Dbounded.directBoundedLeftCalculusOfConcreteLeavesComparisonStableExactAtW883
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfConcreteLeavesComparisonStableExactAtW883
#check LeanLCAExactChallenge.Dbounded.closedMapW808DataOfTargetIsoW844
#check LeanLCAExactChallenge.Dbounded.closedMapW803DataOfTargetIsoW844
#check
  LeanLCAExactChallenge.Dbounded.closedMapTargetHomologyZeroDataOfTargetIsoW844
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetIsoDirectSourceW844
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingTargetIsoDirectSourceW844
#check
  LeanLCAExactChallenge.Dbounded.targetIsoRealizationOfIsoClosureDirectSourceW845
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapIsoClosureDirectSourceW845
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingIsoClosureDirectSourceW845
#check
  LeanLCAExactChallenge.Dbounded.closedMapIsoClosureDataOfStrictDirectSourceW846
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapStrictDirectSourceW846
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingStrictDirectSourceW846
#check
  LeanLCAExactChallenge.exactAcyclicHomotopyObjectTrianglehIso13Realization_of_selected_cochain
#check
  LeanLCAExactChallenge.Dbounded.trianglehRealizationOfSelectedCochainStrictificationW847
#check
  LeanLCAExactChallenge.Dbounded.closedMapStrictRealizationDataOfSelectedCochainW847
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedMapSelectedCochainW847
#check
  LeanLCAExactChallenge.Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingSelectedCochainW847

namespace LeanLCAExactChallenge

theorem originalFourTaskContract_currentOrdinaryRouteRejected :
    Dbounded.StableRouteAttempt.accepted
      (Dbounded.currentOrdinaryStableRouteAttempt MetrizableLCA.{0}) = false :=
  Dbounded.currentOrdinaryStableRouteAttempt_rejected MetrizableLCA.{0}

theorem originalFourTaskContract_currentSemanticRouteNonterminal :
    Dbounded.currentMetrizableSemanticStableRouteState.productSuccessClaimed = false :=
  Dbounded.currentMetrizableSemanticStableRouteState_productSuccess

theorem originalFourTaskContract_typeclassStableRoute_remainingFieldCount :
    Dbounded.metrizableStableInstanceFieldNames.length = 7 :=
  Dbounded.metrizableStableInstanceFieldNames_count

theorem originalFourTaskContract_leftCalculusStableRoute_requiredFieldCount :
    Dbounded.metrizableLeftCalculusStableRouteRequiredFieldNames.length = 5 :=
  Dbounded.metrizableLeftCalculusStableRouteRequiredFieldNames_count

theorem originalFourTaskContract_directLeftCalculusRoute_concreteInputCount :
    Dbounded.metrizableDirectBoundedLeftCalculusInputNamesW830.length = 4 :=
  Dbounded.metrizableDirectBoundedLeftCalculusInputNamesW830_count

theorem originalFourTaskContract_directLeftCalculusStableRoute_expandedRequiredFieldCount :
    Dbounded.metrizableDirectLeftCalculusStableRouteExpandedRequiredFieldNamesW830.length =
      8 :=
  Dbounded.metrizableDirectLeftCalculusStableRouteExpandedRequiredFieldNamesW830_count

theorem originalFourTaskContract_comparisonBijectivityLeftCalculusRoute_concreteInputCount :
    Dbounded.metrizableComparisonBijectivityLeftCalculusInputNamesW831.length = 3 :=
  Dbounded.metrizableComparisonBijectivityLeftCalculusInputNamesW831_count

theorem originalFourTaskContract_comparisonBijectivityLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.metrizableComparisonBijectivityLeftCalculusStableRouteExpandedRequiredFieldNamesW831.length =
      7 :=
  Dbounded.metrizableComparisonBijectivityLeftCalculusStableRouteExpandedRequiredFieldNamesW831_count

theorem originalFourTaskContract_targetExactAtLeftCalculusRoute_concreteInputCount :
    Dbounded.targetExactAtLeftCalculusInputNamesW832.length = 3 :=
  Dbounded.targetExactAtLeftCalculusInputNamesW832_count

theorem originalFourTaskContract_targetExactAtLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.targetExactAtLeftCalculusExpandedRequiredFieldNamesW832.length = 7 :=
  Dbounded.targetExactAtLeftCalculusExpandedRequiredFieldNamesW832_count

theorem originalFourTaskContract_targetIsoLeftCalculusRoute_concreteInputCount :
    Dbounded.targetIsoLeftCalculusInputNamesW833.length = 3 :=
  Dbounded.targetIsoLeftCalculusInputNamesW833_count

theorem originalFourTaskContract_targetIsoLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.targetIsoLeftCalculusExpandedRequiredFieldNamesW833.length = 7 :=
  Dbounded.targetIsoLeftCalculusExpandedRequiredFieldNamesW833_count

theorem originalFourTaskContract_isoClosureLeftCalculusRoute_concreteInputCount :
    Dbounded.isoClosureLeftCalculusInputNamesW834.length = 3 :=
  Dbounded.isoClosureLeftCalculusInputNamesW834_count

theorem originalFourTaskContract_isoClosureLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.isoClosureLeftCalculusExpandedRequiredFieldNamesW834.length = 7 :=
  Dbounded.isoClosureLeftCalculusExpandedRequiredFieldNamesW834_count

theorem originalFourTaskContract_exactInputsIsoClosureLeftCalculusRoute_concreteInputCount :
    Dbounded.exactInputsIsoClosureLeftCalculusInputNamesW835.length = 3 :=
  Dbounded.exactInputsIsoClosureLeftCalculusInputNamesW835_count

theorem originalFourTaskContract_exactInputsIsoClosureLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.exactInputsIsoClosureLeftCalculusExpandedRequiredFieldNamesW835.length =
      7 :=
  Dbounded.exactInputsIsoClosureLeftCalculusExpandedRequiredFieldNamesW835_count

theorem originalFourTaskContract_branchLocalizedExactInputsLeftCalculusRoute_concreteInputCount :
    Dbounded.branchLocalizedExactInputsLeftCalculusInputNamesW836.length =
      2 :=
  Dbounded.branchLocalizedExactInputsLeftCalculusInputNamesW836_count

theorem originalFourTaskContract_branchLocalizedExactInputsLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.branchLocalizedExactInputsLeftCalculusExpandedRequiredFieldNamesW836.length =
      6 :=
  Dbounded.branchLocalizedExactInputsLeftCalculusExpandedRequiredFieldNamesW836_count

theorem originalFourTaskContract_strictRealizationLeftCalculusRoute_concreteInputCount :
    Dbounded.strictRealizationLeftCalculusInputNamesW837.length =
      3 :=
  Dbounded.strictRealizationLeftCalculusInputNamesW837_count

theorem originalFourTaskContract_strictRealizationLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.strictRealizationLeftCalculusExpandedRequiredFieldNamesW837.length =
      7 :=
  Dbounded.strictRealizationLeftCalculusExpandedRequiredFieldNamesW837_count

theorem originalFourTaskContract_comparisonBijectivityStrictRealizationLeftCalculusRoute_concreteInputCount :
    Dbounded.comparisonBijectivityStrictRealizationLeftCalculusInputNamesW838.length =
      2 :=
  Dbounded.comparisonBijectivityStrictRealizationLeftCalculusInputNamesW838_count

theorem originalFourTaskContract_comparisonBijectivityStrictRealizationLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.comparisonBijectivityStrictRealizationLeftCalculusExpandedRequiredFieldNamesW838.length =
      6 :=
  Dbounded.comparisonBijectivityStrictRealizationLeftCalculusExpandedRequiredFieldNamesW838_count

theorem originalFourTaskContract_targetHomologyZeroStrictRealizationLeftCalculusRoute_concreteInputCount :
    Dbounded.targetHomologyZeroStrictRealizationLeftCalculusInputNamesW839.length =
      2 :=
  Dbounded.targetHomologyZeroStrictRealizationLeftCalculusInputNamesW839_count

theorem originalFourTaskContract_targetHomologyZeroStrictRealizationLeftCalculusRoute_expandedRequiredFieldCount :
    Dbounded.targetHomologyZeroStrictRealizationLeftCalculusExpandedRequiredFieldNamesW839.length =
      6 :=
  Dbounded.targetHomologyZeroStrictRealizationLeftCalculusExpandedRequiredFieldNamesW839_count

theorem originalFourTaskContract_targetHomologyZeroFiniteShapeStableRoute_bundledInputCount :
    Dbounded.targetHomologyZeroFiniteShapeStableRouteInputNamesW840.length =
      2 :=
  Dbounded.targetHomologyZeroFiniteShapeStableRouteInputNamesW840_count

theorem originalFourTaskContract_targetHomologyZeroFiniteShapeStableRoute_requiredFieldCount :
    Dbounded.targetHomologyZeroFiniteShapeStableRouteRequiredFieldNamesW840.length =
      4 :=
  Dbounded.targetHomologyZeroFiniteShapeStableRouteRequiredFieldNamesW840_count

theorem originalFourTaskContract_targetHomologyZeroFiniteShapeStableRoute_expandedRequiredFieldCount :
    Dbounded.targetHomologyZeroFiniteShapeStableRouteExpandedRequiredFieldNamesW840.length =
      5 :=
  Dbounded.targetHomologyZeroFiniteShapeStableRouteExpandedRequiredFieldNamesW840_count

theorem originalFourTaskContract_targetHomologyZeroDirectLocalizationStableRoute_bundledInputCount :
    Dbounded.targetHomologyZeroDirectLocalizationStableRouteInputNamesW841.length =
      3 :=
  Dbounded.targetHomologyZeroDirectLocalizationStableRouteInputNamesW841_count

theorem
    originalFourTaskContract_targetHomologyZeroDirectLocalizationStableRoute_expandedRequiredFieldCount :
    Dbounded.targetHomologyZeroDirectLocalizationStableRouteExpandedRequiredFieldNamesW841.length =
      4 :=
  Dbounded.targetHomologyZeroDirectLocalizationStableRouteExpandedRequiredFieldNamesW841_count

theorem originalFourTaskContract_targetHomologyZeroDirectSourceStableRoute_bundledInputCount :
    Dbounded.targetHomologyZeroDirectSourceStableRouteInputNamesW842.length =
      1 :=
  Dbounded.targetHomologyZeroDirectSourceStableRouteInputNamesW842_count

theorem originalFourTaskContract_targetHomologyZeroDirectSourceStableRoute_expandedRequiredFieldCount :
    Dbounded.targetHomologyZeroDirectSourceStableRouteExpandedRequiredFieldNamesW842.length =
      2 :=
  Dbounded.targetHomologyZeroDirectSourceStableRouteExpandedRequiredFieldNamesW842_count

theorem originalFourTaskContract_targetExactAtDirectSourceStableRoute_bundledInputCount :
    Dbounded.targetExactAtDirectSourceStableRouteInputNamesW843.length =
      1 :=
  Dbounded.targetExactAtDirectSourceStableRouteInputNamesW843_count

theorem originalFourTaskContract_targetExactAtDirectSourceStableRoute_expandedRequiredFieldCount :
    Dbounded.targetExactAtDirectSourceStableRouteExpandedRequiredFieldNamesW843.length =
      2 :=
  Dbounded.targetExactAtDirectSourceStableRouteExpandedRequiredFieldNamesW843_count

theorem originalFourTaskContract_targetIsoDirectSourceStableRoute_bundledInputCount :
    Dbounded.targetIsoDirectSourceStableRouteInputNamesW844.length =
      1 :=
  Dbounded.targetIsoDirectSourceStableRouteInputNamesW844_count

theorem originalFourTaskContract_targetIsoDirectSourceStableRoute_expandedRequiredFieldCount :
    Dbounded.targetIsoDirectSourceStableRouteExpandedRequiredFieldNamesW844.length =
      2 :=
  Dbounded.targetIsoDirectSourceStableRouteExpandedRequiredFieldNamesW844_count

theorem originalFourTaskContract_isoClosureDirectSourceStableRoute_bundledInputCount :
    Dbounded.isoClosureDirectSourceStableRouteInputNamesW845.length =
      1 :=
  Dbounded.isoClosureDirectSourceStableRouteInputNamesW845_count

theorem originalFourTaskContract_isoClosureDirectSourceStableRoute_expandedRequiredFieldCount :
    Dbounded.isoClosureDirectSourceStableRouteExpandedRequiredFieldNamesW845.length =
      2 :=
  Dbounded.isoClosureDirectSourceStableRouteExpandedRequiredFieldNamesW845_count

theorem originalFourTaskContract_strictRealizationDirectSourceStableRoute_bundledInputCount :
    Dbounded.strictRealizationDirectSourceStableRouteInputNamesW846.length =
      1 :=
  Dbounded.strictRealizationDirectSourceStableRouteInputNamesW846_count

theorem
    originalFourTaskContract_strictRealizationDirectSourceStableRoute_expandedRequiredFieldCount :
    Dbounded.strictRealizationDirectSourceStableRouteExpandedRequiredFieldNamesW846.length =
      2 :=
  Dbounded.strictRealizationDirectSourceStableRouteExpandedRequiredFieldNamesW846_count

theorem originalFourTaskContract_selectedCochainDirectSourceStableRoute_bundledInputCount :
    Dbounded.selectedCochainDirectSourceStableRouteInputNamesW847.length =
      1 :=
  Dbounded.selectedCochainDirectSourceStableRouteInputNamesW847_count

theorem
    originalFourTaskContract_selectedCochainDirectSourceStableRoute_expandedRequiredFieldCount :
    Dbounded.selectedCochainDirectSourceStableRouteExpandedRequiredFieldNamesW847.length =
      2 :=
  Dbounded.selectedCochainDirectSourceStableRouteExpandedRequiredFieldNamesW847_count

theorem originalFourTaskContract_selectedCochainClosed2Route_inputCount :
    Dbounded.selectedCochainClosed2RouteInputNamesW848.length =
      3 :=
  Dbounded.selectedCochainClosed2RouteInputNamesW848_count

theorem originalFourTaskContract_selectedCochainClosed2Route_nonterminal :
    Dbounded.currentMetrizableSelectedCochainClosed2RouteStateW848.productSuccessClaimed =
      false :=
  Dbounded.currentW848SelectedCochainClosed2Route_productSuccess

theorem originalFourTaskContract_selectedCochainExactInputsRoute_inputCount :
    Dbounded.selectedCochainExactInputsRouteInputNamesW849.length =
      2 :=
  Dbounded.selectedCochainExactInputsRouteInputNamesW849_count

theorem originalFourTaskContract_selectedCochainExactInputsRoute_nonterminal :
    Dbounded.currentMetrizableSelectedCochainExactInputsRouteStateW849.productSuccessClaimed =
      false :=
  Dbounded.currentW849SelectedCochainExactInputsRoute_productSuccess

theorem originalFourTaskContract_exactInputsSelectedCochainDirectSourceRoute_inputCount :
    Dbounded.exactInputsSelectedCochainDirectSourceStableRouteInputNamesW850.length =
      2 :=
  Dbounded.exactInputsSelectedCochainDirectSourceStableRouteInputNamesW850_count

theorem originalFourTaskContract_exactInputsSelectedCochainDirectSourceRoute_nonterminal :
    Dbounded.currentMetrizableExactInputsSelectedCochainDirectSourceStableRouteStateW850.productSuccessClaimed =
      false :=
  Dbounded.currentW850ExactInputsSelectedCochainDirectSourceStableRoute_productSuccess

theorem originalFourTaskContract_comparisonSelectedCochainStableRoute_inputCount :
    Dbounded.comparisonSelectedCochainStableRouteInputNamesW851.length =
      1 :=
  Dbounded.comparisonSelectedCochainStableRouteInputNamesW851_count

theorem originalFourTaskContract_comparisonSelectedCochainStableRoute_nonterminal :
    Dbounded.currentMetrizableComparisonSelectedCochainStableRouteStateW851.productSuccessClaimed =
      false :=
  Dbounded.currentW851ComparisonSelectedCochainStableRoute_productSuccess

theorem originalFourTaskContract_routeDataSelectedCochainStableRoute_inputCount :
    Dbounded.routeDataSelectedCochainStableRouteInputNamesW852.length =
      1 :=
  Dbounded.routeDataSelectedCochainStableRouteInputNamesW852_count

theorem originalFourTaskContract_routeDataSelectedCochainStableRoute_nonterminal :
    Dbounded.currentMetrizableRouteDataSelectedCochainStableRouteStateW852.productSuccessClaimed =
      false :=
  Dbounded.currentW852RouteDataSelectedCochainStableRoute_productSuccess

theorem originalFourTaskContract_homologyFreeSelectedCochainStableRoute_inputCount :
    Dbounded.homologyFreeSelectedCochainStableRouteInputNamesW853.length =
      1 :=
  Dbounded.homologyFreeSelectedCochainStableRouteInputNamesW853_count

theorem originalFourTaskContract_homologyFreeSelectedCochainStableRoute_nonterminal :
    Dbounded.currentMetrizableHomologyFreeSelectedCochainStableRouteStateW853.productSuccessClaimed =
      false :=
  Dbounded.currentW853HomologyFreeSelectedCochainStableRoute_productSuccess

theorem originalFourTaskContract_homologyFreeProviderFromRouteData_inputCount :
    Dbounded.homologyFreeProviderFromRouteDataInputNamesW854.length =
      1 :=
  Dbounded.homologyFreeProviderFromRouteDataInputNamesW854_count

theorem originalFourTaskContract_homologyFreeProviderFromRouteData_nonterminal :
    Dbounded.currentMetrizableHomologyFreeProviderFromRouteDataStateW854.productSuccessClaimed =
      false :=
  Dbounded.currentW854HomologyFreeProviderFromRouteData_productSuccess

theorem originalFourTaskContract_comparisonBijectivityRouteData_inputCount :
    Dbounded.comparisonBijectivityRouteDataBranchInputNamesW855.length = 9 :=
  Dbounded.comparisonBijectivityRouteDataBranchInputNamesW855_count

theorem originalFourTaskContract_comparisonBijectivityRouteData_nonterminal :
    Dbounded.currentMetrizableComparisonBijectivityRouteDataProviderStateW855.productSuccessClaimed =
      false :=
  Dbounded.currentW855ComparisonBijectivityRouteDataProvider_productSuccess

theorem originalFourTaskContract_endpointTopologyFacts_remainingFactCount :
    Dbounded.endpointTopologyFactInputNamesW856.length = 3 :=
  Dbounded.endpointTopologyFactInputNamesW856_count

theorem originalFourTaskContract_endpointFactsHomologyFreeRouteData_inputCount :
    Dbounded.endpointFactsHomologyFreeRouteDataInputNamesW856.length = 8 :=
  Dbounded.endpointFactsHomologyFreeRouteDataInputNamesW856_count

theorem originalFourTaskContract_endpointFactsHomologyFreeRouteData_nonterminal :
    Dbounded.currentMetrizableEndpointFactsHomologyFreeRouteDataStateW856.productSuccessClaimed =
      false :=
  Dbounded.currentW856EndpointFactsHomologyFreeRouteData_productSuccess

theorem originalFourTaskContract_endpointKernelCokernelFacts_remainingFactCount :
    Dbounded.endpointKernelCokernelFactInputNamesW857.length = 2 :=
  Dbounded.endpointKernelCokernelFactInputNamesW857_count

theorem originalFourTaskContract_endpointKernelCokernelLeftCalculus_inputCount :
    Dbounded.endpointKernelCokernelLeftCalculusInputNamesW857.length = 4 :=
  Dbounded.endpointKernelCokernelLeftCalculusInputNamesW857_count

theorem originalFourTaskContract_endpointKernelCokernelStableRoute_expandedInputCount :
    Dbounded.endpointKernelCokernelStableRouteExpandedInputNamesW857.length = 8 :=
  Dbounded.endpointKernelCokernelStableRouteExpandedInputNamesW857_count

theorem originalFourTaskContract_endpointKernelCokernelFromClosednessBranch_nonterminal :
    Dbounded.currentMetrizableEndpointKernelCokernelFromClosednessBranchStateW857.productSuccessClaimed =
      false :=
  Dbounded.currentW857EndpointKernelCokernelFromClosednessBranch_productSuccess

theorem originalFourTaskContract_endpointKernelCokernelLocalizedLeftCalculus_inputCount :
    Dbounded.endpointKernelCokernelLocalizedLeftCalculusInputNamesW858.length = 4 :=
  Dbounded.endpointKernelCokernelLocalizedLeftCalculusInputNamesW858_count

theorem originalFourTaskContract_endpointKernelCokernelLocalizedStableRoute_expandedInputCount :
    Dbounded.endpointKernelCokernelLocalizedStableRouteExpandedInputNamesW858.length =
      8 :=
  Dbounded.endpointKernelCokernelLocalizedStableRouteExpandedInputNamesW858_count

theorem originalFourTaskContract_endpointKernelCokernelLocalizedRoute_nonterminal :
    Dbounded.currentMetrizableEndpointKernelCokernelLocalizedRouteStateW858.productSuccessClaimed =
      false :=
  Dbounded.currentW858EndpointKernelCokernelLocalizedRoute_productSuccess

theorem originalFourTaskContract_endpointExactAtTopologyFacts_remainingFactCount :
    Dbounded.endpointExactAtTopologyFactInputNamesW859.length = 3 :=
  Dbounded.endpointExactAtTopologyFactInputNamesW859_count

theorem originalFourTaskContract_closednessBranchTargetExactAtLeftCalculus_inputCount :
    Dbounded.closednessBranchTargetExactAtLeftCalculusInputNamesW859.length =
      4 :=
  Dbounded.closednessBranchTargetExactAtLeftCalculusInputNamesW859_count

theorem originalFourTaskContract_closednessBranchTargetExactAtStableRoute_expandedInputCount :
    Dbounded.closednessBranchTargetExactAtStableRouteExpandedInputNamesW859.length =
      8 :=
  Dbounded.closednessBranchTargetExactAtStableRouteExpandedInputNamesW859_count

theorem originalFourTaskContract_closednessBranchTargetExactAtRoute_nonterminal :
    Dbounded.currentMetrizableClosednessBranchTargetExactAtRouteStateW859.productSuccessClaimed =
      false :=
  Dbounded.currentW859ClosednessBranchTargetExactAtRoute_productSuccess

theorem originalFourTaskContract_endpointLocalizedTargetExactAtLeftCalculus_inputCount :
    Dbounded.endpointLocalizedClosednessBranchTargetExactAtLeftCalculusInputNamesW860.length =
      3 :=
  Dbounded.endpointLocalizedClosednessBranchTargetExactAtLeftCalculusInputNamesW860_count

theorem originalFourTaskContract_endpointLocalizedTargetExactAtStableRoute_expandedInputCount :
    Dbounded.endpointLocalizedClosednessBranchTargetExactAtStableRouteExpandedInputNamesW860.length =
      7 :=
  Dbounded.endpointLocalizedClosednessBranchTargetExactAtStableRouteExpandedInputNamesW860_count

theorem originalFourTaskContract_endpointLocalizedTargetExactAtRoute_nonterminal :
    Dbounded.currentMetrizableEndpointLocalizedClosednessBranchTargetExactAtRouteStateW860.productSuccessClaimed =
      false :=
  Dbounded.currentW860EndpointLocalizedClosednessBranchTargetExactAtRoute_productSuccess

theorem originalFourTaskContract_concreteLeavesTargetExactAtLeftCalculus_inputCount :
    Dbounded.concreteLeavesTargetExactAtLeftCalculusInputNamesW861.length =
      2 :=
  Dbounded.concreteLeavesTargetExactAtLeftCalculusInputNamesW861_count

theorem originalFourTaskContract_concreteLeavesTargetExactAtStableRoute_expandedInputCount :
    Dbounded.concreteLeavesTargetExactAtStableRouteExpandedInputNamesW861.length =
      6 :=
  Dbounded.concreteLeavesTargetExactAtStableRouteExpandedInputNamesW861_count

theorem originalFourTaskContract_concreteLeavesTargetExactAtRoute_nonterminal :
    Dbounded.currentMetrizableConcreteLeavesTargetExactAtRouteStateW861.productSuccessClaimed =
      false :=
  Dbounded.currentW861ConcreteLeavesTargetExactAtRoute_productSuccess

theorem originalFourTaskContract_targetHomologyZeroConcreteLeavesTargetExactAt_inputCount :
    Dbounded.targetHomologyZeroConcreteLeavesTargetExactAtInputNamesW862.length =
      1 :=
  Dbounded.targetHomologyZeroConcreteLeavesTargetExactAtInputNamesW862_count

theorem originalFourTaskContract_targetHomologyZeroConcreteLeavesTargetExactAt_stableInputCount :
    Dbounded.targetHomologyZeroConcreteLeavesTargetExactAtStableRouteInputNamesW862.length =
      5 :=
  Dbounded.targetHomologyZeroConcreteLeavesTargetExactAtStableRouteInputNamesW862_count

theorem originalFourTaskContract_targetHomologyZeroConcreteLeavesTargetExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableTargetHomologyZeroConcreteLeavesTargetExactAtRouteStateW862;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW862TargetHomologyZeroConcreteLeavesTargetExactAtRoute_productSuccess

theorem originalFourTaskContract_targetHomologyZeroStableExactAt_inputCount :
    Dbounded.targetHomologyZeroStableExactAtInputNamesW863.length = 1 :=
  Dbounded.targetHomologyZeroStableExactAtInputNamesW863_count

theorem originalFourTaskContract_targetHomologyZeroStableExactAt_expandedInputCount :
    Dbounded.targetHomologyZeroStableExactAtExpandedInputNamesW863.length =
      2 :=
  Dbounded.targetHomologyZeroStableExactAtExpandedInputNamesW863_count

theorem originalFourTaskContract_targetHomologyZeroStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableTargetHomologyZeroStableExactAtRouteStateW863;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW863TargetHomologyZeroStableExactAtRoute_productSuccess

theorem originalFourTaskContract_targetExactAtDirectSourceStableExactAt_inputCount :
    Dbounded.targetExactAtDirectSourceStableExactAtInputNamesW864.length =
      1 :=
  Dbounded.targetExactAtDirectSourceStableExactAtInputNamesW864_count

theorem originalFourTaskContract_targetExactAtDirectSourceStableExactAt_expandedInputCount :
    Dbounded.targetExactAtDirectSourceStableExactAtExpandedInputNamesW864.length =
      2 :=
  Dbounded.targetExactAtDirectSourceStableExactAtExpandedInputNamesW864_count

theorem originalFourTaskContract_targetExactAtDirectSourceStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableTargetExactAtDirectSourceStableExactAtRouteStateW864;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW864TargetExactAtDirectSourceStableExactAtRoute_productSuccess

theorem originalFourTaskContract_targetIsoDirectSourceStableExactAt_inputCount :
    Dbounded.targetIsoDirectSourceStableExactAtInputNamesW865.length =
      1 :=
  Dbounded.targetIsoDirectSourceStableExactAtInputNamesW865_count

theorem originalFourTaskContract_targetIsoDirectSourceStableExactAt_expandedInputCount :
    Dbounded.targetIsoDirectSourceStableExactAtExpandedInputNamesW865.length =
      2 :=
  Dbounded.targetIsoDirectSourceStableExactAtExpandedInputNamesW865_count

theorem originalFourTaskContract_targetIsoDirectSourceStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableTargetIsoDirectSourceStableExactAtRouteStateW865;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW865TargetIsoDirectSourceStableExactAtRoute_productSuccess

theorem originalFourTaskContract_isoClosureDirectSourceStableExactAt_inputCount :
    Dbounded.isoClosureDirectSourceStableExactAtInputNamesW866.length =
      1 :=
  Dbounded.isoClosureDirectSourceStableExactAtInputNamesW866_count

theorem originalFourTaskContract_isoClosureDirectSourceStableExactAt_expandedInputCount :
    Dbounded.isoClosureDirectSourceStableExactAtExpandedInputNamesW866.length =
      2 :=
  Dbounded.isoClosureDirectSourceStableExactAtExpandedInputNamesW866_count

theorem originalFourTaskContract_isoClosureDirectSourceStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableIsoClosureDirectSourceStableExactAtRouteStateW866;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW866IsoClosureDirectSourceStableExactAtRoute_productSuccess

theorem originalFourTaskContract_strictRealizationDirectSourceStableExactAt_inputCount :
    Dbounded.strictRealizationDirectSourceStableExactAtInputNamesW867.length =
      1 :=
  Dbounded.strictRealizationDirectSourceStableExactAtInputNamesW867_count

theorem originalFourTaskContract_strictRealizationDirectSourceStableExactAt_expandedInputCount :
    Dbounded.strictRealizationDirectSourceStableExactAtExpandedInputNamesW867.length =
      2 :=
  Dbounded.strictRealizationDirectSourceStableExactAtExpandedInputNamesW867_count

theorem originalFourTaskContract_strictRealizationDirectSourceStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableStrictRealizationDirectSourceStableExactAtRouteStateW867;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW867StrictRealizationDirectSourceStableExactAtRoute_productSuccess

theorem originalFourTaskContract_selectedCochainDirectSourceStableExactAt_inputCount :
    Dbounded.selectedCochainDirectSourceStableExactAtInputNamesW868.length =
      1 :=
  Dbounded.selectedCochainDirectSourceStableExactAtInputNamesW868_count

theorem originalFourTaskContract_selectedCochainDirectSourceStableExactAt_expandedInputCount :
    Dbounded.selectedCochainDirectSourceStableExactAtExpandedInputNamesW868.length =
      2 :=
  Dbounded.selectedCochainDirectSourceStableExactAtExpandedInputNamesW868_count

theorem originalFourTaskContract_selectedCochainDirectSourceStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableSelectedCochainDirectSourceStableExactAtRouteStateW868;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW868SelectedCochainDirectSourceStableExactAtRoute_productSuccess

theorem originalFourTaskContract_exactInputsSelectedCochainStableExactAt_inputCount :
    Dbounded.exactInputsSelectedCochainStableExactAtInputNamesW869.length =
      2 :=
  Dbounded.exactInputsSelectedCochainStableExactAtInputNamesW869_count

theorem originalFourTaskContract_exactInputsSelectedCochainStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableExactInputsSelectedCochainStableExactAtRouteStateW869;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW869ExactInputsSelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_comparisonSelectedCochainStableExactAt_inputCount :
    Dbounded.comparisonSelectedCochainStableExactAtInputNamesW870.length =
      1 :=
  Dbounded.comparisonSelectedCochainStableExactAtInputNamesW870_count

theorem originalFourTaskContract_comparisonSelectedCochainStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableComparisonSelectedCochainStableExactAtRouteStateW870;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW870ComparisonSelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_routeDataSelectedCochainStableExactAt_inputCount :
    Dbounded.routeDataSelectedCochainStableExactAtInputNamesW871.length =
      1 :=
  Dbounded.routeDataSelectedCochainStableExactAtInputNamesW871_count

theorem originalFourTaskContract_routeDataSelectedCochainStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableRouteDataSelectedCochainStableExactAtRouteStateW871;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW871RouteDataSelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_homologyFreeSelectedCochainStableExactAt_inputCount :
    Dbounded.homologyFreeSelectedCochainStableExactAtInputNamesW872.length =
      1 :=
  Dbounded.homologyFreeSelectedCochainStableExactAtInputNamesW872_count

theorem originalFourTaskContract_homologyFreeSelectedCochainStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableHomologyFreeSelectedCochainStableExactAtRouteStateW872;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW872HomologyFreeSelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_endpointFactsHomologyFreeSelectedCochainStableExactAt_inputCount :
    Dbounded.endpointFactsHomologyFreeSelectedCochainStableExactAtInputNamesW873.length =
      8 :=
  Dbounded.endpointFactsHomologyFreeSelectedCochainStableExactAtInputNamesW873_count

theorem originalFourTaskContract_endpointFactsHomologyFreeSelectedCochainStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableEndpointFactsHomologyFreeSelectedCochainStableExactAtRouteStateW873;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW873EndpointFactsHomologyFreeSelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_endpointLocalizedHomologyFreeSelectedCochainStableExactAt_inputCount :
    Dbounded.endpointLocalizedHomologyFreeSelectedCochainStableExactAtInputNamesW874.length =
      7 :=
  Dbounded.endpointLocalizedHomologyFreeSelectedCochainStableExactAtInputNamesW874_count

theorem originalFourTaskContract_endpointLocalizedHomologyFreeSelectedCochainStableExactAt_nonterminal :
    (let state :=
        Dbounded.currentMetrizableEndpointLocalizedHomologyFreeSelectedCochainStableExactAtRouteStateW874;
      state.productSuccessClaimed) =
      false :=
  Dbounded.currentW874EndpointLocalizedHomologyFreeSelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_w732SelectedCochainStableExactAt_inputCount :
    Dbounded.w732SelectedCochainStableExactAtInputNamesW875.length = 1 :=
  Dbounded.w732SelectedCochainStableExactAtInputNamesW875_count

theorem originalFourTaskContract_w732SelectedCochainStableExactAt_nonterminal :
    Dbounded.currentMetrizableW732SelectedCochainStableExactAtRouteStateW875.productSuccessClaimed =
      false :=
  Dbounded.currentW875W732SelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_w735W732SelectedCochainStableExactAt_inputCount :
    Dbounded.w735W732SelectedCochainStableExactAtInputNamesW876.length = 9 :=
  Dbounded.w735W732SelectedCochainStableExactAtInputNamesW876_count

theorem originalFourTaskContract_w735W732SelectedCochainStableExactAt_nonterminal :
    Dbounded.currentMetrizableW735W732SelectedCochainStableExactAtRouteStateW876.productSuccessClaimed =
      false :=
  Dbounded.currentW876W735W732SelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_concreteLeavesSelectedCochainStableExactAt_inputCount :
    Dbounded.concreteLeavesSelectedCochainStableExactAtInputNamesW877.length =
      8 :=
  Dbounded.concreteLeavesSelectedCochainStableExactAtInputNamesW877_count

theorem originalFourTaskContract_concreteLeavesSelectedCochainStableExactAt_nonterminal :
    Dbounded.currentMetrizableConcreteLeavesSelectedCochainStableExactAtRouteStateW877.productSuccessClaimed =
      false :=
  Dbounded.currentW877ConcreteLeavesSelectedCochainStableExactAtRoute_productSuccess

theorem originalFourTaskContract_selectedCochainConcreteLeavesStableExactAt_inputCount :
    Dbounded.selectedCochainConcreteLeavesStableExactAtInputNamesW878.length =
      1 :=
  Dbounded.selectedCochainConcreteLeavesStableExactAtInputNamesW878_count

theorem
    originalFourTaskContract_selectedCochainConcreteLeavesStableExactAt_expandedInputCount :
    Dbounded.selectedCochainConcreteLeavesStableExactAtExpandedInputNamesW878.length =
      2 :=
  Dbounded.selectedCochainConcreteLeavesStableExactAtExpandedInputNamesW878_count

theorem originalFourTaskContract_selectedCochainConcreteLeavesStableExactAt_nonterminal :
    Dbounded.currentMetrizableSelectedCochainConcreteLeavesStableExactAtRouteStateW878.productSuccessClaimed =
      false :=
  Dbounded.currentW878SelectedCochainConcreteLeavesStableExactAtRoute_productSuccess

theorem originalFourTaskContract_comparisonConcreteLeavesStableExactAt_inputCount :
    Dbounded.comparisonConcreteLeavesStableExactAtInputNamesW879.length =
      1 :=
  Dbounded.comparisonConcreteLeavesStableExactAtInputNamesW879_count

theorem originalFourTaskContract_comparisonConcreteLeavesStableExactAt_expandedInputCount :
    Dbounded.comparisonConcreteLeavesStableExactAtExpandedInputNamesW879.length =
      9 :=
  Dbounded.comparisonConcreteLeavesStableExactAtExpandedInputNamesW879_count

theorem originalFourTaskContract_comparisonConcreteLeavesStableExactAt_nonterminal :
    Dbounded.currentMetrizableComparisonConcreteLeavesStableExactAtRouteStateW879.productSuccessClaimed =
      false :=
  Dbounded.currentW879ComparisonConcreteLeavesStableExactAtRoute_productSuccess

theorem originalFourTaskContract_homologyFreeComparisonConcreteLeavesStableExactAt_inputCount :
    Dbounded.homologyFreeComparisonConcreteLeavesStableExactAtInputNamesW880.length =
      1 :=
  Dbounded.homologyFreeComparisonConcreteLeavesStableExactAtInputNamesW880_count

theorem originalFourTaskContract_homologyFreeComparisonConcreteLeavesStableExactAt_expandedInputCount :
    Dbounded.homologyFreeComparisonConcreteLeavesStableExactAtExpandedInputNamesW880.length =
      8 :=
  Dbounded.homologyFreeComparisonConcreteLeavesStableExactAtExpandedInputNamesW880_count

theorem originalFourTaskContract_homologyFreeComparisonConcreteLeavesStableExactAt_nonterminal :
    Dbounded.currentMetrizableHomologyFreeComparisonConcreteLeavesStableExactAtRouteStateW880.productSuccessClaimed =
      false :=
  Dbounded.currentW880HomologyFreeComparisonConcreteLeavesStableExactAtRoute_productSuccess

theorem originalFourTaskContract_endpointLocalizedComparisonConcreteLeavesStableExactAt_inputCount :
    Dbounded.endpointLocalizedComparisonConcreteLeavesStableExactAtInputNamesW881.length =
      1 :=
  Dbounded.endpointLocalizedComparisonConcreteLeavesStableExactAtInputNamesW881_count

theorem originalFourTaskContract_endpointLocalizedComparisonConcreteLeavesStableExactAt_expandedInputCount :
    Dbounded.endpointLocalizedComparisonConcreteLeavesStableExactAtExpandedInputNamesW881.length =
      7 :=
  Dbounded.endpointLocalizedComparisonConcreteLeavesStableExactAtExpandedInputNamesW881_count

theorem originalFourTaskContract_endpointLocalizedComparisonConcreteLeavesStableExactAt_nonterminal :
    Dbounded.currentMetrizableEndpointLocalizedComparisonConcreteLeavesStableExactAtRouteStateW881.productSuccessClaimed =
      false :=
  Dbounded.currentW881EndpointLocalizedComparisonConcreteLeavesStableExactAtRoute_productSuccess

theorem originalFourTaskContract_w732ComparisonConcreteLeavesStableExactAt_inputCount :
    Dbounded.w732ComparisonConcreteLeavesStableExactAtInputNamesW882.length =
      1 :=
  Dbounded.w732ComparisonConcreteLeavesStableExactAtInputNamesW882_count

theorem originalFourTaskContract_w732ComparisonConcreteLeavesStableExactAt_expandedInputCount :
    Dbounded.w732ComparisonConcreteLeavesStableExactAtExpandedInputNamesW882.length =
      1 :=
  Dbounded.w732ComparisonConcreteLeavesStableExactAtExpandedInputNamesW882_count

theorem originalFourTaskContract_w732ComparisonConcreteLeavesStableExactAt_nonterminal :
    Dbounded.currentMetrizableW732ComparisonConcreteLeavesStableExactAtRouteStateW882.productSuccessClaimed =
      false :=
  Dbounded.currentW882W732ComparisonConcreteLeavesStableExactAtRoute_productSuccess

theorem originalFourTaskContract_concreteLeavesComparisonStableExactAt_inputCount :
    Dbounded.concreteLeavesComparisonStableExactAtInputNamesW883.length =
      8 :=
  Dbounded.concreteLeavesComparisonStableExactAtInputNamesW883_count

theorem originalFourTaskContract_concreteLeavesComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableConcreteLeavesComparisonStableExactAtRouteStateW883.productSuccessClaimed =
      false :=
  Dbounded.currentW883ConcreteLeavesComparisonStableExactAtRoute_productSuccess

#check Dbounded.concreteLeavesOfSourceTriangulationComparisonW884
#check
  Dbounded.directBoundedLeftCalculusOfSourceTriangulationComparisonStableExactAtW884
#check
  Dbounded.boundedDerivedInfinityCategoryOfSourceTriangulationComparisonStableExactAtW884

theorem originalFourTaskContract_sourceTriangulationComparisonStableExactAt_inputCount :
    Dbounded.sourceTriangulationComparisonStableExactAtInputNamesW884.length =
      8 :=
  Dbounded.sourceTriangulationComparisonStableExactAtInputNamesW884_count

theorem originalFourTaskContract_sourceTriangulationComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableSourceTriangulationComparisonStableExactAtRouteStateW884.productSuccessClaimed =
      false :=
  Dbounded.currentW884SourceTriangulationComparisonStableExactAtRoute_productSuccess

#check Dbounded.sourceTriangulationLeavesOfFieldsW885
#check
  Dbounded.directBoundedLeftCalculusOfSourceTriangulationFieldsComparisonStableExactAtW885
#check
  Dbounded.boundedDerivedInfinityCategoryOfSourceTriangulationFieldsComparisonStableExactAtW885

theorem originalFourTaskContract_sourceTriangulationFieldsComparisonStableExactAt_inputCount :
    Dbounded.sourceTriangulationFieldsComparisonStableExactAtInputNamesW885.length =
      10 :=
  Dbounded.sourceTriangulationFieldsComparisonStableExactAtInputNamesW885_count

theorem originalFourTaskContract_sourceTriangulationFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableSourceTriangulationFieldsComparisonStableExactAtRouteStateW885.productSuccessClaimed =
      false :=
  Dbounded.currentW885SourceTriangulationFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.sourceTriangulationFieldLeavesOfEndpointFieldsW886
#check
  Dbounded.directBoundedLeftCalculusOfEndpointFieldsComparisonStableExactAtW886
#check
  Dbounded.boundedDerivedInfinityCategoryOfEndpointFieldsComparisonStableExactAtW886

theorem originalFourTaskContract_endpointFieldsComparisonStableExactAt_inputCount :
    Dbounded.endpointFieldsComparisonStableExactAtInputNamesW886.length =
      13 :=
  Dbounded.endpointFieldsComparisonStableExactAtInputNamesW886_count

theorem originalFourTaskContract_endpointFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableEndpointFieldsComparisonStableExactAtRouteStateW886.productSuccessClaimed =
      false :=
  Dbounded.currentW886EndpointFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.endpointStrictTopologyFieldLeavesOfLocalizedRightAdjointFieldsW887
#check
  Dbounded.directBoundedLeftCalculusOfLocalizedRightAdjointFieldsComparisonStableExactAtW887
#check
  Dbounded.boundedDerivedInfinityCategoryOfLocalizedRightAdjointFieldsComparisonStableExactAtW887

theorem originalFourTaskContract_localizedRightAdjointFieldsComparisonStableExactAt_inputCount :
    Dbounded.localizedRightAdjointFieldsComparisonStableExactAtInputNamesW887.length =
      15 :=
  Dbounded.localizedRightAdjointFieldsComparisonStableExactAtInputNamesW887_count

theorem originalFourTaskContract_localizedRightAdjointFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableLocalizedRightAdjointFieldsComparisonStableExactAtRouteStateW887.productSuccessClaimed =
      false :=
  Dbounded.currentW887LocalizedRightAdjointFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.localizedRightAdjointFieldLeavesOfNormalizedFixedTargetFieldsW888
#check
  Dbounded.directBoundedLeftCalculusOfNormalizedFixedTargetFieldsComparisonStableExactAtW888
#check
  Dbounded.boundedDerivedInfinityCategoryOfNormalizedFixedTargetFieldsComparisonStableExactAtW888

theorem originalFourTaskContract_normalizedFixedTargetFieldsComparisonStableExactAt_inputCount :
    Dbounded.normalizedFixedTargetFieldsComparisonStableExactAtInputNamesW888.length =
      17 :=
  Dbounded.normalizedFixedTargetFieldsComparisonStableExactAtInputNamesW888_count

theorem originalFourTaskContract_normalizedFixedTargetFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableNormalizedFixedTargetFieldsComparisonStableExactAtRouteStateW888.productSuccessClaimed =
      false :=
  Dbounded.currentW888NormalizedFixedTargetFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.normalizedFixedTargetFieldLeavesOfNormalizedLiftBlueprintFieldsW889
#check
  Dbounded.directBoundedLeftCalculusOfNormalizedLiftBlueprintFieldsComparisonStableExactAtW889
#check
  Dbounded.boundedDerivedInfinityCategoryOfNormalizedLiftBlueprintFieldsComparisonStableExactAtW889

theorem originalFourTaskContract_normalizedLiftBlueprintFieldsComparisonStableExactAt_inputCount :
    Dbounded.normalizedLiftBlueprintFieldsComparisonStableExactAtInputNamesW889.length =
      19 :=
  Dbounded.normalizedLiftBlueprintFieldsComparisonStableExactAtInputNamesW889_count

theorem originalFourTaskContract_normalizedLiftBlueprintFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableNormalizedLiftBlueprintFieldsComparisonStableExactAtRouteStateW889.productSuccessClaimed =
      false :=
  Dbounded.currentW889NormalizedLiftBlueprintFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.normalizedLiftBlueprintFieldLeavesOfStrictRepresentativeFieldsW890
#check
  Dbounded.directBoundedLeftCalculusOfStrictRepresentativeFieldsComparisonStableExactAtW890
#check
  Dbounded.boundedDerivedInfinityCategoryOfStrictRepresentativeFieldsComparisonStableExactAtW890

theorem originalFourTaskContract_strictRepresentativeFieldsComparisonStableExactAt_inputCount :
    Dbounded.strictRepresentativeFieldsComparisonStableExactAtInputNamesW890.length =
      22 :=
  Dbounded.strictRepresentativeFieldsComparisonStableExactAtInputNamesW890_count

theorem originalFourTaskContract_strictRepresentativeFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableStrictRepresentativeFieldsComparisonStableExactAtRouteStateW890.productSuccessClaimed =
      false :=
  Dbounded.currentW890StrictRepresentativeFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.strictRepresentativeFieldLeavesOfObjectFieldsW891
#check
  Dbounded.directBoundedLeftCalculusOfStrictPreimageObjectFieldsComparisonStableExactAtW891
#check
  Dbounded.boundedDerivedInfinityCategoryOfStrictPreimageObjectFieldsComparisonStableExactAtW891

theorem originalFourTaskContract_strictPreimageObjectFieldsComparisonStableExactAt_inputCount :
    Dbounded.strictPreimageObjectFieldsComparisonStableExactAtInputNamesW891.length =
      29 :=
  Dbounded.strictPreimageObjectFieldsComparisonStableExactAtInputNamesW891_count

theorem originalFourTaskContract_strictPreimageObjectFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableStrictPreimageObjectFieldsComparisonStableExactAtRouteStateW891.productSuccessClaimed =
      false :=
  Dbounded.currentW891StrictPreimageObjectFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.strictRepresentativeObjectFieldLeavesOfMapFieldsW892
#check
  Dbounded.directBoundedLeftCalculusOfStrictPreimageMapFieldsComparisonStableExactAtW892
#check
  Dbounded.boundedDerivedInfinityCategoryOfStrictPreimageMapFieldsComparisonStableExactAtW892

theorem originalFourTaskContract_strictPreimageMapFieldsComparisonStableExactAt_inputCount :
    Dbounded.strictPreimageMapFieldsComparisonStableExactAtInputNamesW892.length =
      34 :=
  Dbounded.strictPreimageMapFieldsComparisonStableExactAtInputNamesW892_count

theorem originalFourTaskContract_strictPreimageMapFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableStrictPreimageMapFieldsComparisonStableExactAtRouteStateW892.productSuccessClaimed =
      false :=
  Dbounded.currentW892StrictPreimageMapFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.strictPreimageMapFieldLeavesOfBoundaryFieldsW893
#check
  Dbounded.directBoundedLeftCalculusOfBoundaryFieldsComparisonStableExactAtW893
#check
  Dbounded.boundedDerivedInfinityCategoryOfBoundaryFieldsComparisonStableExactAtW893

theorem originalFourTaskContract_boundaryFieldsComparisonStableExactAt_inputCount :
    Dbounded.boundaryFieldsComparisonStableExactAtInputNamesW893.length =
      35 :=
  Dbounded.boundaryFieldsComparisonStableExactAtInputNamesW893_count

theorem originalFourTaskContract_boundaryFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableBoundaryFieldsComparisonStableExactAtRouteStateW893.productSuccessClaimed =
      false :=
  Dbounded.currentW893BoundaryFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.boundaryFieldLeavesOfRelationFieldsW894
#check
  Dbounded.directBoundedLeftCalculusOfRelationFieldsComparisonStableExactAtW894
#check
  Dbounded.boundedDerivedInfinityCategoryOfRelationFieldsComparisonStableExactAtW894

theorem originalFourTaskContract_relationFieldsComparisonStableExactAt_inputCount :
    Dbounded.relationFieldsComparisonStableExactAtInputNamesW894.length =
      36 :=
  Dbounded.relationFieldsComparisonStableExactAtInputNamesW894_count

theorem originalFourTaskContract_relationFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableRelationFieldsComparisonStableExactAtRouteStateW894.productSuccessClaimed =
      false :=
  Dbounded.currentW894RelationFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.relationFieldLeavesOfTargetSurjectiveCompactFieldsW895
#check
  Dbounded.directBoundedLeftCalculusOfTargetSurjectiveCompactFieldsComparisonStableExactAtW895
#check
  Dbounded.boundedDerivedInfinityCategoryOfTargetSurjectiveCompactFieldsComparisonStableExactAtW895

theorem originalFourTaskContract_targetSurjectiveCompactFieldsComparisonStableExactAt_inputCount :
    Dbounded.targetSurjectiveCompactFieldsComparisonStableExactAtInputNamesW895.length =
      37 :=
  Dbounded.targetSurjectiveCompactFieldsComparisonStableExactAtInputNamesW895_count

theorem originalFourTaskContract_targetSurjectiveCompactFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableTargetSurjectiveCompactFieldsComparisonStableExactAtRouteStateW895.productSuccessClaimed =
      false :=
  Dbounded.currentW895TargetSurjectiveCompactFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.targetSurjectiveCompactFieldLeavesOfClosedMapClosednessFieldsW896
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapClosednessFieldsComparisonStableExactAtW896
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapClosednessFieldsComparisonStableExactAtW896

theorem originalFourTaskContract_closedMapClosednessFieldsComparisonStableExactAt_inputCount :
    Dbounded.closedMapClosednessFieldsComparisonStableExactAtInputNamesW896.length =
      38 :=
  Dbounded.closedMapClosednessFieldsComparisonStableExactAtInputNamesW896_count

theorem originalFourTaskContract_closedMapClosednessFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableClosedMapClosednessFieldsComparisonStableExactAtRouteStateW896.productSuccessClaimed =
      false :=
  Dbounded.currentW896ClosedMapClosednessFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.targetSurjectiveCompactFieldLeavesOfClosedEmbeddingClosednessFieldsW897
#check
  Dbounded.directBoundedLeftCalculusOfClosedEmbeddingClosednessFieldsComparisonStableExactAtW897
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingClosednessFieldsComparisonStableExactAtW897

theorem originalFourTaskContract_closedEmbeddingClosednessFieldsComparisonStableExactAt_inputCount :
    Dbounded.closedEmbeddingClosednessFieldsComparisonStableExactAtInputNamesW897.length =
      38 :=
  Dbounded.closedEmbeddingClosednessFieldsComparisonStableExactAtInputNamesW897_count

theorem originalFourTaskContract_closedEmbeddingClosednessFieldsComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableClosedEmbeddingClosednessFieldsComparisonStableExactAtRouteStateW897.productSuccessClaimed =
      false :=
  Dbounded.currentW897ClosedEmbeddingClosednessFieldsComparisonStableExactAtRoute_productSuccess

#check Dbounded.closedEmbeddingClosednessFieldLeavesOfEndpointHomologyFreeW898
#check
  Dbounded.directBoundedLeftCalculusOfClosedEmbeddingEndpointHomologyFreeComparisonStableExactAtW898
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedEmbeddingEndpointHomologyFreeComparisonStableExactAtW898

theorem originalFourTaskContract_closedEmbeddingEndpointHomologyFreeComparisonStableExactAt_inputCount :
    Dbounded.closedEmbeddingEndpointHomologyFreeComparisonStableExactAtInputNamesW898.length =
      37 :=
  Dbounded.closedEmbeddingEndpointHomologyFreeComparisonStableExactAtInputNamesW898_count

theorem originalFourTaskContract_closedEmbeddingEndpointHomologyFreeComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableClosedEmbeddingEndpointHomologyFreeComparisonStableExactAtRouteStateW898.productSuccessClaimed =
      false :=
  Dbounded.currentW898ClosedEmbeddingEndpointHomologyFreeComparisonStableExactAtRoute_productSuccess

#check Dbounded.closedMapClosednessFieldLeavesOfEndpointHomologyFreeW899
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapEndpointHomologyFreeComparisonStableExactAtW899
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapEndpointHomologyFreeComparisonStableExactAtW899

theorem originalFourTaskContract_closedMapEndpointHomologyFreeComparisonStableExactAt_inputCount :
    Dbounded.closedMapEndpointHomologyFreeComparisonStableExactAtInputNamesW899.length =
      37 :=
  Dbounded.closedMapEndpointHomologyFreeComparisonStableExactAtInputNamesW899_count

theorem originalFourTaskContract_closedMapEndpointHomologyFreeComparisonStableExactAt_nonterminal :
    Dbounded.currentMetrizableClosedMapEndpointHomologyFreeComparisonStableExactAtRouteStateW899.productSuccessClaimed =
      false :=
  Dbounded.currentW899ClosedMapEndpointHomologyFreeComparisonStableExactAtRoute_productSuccess

#check
  Dbounded.closedMapEndpointHomologyFreeLeavesOfEndpointFactsLocalizedRightAdjointW900
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapEndpointLocalizedAdjointW900
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapEndpointLocalizedAdjointW900

theorem originalFourTaskContract_closedMapEndpointLocalizedAdjoint_inputCount :
    Dbounded.closedMapEndpointLocalizedAdjointInputNamesW900.length =
      33 :=
  Dbounded.closedMapEndpointLocalizedAdjointInputNamesW900_count

theorem originalFourTaskContract_closedMapEndpointLocalizedAdjoint_nonterminal :
    Dbounded.currentMetrizableClosedMapEndpointLocalizedAdjointRouteStateW900.productSuccessClaimed =
      false :=
  Dbounded.currentW900ClosedMapEndpointLocalizedAdjointRoute_productSuccess

#check Dbounded.closedMapEndpointLocalizedAdjointLeavesOfSourceTriangulationW901
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapSourceTriangulationEndpointFactsW901
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapSourceTriangulationEndpointFactsW901

theorem originalFourTaskContract_closedMapSourceTriangulationEndpointFacts_inputCount :
    Dbounded.closedMapSourceTriangulationEndpointFactsInputNamesW901.length =
      31 :=
  Dbounded.closedMapSourceTriangulationEndpointFactsInputNamesW901_count

theorem originalFourTaskContract_closedMapSourceTriangulationEndpointFacts_nonterminal :
    Dbounded.currentMetrizableClosedMapSourceTriangulationEndpointFactsRouteStateW901.productSuccessClaimed =
      false :=
  Dbounded.currentW901ClosedMapSourceTriangulationEndpointFactsRoute_productSuccess

#check Dbounded.closedMapSourceTriangulationEndpointFactsLeavesOfBoundaryDataW902
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapBoundaryDataSourceTriangulationEndpointFactsW902
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapBoundaryDataSourceTriangulationEndpointFactsW902

theorem originalFourTaskContract_closedMapBoundaryDataSourceTriangulationEndpointFacts_inputCount :
    Dbounded.closedMapBoundaryDataSourceTriangulationEndpointFactsInputNamesW902.length =
      30 :=
  Dbounded.closedMapBoundaryDataSourceTriangulationEndpointFactsInputNamesW902_count

theorem originalFourTaskContract_closedMapBoundaryDataSourceTriangulationEndpointFacts_nonterminal :
    Dbounded.currentMetrizableClosedMapBoundaryDataSourceTriangulationEndpointFactsRouteStateW902.productSuccessClaimed =
      false :=
  Dbounded.currentW902ClosedMapBoundaryDataSourceTriangulationEndpointFactsRoute_productSuccess

#check Dbounded.closedMapBoundaryEndpointFactsLeavesOfRelationDataW903
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapRelationDataBoundaryEndpointFactsW903
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapRelationDataBoundaryEndpointFactsW903

theorem originalFourTaskContract_closedMapRelationDataBoundaryDataSourceTriangulationEndpointFacts_inputCount :
    Dbounded.closedMapRelationDataBoundaryEndpointFactsInputNamesW903.length =
      29 :=
  Dbounded.closedMapRelationDataBoundaryEndpointFactsInputNamesW903_count

theorem originalFourTaskContract_closedMapRelationDataBoundaryDataSourceTriangulationEndpointFacts_nonterminal :
    Dbounded.currentMetrizableClosedMapRelationDataBoundaryEndpointFactsRouteStateW903.productSuccessClaimed =
      false :=
  Dbounded.currentW903ClosedMapRelationDataBoundaryEndpointFactsRoute_productSuccess

#check Dbounded.w903LeavesOfTargetDataW904
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapTargetDataEndpointFactsW904
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetDataEndpointFactsW904

theorem originalFourTaskContract_closedMapTargetDataEndpointFacts_inputCount :
    Dbounded.closedMapTargetDataEndpointFactsInputNamesW904.length =
      28 :=
  Dbounded.closedMapTargetDataEndpointFactsInputNamesW904_count

theorem originalFourTaskContract_closedMapTargetDataEndpointFacts_nonterminal :
    Dbounded.currentMetrizableClosedMapTargetDataEndpointFactsRouteStateW904.productSuccessClaimed =
      false :=
  Dbounded.currentW904ClosedMapTargetDataEndpointFactsRoute_productSuccess

#check Dbounded.w904LeavesOfMappedCokernelFieldW905
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapMappedCokernelFieldTargetDataW905
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapMappedCokernelFieldTargetDataW905

theorem originalFourTaskContract_closedMapMappedCokernelFieldTargetData_inputCount :
    Dbounded.closedMapMappedCokernelFieldTargetDataInputNamesW905.length =
      28 :=
  Dbounded.closedMapMappedCokernelFieldTargetDataInputNamesW905_count

theorem originalFourTaskContract_closedMapMappedCokernelFieldTargetData_nonterminal :
    Dbounded.currentMetrizableClosedMapMappedCokernelFieldTargetDataRouteStateW905.productSuccessClaimed =
      false :=
  Dbounded.currentW905ClosedMapMappedCokernelFieldTargetDataRoute_productSuccess

#check Dbounded.w905LeavesOfClosedMapComponentFieldsW906
#check
  Dbounded.directBoundedLeftCalculusOfClosedMapComponentFieldsMappedCokernelFieldTargetDataW906
#check
  Dbounded.boundedDerivedInfinityCategoryOfClosedMapComponentFieldsMappedCokernelFieldTargetDataW906

theorem originalFourTaskContract_closedMapComponentFieldsMappedCokernelFieldTargetData_inputCount :
    Dbounded.closedMapComponentFieldsMappedCokernelFieldTargetDataInputNamesW906.length =
      30 :=
  Dbounded.closedMapComponentFieldsMappedCokernelFieldTargetDataInputNamesW906_count

theorem originalFourTaskContract_closedMapComponentFieldsMappedCokernelFieldTargetData_nonterminal :
    Dbounded.currentMetrizableClosedMapComponentFieldsMappedCokernelFieldTargetDataRouteStateW906.productSuccessClaimed =
      false :=
  Dbounded.currentW906ClosedMapComponentFieldsMappedCokernelFieldTargetDataRoute_productSuccess

#check Dbounded.w906LeavesOfBoundaryFieldsW907
#check Dbounded.directBoundedLeftCalculusOfClosedMapBoundaryFieldsW907
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapBoundaryFieldsW907

theorem originalFourTaskContract_closedMapBoundaryFieldsComponentFieldsMappedCokernelFieldTargetData_inputCount :
    Dbounded.closedMapBoundaryFieldsInputNamesW907.length =
      31 :=
  Dbounded.closedMapBoundaryFieldsInputNamesW907_count

theorem originalFourTaskContract_closedMapBoundaryFieldsComponentFieldsMappedCokernelFieldTargetData_nonterminal :
    Dbounded.currentMetrizableClosedMapBoundaryFieldsRouteStateW907.productSuccessClaimed =
      false :=
  Dbounded.currentW907ClosedMapBoundaryFieldsRoute_productSuccess

#check Dbounded.w907LeavesOfRelationFieldsW908
#check Dbounded.directBoundedLeftCalculusOfClosedMapRelationFieldsW908
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapRelationFieldsW908

theorem originalFourTaskContract_closedMapRelationFields_inputCount :
    Dbounded.closedMapRelationFieldsInputNamesW908.length =
      32 :=
  Dbounded.closedMapRelationFieldsInputNamesW908_count

theorem originalFourTaskContract_closedMapRelationFields_nonterminal :
    Dbounded.currentMetrizableClosedMapRelationFieldsRouteStateW908.productSuccessClaimed =
      false :=
  Dbounded.currentW908ClosedMapRelationFieldsRoute_productSuccess

#check Dbounded.w908LeavesOfTargetFieldsW909
#check Dbounded.directBoundedLeftCalculusOfClosedMapTargetFieldsW909
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetFieldsW909

theorem originalFourTaskContract_closedMapTargetFields_inputCount :
    Dbounded.closedMapTargetFieldsInputNamesW909.length =
      33 :=
  Dbounded.closedMapTargetFieldsInputNamesW909_count

theorem originalFourTaskContract_closedMapTargetFields_nonterminal :
    Dbounded.currentMetrizableClosedMapTargetFieldsRouteStateW909.productSuccessClaimed =
      false :=
  Dbounded.currentW909ClosedMapTargetFieldsRoute_productSuccess

#check Dbounded.w909LeavesOfSourceFieldsW910
#check Dbounded.directBoundedLeftCalculusOfClosedMapSourceFieldsW910
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapSourceFieldsW910

theorem originalFourTaskContract_closedMapSourceFields_inputCount :
    Dbounded.closedMapSourceFieldsInputNamesW910.length =
      35 :=
  Dbounded.closedMapSourceFieldsInputNamesW910_count

theorem originalFourTaskContract_closedMapSourceFields_nonterminal :
    Dbounded.currentMetrizableClosedMapSourceFieldsRouteStateW910.productSuccessClaimed =
      false :=
  Dbounded.currentW910ClosedMapSourceFieldsRoute_productSuccess

#check Dbounded.w910LeavesOfEndpointFieldsW911
#check Dbounded.directBoundedLeftCalculusOfClosedMapEndpointFieldsW911
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapEndpointFieldsW911

theorem originalFourTaskContract_closedMapEndpointFields_inputCount :
    Dbounded.closedMapEndpointFieldsInputNamesW911.length =
      37 :=
  Dbounded.closedMapEndpointFieldsInputNamesW911_count

theorem originalFourTaskContract_closedMapEndpointFields_nonterminal :
    Dbounded.currentMetrizableClosedMapEndpointFieldsRouteStateW911.productSuccessClaimed =
      false :=
  Dbounded.currentW911ClosedMapEndpointFieldsRoute_productSuccess

#check Dbounded.w911LeavesOfLocalizedRightAdjointFieldsW912
#check Dbounded.directBoundedLeftCalculusOfClosedMapLocalizedRightAdjointFieldsW912
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapLocalizedRightAdjointFieldsW912

theorem originalFourTaskContract_closedMapLocalizedRightAdjointFields_inputCount :
    Dbounded.closedMapLocalizedRightAdjointFieldsInputNamesW912.length =
      39 :=
  Dbounded.closedMapLocalizedRightAdjointFieldsInputNamesW912_count

theorem originalFourTaskContract_closedMapLocalizedRightAdjointFields_nonterminal :
    Dbounded.currentMetrizableClosedMapLocalizedRightAdjointFieldsRouteStateW912.productSuccessClaimed =
      false :=
  Dbounded.currentW912ClosedMapLocalizedRightAdjointFieldsRoute_productSuccess

#check Dbounded.w912LeavesOfFixedTargetUniqFieldsW913
#check Dbounded.directBoundedLeftCalculusOfClosedMapFixedTargetUniqFieldsW913
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapFixedTargetUniqFieldsW913

theorem originalFourTaskContract_closedMapFixedTargetUniqFields_inputCount :
    Dbounded.closedMapFixedTargetUniqFieldsInputNamesW913.length =
      39 :=
  Dbounded.closedMapFixedTargetUniqFieldsInputNamesW913_count

theorem originalFourTaskContract_closedMapFixedTargetUniqFields_nonterminal :
    Dbounded.currentMetrizableClosedMapFixedTargetUniqFieldsRouteStateW913.productSuccessClaimed =
      false :=
  Dbounded.currentW913ClosedMapFixedTargetUniqFieldsRoute_productSuccess

#check Dbounded.w913LeavesOfSelectedDifferenceFieldsW914
#check Dbounded.directBoundedLeftCalculusOfClosedMapSelectedDifferenceFieldsW914
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapSelectedDifferenceFieldsW914

theorem originalFourTaskContract_closedMapSelectedDifferenceFields_inputCount :
    Dbounded.closedMapSelectedDifferenceFieldsInputNamesW914.length =
      39 :=
  Dbounded.closedMapSelectedDifferenceFieldsInputNamesW914_count

theorem originalFourTaskContract_closedMapSelectedDifferenceFields_nonterminal :
    Dbounded.currentMetrizableClosedMapSelectedDifferenceFieldsRouteStateW914.productSuccessClaimed =
      false :=
  Dbounded.currentW914ClosedMapSelectedDifferenceFieldsRoute_productSuccess

#check Dbounded.w914LeavesOfTargetRawFieldsW915
#check Dbounded.directBoundedLeftCalculusOfClosedMapTargetRawFieldsW915
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapTargetRawFieldsW915

theorem originalFourTaskContract_closedMapTargetRawFields_inputCount :
    Dbounded.closedMapTargetRawFieldsInputNamesW915.length =
      39 :=
  Dbounded.closedMapTargetRawFieldsInputNamesW915_count

theorem originalFourTaskContract_closedMapTargetRawFields_nonterminal :
    Dbounded.currentMetrizableClosedMapTargetRawFieldsRouteStateW915.productSuccessClaimed =
      false :=
  Dbounded.currentW915ClosedMapTargetRawFieldsRoute_productSuccess

#check Dbounded.w915LeavesOfRelationRawFieldsW916
#check Dbounded.directBoundedLeftCalculusOfClosedMapRelationRawFieldsW916
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapRelationRawFieldsW916

theorem originalFourTaskContract_closedMapRelationRawFields_inputCount :
    Dbounded.closedMapRelationRawFieldsInputNamesW916.length =
      39 :=
  Dbounded.closedMapRelationRawFieldsInputNamesW916_count

theorem originalFourTaskContract_closedMapRelationRawFields_nonterminal :
    Dbounded.currentMetrizableClosedMapRelationRawFieldsRouteStateW916.productSuccessClaimed =
      false :=
  Dbounded.currentW916ClosedMapRelationRawFieldsRoute_productSuccess

#check Dbounded.w916LeavesOfBoundaryRawFieldsW917
#check Dbounded.directBoundedLeftCalculusOfClosedMapBoundaryRawFieldsW917
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapBoundaryRawFieldsW917

theorem originalFourTaskContract_closedMapBoundaryRawFields_inputCount :
    Dbounded.closedMapBoundaryRawFieldsInputNamesW917.length =
      39 :=
  Dbounded.closedMapBoundaryRawFieldsInputNamesW917_count

theorem originalFourTaskContract_closedMapBoundaryRawFields_nonterminal :
    Dbounded.currentMetrizableClosedMapBoundaryRawFieldsRouteStateW917.productSuccessClaimed =
      false :=
  Dbounded.currentW917ClosedMapBoundaryRawFieldsRoute_productSuccess

#check Dbounded.w917LeavesOfTriangleCompletionRawFieldW918
#check Dbounded.directBoundedLeftCalculusOfClosedMapTriangleCompletionRawFieldBoundaryRawFieldsW918
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapTriangleCompletionRawFieldBoundaryRawFieldsW918

theorem originalFourTaskContract_closedMapTriangleCompletionRawField_inputCount :
    Dbounded.closedMapTriangleCompletionRawFieldBoundaryRawFieldsInputNamesW918.length =
      39 :=
  Dbounded.closedMapTriangleCompletionRawFieldBoundaryRawFieldsInputNamesW918_count

theorem originalFourTaskContract_closedMapTriangleCompletionRawField_nonterminal :
    Dbounded.currentMetrizableClosedMapTriangleCompletionRawFieldBoundaryRawFieldsRouteStateW918.productSuccessClaimed =
      false :=
  Dbounded.currentW918ClosedMapTriangleCompletionRawFieldBoundaryRawFieldsRoute_productSuccess

#check Dbounded.w918LeavesOfSourceRawFieldsW919
#check Dbounded.directBoundedLeftCalculusOfClosedMapSourceRawFieldsW919
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapSourceRawFieldsW919

theorem originalFourTaskContract_closedMapSourceRawFields_inputCount :
    Dbounded.closedMapSourceRawFieldsInputNamesW919.length =
      39 :=
  Dbounded.closedMapSourceRawFieldsInputNamesW919_count

theorem originalFourTaskContract_closedMapSourceRawFields_nonterminal :
    Dbounded.currentMetrizableClosedMapSourceRawFieldsRouteStateW919.productSuccessClaimed =
      false :=
  Dbounded.currentW919ClosedMapSourceRawFieldsRoute_productSuccess

#check Dbounded.w919LeavesOfRelationPrimitiveFieldsW920
#check Dbounded.directBoundedLeftCalculusOfClosedMapRelationPrimitiveFieldsW920
#check Dbounded.boundedDerivedInfinityCategoryOfClosedMapRelationPrimitiveFieldsW920

theorem originalFourTaskContract_closedMapRelationPrimitiveFields_inputCount :
    Dbounded.closedMapRelationPrimitiveFieldsInputNamesW920.length =
      39 :=
  Dbounded.closedMapRelationPrimitiveFieldsInputNamesW920_count

theorem originalFourTaskContract_closedMapRelationPrimitiveFields_nonterminal :
    Dbounded.currentMetrizableClosedMapRelationPrimitiveFieldsRouteStateW920.productSuccessClaimed =
      false :=
  Dbounded.currentW920ClosedMapRelationPrimitiveFieldsRoute_productSuccess

end LeanLCAExactChallenge
