import LeanLCAExactChallenge

set_option autoImplicit false

#check LeanLCAExactChallenge.QuillenExactCategory
#check LeanLCAExactChallenge.QuillenExactCategory.Conflation
#check LeanLCAExactChallenge.QuillenExactCategory.inflation
#check LeanLCAExactChallenge.QuillenExactCategory.deflation
#check LeanLCAExactChallenge.QuillenExactCategory.split_conflation
#check LeanLCAExactChallenge.QuillenExactCategory.pushout_inflation
#check LeanLCAExactChallenge.QuillenExactCategory.pullback_deflation

#check LeanLCAExactChallenge.MetrizableLCA
#check LeanLCAExactChallenge.MetrizableLCA.Hom
#check LeanLCAExactChallenge.MetrizableLCA.strictShortExact
#check LeanLCAExactChallenge.MetrizableLCA.closed_inclusion_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.open_surjection_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.algebraic_kernel_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.algebraic_cokernel_of_strict
#check LeanLCAExactChallenge.MetrizableLCA.quotientObj
#check LeanLCAExactChallenge.MetrizableLCA.quotientMap
#check LeanLCAExactChallenge.MetrizableLCA.quotientMap_surjective
#check LeanLCAExactChallenge.MetrizableLCA.quotientMap_openMap
#check LeanLCAExactChallenge.MetrizableLCA.quotientLift
#check LeanLCAExactChallenge.MetrizableLCA.quotientLift_quotientMap
#check LeanLCAExactChallenge.MetrizableLCA.pushoutRelationMap
#check LeanLCAExactChallenge.MetrizableLCA.pushoutSubgroup
#check LeanLCAExactChallenge.MetrizableLCA.pushoutObj
#check LeanLCAExactChallenge.MetrizableLCA.pushoutInl
#check LeanLCAExactChallenge.MetrizableLCA.pushoutInr
#check LeanLCAExactChallenge.MetrizableLCA.pushout_condition
#check LeanLCAExactChallenge.MetrizableLCA.pushoutDesc
#check LeanLCAExactChallenge.MetrizableLCA.pushout_hom_ext
#check LeanLCAExactChallenge.MetrizableLCA.pushoutCocone
#check LeanLCAExactChallenge.MetrizableLCA.pushoutIsColimit
#check LeanLCAExactChallenge.MetrizableLCA.hasPushout_of_pushoutSubgroup_closed
#check LeanLCAExactChallenge.MetrizableLCA.pushoutCokernelMap
#check LeanLCAExactChallenge.MetrizableLCA.pushoutQuotientMap_cokernel
#check LeanLCAExactChallenge.MetrizableLCA.pushoutInl_cokernel
#check LeanLCAExactChallenge.MetrizableLCA.pushoutInr_cokernel
#check LeanLCAExactChallenge.MetrizableLCA.pushoutCokernelMap_openMap
#check LeanLCAExactChallenge.MetrizableLCA.pushoutCokernelMap_surjective
#check LeanLCAExactChallenge.MetrizableLCA.pushoutCokernelMap_algebraic_exact
#check LeanLCAExactChallenge.MetrizableLCA.pullbackObj
#check LeanLCAExactChallenge.MetrizableLCA.pullbackIsLimit
#check LeanLCAExactChallenge.MetrizableLCA.isClosedEmbedding_zero_prod
#check LeanLCAExactChallenge.MetrizableLCA.pullbackIsoPullbackObj
#check LeanLCAExactChallenge.MetrizableLCA.pullbackIsoPullbackObj_hom_fst
#check LeanLCAExactChallenge.MetrizableLCA.pullbackIsoPullbackObj_inv_fst
#check LeanLCAExactChallenge.MetrizableLCA.pullbackFst_surjective_of_snd_surjective
#check LeanLCAExactChallenge.MetrizableLCA.pullbackFst_openMap_of_snd_openMap
#check LeanLCAExactChallenge.MetrizableLCA.pullbackSnd_surjective_of_fst_surjective
#check LeanLCAExactChallenge.MetrizableLCA.pullbackKernelMap
#check LeanLCAExactChallenge.MetrizableLCA.pullbackKernelMap_fst
#check LeanLCAExactChallenge.MetrizableLCA.pullbackKernelMap_snd
#check LeanLCAExactChallenge.MetrizableLCA.pullbackKernelMap_algebraic_exact
#check LeanLCAExactChallenge.MetrizableLCA.pullbackKernelMap_closedEmbedding
#check LeanLCAExactChallenge.MetrizableLCA.strictShortExact_pullback
#check LeanLCAExactChallenge.MetrizableLCA.strictShortExact_categorical_pullback
#check LeanLCAExactChallenge.MetrizableLCA.quillenExactCategory

#check LeanLCAExactChallenge.YonedaExt
#check LeanLCAExactChallenge.YonedaExt.zero_equiv_hom
#check LeanLCAExactChallenge.YonedaExt.baer_sum
#check LeanLCAExactChallenge.YonedaExt.instAddCommGroup

#check LeanLCAExactChallenge.BoundedDerivedInfinityCategory
#check LeanLCAExactChallenge.Dbounded
