#check LeanLCAExactChallenge.OriginalFourTaskProductSuccess
#check LeanLCAExactChallenge.originalFourTaskProductSuccess
#check LeanLCAExactChallenge.originalFourTaskProductSuccess_quillenExactCategory
#check LeanLCAExactChallenge.originalFourTaskProductSuccess_metrizableLCAExactCategory
#check LeanLCAExactChallenge.originalFourTaskProductSuccess_yonedaExt
#check LeanLCAExactChallenge.originalFourTaskProductSuccess_boundedDerivedInfinityCategory
