import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataRepeatedDirectRouteAliasGuardW1283
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromCurrentFullDataToBranchFullDataDirectRouteW1053
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromComponentFieldsToCurrentFullDataDirectRouteW1054
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromUnitStrictExactIsoDataToComponentFieldsDirectRouteW1055
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromLocalizedUnitChoiceToUnitStrictExactIsoDataDirectRouteW1056
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromEndpointLocalizedUnitToLocalizedUnitChoiceDirectRouteW1057
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromNormalizedSourceEndpointLocalizedUnitToEndpointLocalizedUnitDirectRouteW1058
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessToNormalizedSourceEndpointLocalizedUnitDirectRouteW1059
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessNormalizedSourceEndpointToTargetClosedEmbeddingClosednessDirectRouteW1060
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromBranchFullDataToTargetClosedEmbeddingClosednessNormalizedSourceEndpointDirectRouteW1061
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromCurrentFullDataToBranchFullDataDirectRouteW1062
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromComponentFieldsToCurrentFullDataDirectRouteW1063
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromUnitStrictExactIsoDataToComponentFieldsDirectRouteW1064
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromLocalizedUnitChoiceToUnitStrictExactIsoDataDirectRouteW1065
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromEndpointLocalizedUnitToLocalizedUnitChoiceDirectRouteW1066
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromNormalizedSourceEndpointLocalizedUnitToEndpointLocalizedUnitDirectRouteW1067
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessToNormalizedSourceEndpointLocalizedUnitDirectRouteW1068
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessNormalizedSourceEndpointToTargetClosedEmbeddingClosednessDirectRouteW1069
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromBranchFullDataToTargetClosedEmbeddingClosednessNormalizedSourceEndpointDirectRouteW1070

/-!
W1284 records the repeated W1053-W1070 direct-route alias bands.

These routes repeat the same one-input wrappers and larger expansions seen in
W1283, so they do not close the current W987 provider.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace LeanLCAExactChallenge

open CategoryTheory
open CategoryTheory.Limits
open Topology
open DirectWppLimitFiniteShapeTransfer
open WppOpW426W318LegCompatibilityAlignmentV370SupportW439
open WppOpSelectedW461TransportedPointIsoProviderV370SupportW506
open WppOpClosedNatTransOrdinaryRelationTopologyV370SupportW511
open WppOpClosedNatTransOrdinaryRelationFieldsV370SupportW512
open WppOpW461BridgeComponentwiseClosedRangeProjectionV370SupportW481
open WppOpClosedRangeOnlyComponentwiseProjectionV370SupportW484
open WppOpClosedRangeMappedCokernelPreservationV370SupportW519

namespace Dbounded

def currentFullDataRepeatCInputNamesW1284 : List String := currentFullDataInputNamesW1053
def componentFieldsRepeatCInputNamesW1284 : List String := componentFieldsInputNamesW1054
def unitStrictExactIsoDataRepeatCInputNamesW1284 : List String := unitStrictExactIsoDataInputNamesW1055
def localizedUnitChoiceRepeatCInputNamesW1284 : List String := localizedUnitChoiceInputNamesW1056
def endpointLocalizedUnitRepeatCInputNamesW1284 : List String := endpointLocalizedUnitInputNamesW1057
def normalizedSourceEndpointLocalizedUnitRepeatCInputNamesW1284 : List String :=
  normalizedSourceEndpointLocalizedUnitInputNamesW1058
def targetClosedEmbeddingClosednessRepeatCInputNamesW1284 : List String :=
  targetClosedEmbeddingClosednessInputNamesW1059
def targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatCInputNamesW1284 :
    List String :=
  targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1060
def branchFullDataRepeatCInputNamesW1284 : List String := branchFullDataInputNamesW1061
def currentFullDataRepeatDInputNamesW1284 : List String := currentFullDataInputNamesW1062
def componentFieldsRepeatDInputNamesW1284 : List String := componentFieldsInputNamesW1063
def unitStrictExactIsoDataRepeatDInputNamesW1284 : List String := unitStrictExactIsoDataInputNamesW1064
def localizedUnitChoiceRepeatDInputNamesW1284 : List String := localizedUnitChoiceInputNamesW1065
def endpointLocalizedUnitRepeatDInputNamesW1284 : List String := endpointLocalizedUnitInputNamesW1066
def normalizedSourceEndpointLocalizedUnitRepeatDInputNamesW1284 : List String :=
  normalizedSourceEndpointLocalizedUnitInputNamesW1067
def targetClosedEmbeddingClosednessRepeatDInputNamesW1284 : List String :=
  targetClosedEmbeddingClosednessInputNamesW1068
def targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatDInputNamesW1284 :
    List String :=
  targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1069
def branchFullDataRepeatDInputNamesW1284 : List String := branchFullDataInputNamesW1070

theorem currentFullDataRepeatCInputNamesW1284_count :
    currentFullDataRepeatCInputNamesW1284.length = 1 := currentFullDataInputNamesW1053_count
theorem componentFieldsRepeatCInputNamesW1284_count :
    componentFieldsRepeatCInputNamesW1284.length = 18 := componentFieldsInputNamesW1054_count
theorem unitStrictExactIsoDataRepeatCInputNamesW1284_count :
    unitStrictExactIsoDataRepeatCInputNamesW1284.length = 7 := unitStrictExactIsoDataInputNamesW1055_count
theorem localizedUnitChoiceRepeatCInputNamesW1284_count :
    localizedUnitChoiceRepeatCInputNamesW1284.length = 6 := localizedUnitChoiceInputNamesW1056_count
theorem endpointLocalizedUnitRepeatCInputNamesW1284_count :
    endpointLocalizedUnitRepeatCInputNamesW1284.length = 5 := endpointLocalizedUnitInputNamesW1057_count
theorem normalizedSourceEndpointLocalizedUnitRepeatCInputNamesW1284_count :
    normalizedSourceEndpointLocalizedUnitRepeatCInputNamesW1284.length = 4 :=
  normalizedSourceEndpointLocalizedUnitInputNamesW1058_count
theorem targetClosedEmbeddingClosednessRepeatCInputNamesW1284_count :
    targetClosedEmbeddingClosednessRepeatCInputNamesW1284.length = 3 :=
  targetClosedEmbeddingClosednessInputNamesW1059_count
theorem targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatCInputNamesW1284_count :
    targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatCInputNamesW1284.length =
      2 :=
  targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1060_count
theorem branchFullDataRepeatCInputNamesW1284_count :
    branchFullDataRepeatCInputNamesW1284.length = 1 := branchFullDataInputNamesW1061_count
theorem currentFullDataRepeatDInputNamesW1284_count :
    currentFullDataRepeatDInputNamesW1284.length = 1 := currentFullDataInputNamesW1062_count
theorem componentFieldsRepeatDInputNamesW1284_count :
    componentFieldsRepeatDInputNamesW1284.length = 18 := componentFieldsInputNamesW1063_count
theorem unitStrictExactIsoDataRepeatDInputNamesW1284_count :
    unitStrictExactIsoDataRepeatDInputNamesW1284.length = 7 := unitStrictExactIsoDataInputNamesW1064_count
theorem localizedUnitChoiceRepeatDInputNamesW1284_count :
    localizedUnitChoiceRepeatDInputNamesW1284.length = 6 := localizedUnitChoiceInputNamesW1065_count
theorem endpointLocalizedUnitRepeatDInputNamesW1284_count :
    endpointLocalizedUnitRepeatDInputNamesW1284.length = 5 := endpointLocalizedUnitInputNamesW1066_count
theorem normalizedSourceEndpointLocalizedUnitRepeatDInputNamesW1284_count :
    normalizedSourceEndpointLocalizedUnitRepeatDInputNamesW1284.length = 4 :=
  normalizedSourceEndpointLocalizedUnitInputNamesW1067_count
theorem targetClosedEmbeddingClosednessRepeatDInputNamesW1284_count :
    targetClosedEmbeddingClosednessRepeatDInputNamesW1284.length = 3 :=
  targetClosedEmbeddingClosednessInputNamesW1068_count
theorem targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatDInputNamesW1284_count :
    targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatDInputNamesW1284.length =
      2 :=
  targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1069_count
theorem branchFullDataRepeatDInputNamesW1284_count :
    branchFullDataRepeatDInputNamesW1284.length = 1 := branchFullDataInputNamesW1070_count

theorem repeatedDirectRouteWrappersKeepCurrentSurfaceW1284 :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      currentFullDataRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      branchFullDataRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      currentFullDataRepeatDInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      branchFullDataRepeatDInputNamesW1284.length := by
  rw [currentFullDataPayloadFromBranchFullDataInputNamesW1270_count,
    currentFullDataRepeatCInputNamesW1284_count,
    branchFullDataRepeatCInputNamesW1284_count,
    currentFullDataRepeatDInputNamesW1284_count,
    branchFullDataRepeatDInputNamesW1284_count]
  exact ⟨rfl, rfl, rfl, rfl⟩

theorem repeatedDirectRouteAliasesDoNotReduceW1284 :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      componentFieldsRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      unitStrictExactIsoDataRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      localizedUnitChoiceRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      endpointLocalizedUnitRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      normalizedSourceEndpointLocalizedUnitRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatCInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      componentFieldsRepeatDInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      unitStrictExactIsoDataRepeatDInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      localizedUnitChoiceRepeatDInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      endpointLocalizedUnitRepeatDInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      normalizedSourceEndpointLocalizedUnitRepeatDInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessRepeatDInputNamesW1284.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatDInputNamesW1284.length := by
  rw [currentFullDataPayloadFromBranchFullDataInputNamesW1270_count,
    componentFieldsRepeatCInputNamesW1284_count,
    unitStrictExactIsoDataRepeatCInputNamesW1284_count,
    localizedUnitChoiceRepeatCInputNamesW1284_count,
    endpointLocalizedUnitRepeatCInputNamesW1284_count,
    normalizedSourceEndpointLocalizedUnitRepeatCInputNamesW1284_count,
    targetClosedEmbeddingClosednessRepeatCInputNamesW1284_count,
    targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatCInputNamesW1284_count,
    componentFieldsRepeatDInputNamesW1284_count,
    unitStrictExactIsoDataRepeatDInputNamesW1284_count,
    localizedUnitChoiceRepeatDInputNamesW1284_count,
    endpointLocalizedUnitRepeatDInputNamesW1284_count,
    normalizedSourceEndpointLocalizedUnitRepeatDInputNamesW1284_count,
    targetClosedEmbeddingClosednessRepeatDInputNamesW1284_count,
    targetClosedEmbeddingClosednessNormalizedSourceEndpointRepeatDInputNamesW1284_count]
  norm_num

structure MetrizableRepeatedDirectRouteAliasGuardStateW1284 : Type where
  seed : String
  inspectedRoutes : List String
  routeInputCounts : List (String × Nat)
  providerSearchResult : String
  remainingInputs : List String
  productSuccessClaimed : Bool

def currentMetrizableRepeatedDirectRouteAliasGuardStateW1284 :
    MetrizableRepeatedDirectRouteAliasGuardStateW1284 where
  seed := "w1284-repeated-direct-route-alias-guard"
  inspectedRoutes :=
    ["W1053-W1061 direct-route alias band", "W1062-W1070 direct-route alias band"]
  routeInputCounts :=
    [("W1053 current-full-data wrapper", 1), ("W1061 branch-full-data wrapper", 1),
      ("W1062 current-full-data wrapper", 1), ("W1070 branch-full-data wrapper", 1),
      ("each middle band", 18), ("each middle band", 7), ("each middle band", 6),
      ("each middle band", 5), ("each middle band", 4), ("each middle band", 3),
      ("each middle band", 2)]
  providerSearchResult :=
    "proved: W1053/W1061/W1062/W1070 preserve the current W1270 one-input\
      surface, while W1054-W1060 and W1063-W1069 expand"
  remainingInputs := currentFullDataPayloadFromBranchFullDataInputNamesW1270
  productSuccessClaimed := false

theorem currentW1284RepeatedDirectRouteAliasGuard_productSuccess :
    (let state :=
        currentMetrizableRepeatedDirectRouteAliasGuardStateW1284;
      state.productSuccessClaimed) =
      false :=
  rfl

end Dbounded

end LeanLCAExactChallenge
