import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataRepeatedDirectRouteAliasGuardW1289
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromCurrentFullDataToBranchFullDataDirectRouteW1161
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromComponentFieldsToCurrentFullDataDirectRouteW1162
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromUnitStrictExactIsoDataToComponentFieldsDirectRouteW1163
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromLocalizedUnitChoiceToUnitStrictExactIsoDataDirectRouteW1164
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromEndpointLocalizedUnitToLocalizedUnitChoiceDirectRouteW1165
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromNormalizedSourceEndpointLocalizedUnitToEndpointLocalizedUnitDirectRouteW1166
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessToNormalizedSourceEndpointLocalizedUnitDirectRouteW1167
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessNormalizedSourceEndpointToTargetClosedEmbeddingClosednessDirectRouteW1168
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromBranchFullDataToTargetClosedEmbeddingClosednessNormalizedSourceEndpointDirectRouteW1169
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromCurrentFullDataToBranchFullDataDirectRouteW1170
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromComponentFieldsToCurrentFullDataDirectRouteW1171
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromUnitStrictExactIsoDataToComponentFieldsDirectRouteW1172
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromLocalizedUnitChoiceToUnitStrictExactIsoDataDirectRouteW1173
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromEndpointLocalizedUnitToLocalizedUnitChoiceDirectRouteW1174
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromNormalizedSourceEndpointLocalizedUnitToEndpointLocalizedUnitDirectRouteW1175
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessToNormalizedSourceEndpointLocalizedUnitDirectRouteW1176
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessNormalizedSourceEndpointToTargetClosedEmbeddingClosednessDirectRouteW1177
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromBranchFullDataToTargetClosedEmbeddingClosednessNormalizedSourceEndpointDirectRouteW1178

/-!
W1290 records the repeated W1161-W1178 direct-route alias bands.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace LeanLCAExactChallenge

open CategoryTheory
open CategoryTheory.Limits
open Topology
open DirectWppLimitFiniteShapeTransfer
open WppOpW426W318LegCompatibilityAlignmentV370SupportW439
open WppOpSelectedW461TransportedPointIsoProviderV370SupportW506
open WppOpClosedNatTransOrdinaryRelationTopologyV370SupportW511
open WppOpClosedNatTransOrdinaryRelationFieldsV370SupportW512
open WppOpW461BridgeComponentwiseClosedRangeProjectionV370SupportW481
open WppOpClosedRangeOnlyComponentwiseProjectionV370SupportW484
open WppOpClosedRangeMappedCokernelPreservationV370SupportW519

namespace Dbounded

theorem repeatedDirectRouteWrappersKeepCurrentSurfaceW1290 :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      currentFullDataInputNamesW1161.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      branchFullDataInputNamesW1169.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      currentFullDataInputNamesW1170.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      branchFullDataInputNamesW1178.length := by
  rw [currentFullDataPayloadFromBranchFullDataInputNamesW1270_count,
    currentFullDataInputNamesW1161_count,
    branchFullDataInputNamesW1169_count,
    currentFullDataInputNamesW1170_count,
    branchFullDataInputNamesW1178_count]
  exact ⟨rfl, rfl, rfl, rfl⟩

theorem repeatedDirectRouteAliasesDoNotReduceW1290 :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      componentFieldsInputNamesW1162.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      unitStrictExactIsoDataInputNamesW1163.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      localizedUnitChoiceInputNamesW1164.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      endpointLocalizedUnitInputNamesW1165.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      normalizedSourceEndpointLocalizedUnitInputNamesW1166.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessInputNamesW1167.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1168.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      componentFieldsInputNamesW1171.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      unitStrictExactIsoDataInputNamesW1172.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      localizedUnitChoiceInputNamesW1173.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      endpointLocalizedUnitInputNamesW1174.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      normalizedSourceEndpointLocalizedUnitInputNamesW1175.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessInputNamesW1176.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1177.length := by
  rw [currentFullDataPayloadFromBranchFullDataInputNamesW1270_count,
    componentFieldsInputNamesW1162_count,
    unitStrictExactIsoDataInputNamesW1163_count,
    localizedUnitChoiceInputNamesW1164_count,
    endpointLocalizedUnitInputNamesW1165_count,
    normalizedSourceEndpointLocalizedUnitInputNamesW1166_count,
    targetClosedEmbeddingClosednessInputNamesW1167_count,
    targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1168_count,
    componentFieldsInputNamesW1171_count,
    unitStrictExactIsoDataInputNamesW1172_count,
    localizedUnitChoiceInputNamesW1173_count,
    endpointLocalizedUnitInputNamesW1174_count,
    normalizedSourceEndpointLocalizedUnitInputNamesW1175_count,
    targetClosedEmbeddingClosednessInputNamesW1176_count,
    targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1177_count]
  norm_num

structure MetrizableRepeatedDirectRouteAliasGuardStateW1290 : Type where
  seed : String
  inspectedRoutes : List String
  routeInputCounts : List (String × Nat)
  providerSearchResult : String
  remainingInputs : List String
  productSuccessClaimed : Bool

def currentMetrizableRepeatedDirectRouteAliasGuardStateW1290 :
    MetrizableRepeatedDirectRouteAliasGuardStateW1290 where
  seed := "w1290-repeated-direct-route-alias-guard"
  inspectedRoutes :=
    ["W1161-W1169 direct-route alias band", "W1170-W1178 direct-route alias band"]
  routeInputCounts :=
    [("W1161 current-full-data wrapper", 1), ("W1169 branch-full-data wrapper", 1),
      ("W1170 current-full-data wrapper", 1), ("W1178 branch-full-data wrapper", 1),
      ("each middle band", 18), ("each middle band", 7), ("each middle band", 6),
      ("each middle band", 5), ("each middle band", 4), ("each middle band", 3),
      ("each middle band", 2)]
  providerSearchResult :=
    "proved: W1161/W1169/W1170/W1178 preserve the current W1270 one-input\
      surface, while W1162-W1168 and W1171-W1177 expand"
  remainingInputs := currentFullDataPayloadFromBranchFullDataInputNamesW1270
  productSuccessClaimed := false

theorem currentW1290RepeatedDirectRouteAliasGuard_productSuccess :
    (let state :=
        currentMetrizableRepeatedDirectRouteAliasGuardStateW1290;
      state.productSuccessClaimed) =
      false :=
  rfl

end Dbounded

end LeanLCAExactChallenge
