import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataRepeatedDirectRouteAliasGuardW1287
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromCurrentFullDataToBranchFullDataDirectRouteW1125
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromComponentFieldsToCurrentFullDataDirectRouteW1126
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromUnitStrictExactIsoDataToComponentFieldsDirectRouteW1127
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromLocalizedUnitChoiceToUnitStrictExactIsoDataDirectRouteW1128
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromEndpointLocalizedUnitToLocalizedUnitChoiceDirectRouteW1129
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromNormalizedSourceEndpointLocalizedUnitToEndpointLocalizedUnitDirectRouteW1130
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessToNormalizedSourceEndpointLocalizedUnitDirectRouteW1131
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessNormalizedSourceEndpointToTargetClosedEmbeddingClosednessDirectRouteW1132
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromBranchFullDataToTargetClosedEmbeddingClosednessNormalizedSourceEndpointDirectRouteW1133
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromCurrentFullDataToBranchFullDataDirectRouteW1134
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromComponentFieldsToCurrentFullDataDirectRouteW1135
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromUnitStrictExactIsoDataToComponentFieldsDirectRouteW1136
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromLocalizedUnitChoiceToUnitStrictExactIsoDataDirectRouteW1137
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromEndpointLocalizedUnitToLocalizedUnitChoiceDirectRouteW1138
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromNormalizedSourceEndpointLocalizedUnitToEndpointLocalizedUnitDirectRouteW1139
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessToNormalizedSourceEndpointLocalizedUnitDirectRouteW1140
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromTargetClosedEmbeddingClosednessNormalizedSourceEndpointToTargetClosedEmbeddingClosednessDirectRouteW1141
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataFromBranchFullDataToTargetClosedEmbeddingClosednessNormalizedSourceEndpointDirectRouteW1142

/-!
W1288 records the repeated W1125-W1142 direct-route alias bands.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace LeanLCAExactChallenge

open CategoryTheory
open CategoryTheory.Limits
open Topology
open DirectWppLimitFiniteShapeTransfer
open WppOpW426W318LegCompatibilityAlignmentV370SupportW439
open WppOpSelectedW461TransportedPointIsoProviderV370SupportW506
open WppOpClosedNatTransOrdinaryRelationTopologyV370SupportW511
open WppOpClosedNatTransOrdinaryRelationFieldsV370SupportW512
open WppOpW461BridgeComponentwiseClosedRangeProjectionV370SupportW481
open WppOpClosedRangeOnlyComponentwiseProjectionV370SupportW484
open WppOpClosedRangeMappedCokernelPreservationV370SupportW519

namespace Dbounded

theorem repeatedDirectRouteWrappersKeepCurrentSurfaceW1288 :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      currentFullDataInputNamesW1125.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      branchFullDataInputNamesW1133.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      currentFullDataInputNamesW1134.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length =
      branchFullDataInputNamesW1142.length := by
  rw [currentFullDataPayloadFromBranchFullDataInputNamesW1270_count,
    currentFullDataInputNamesW1125_count,
    branchFullDataInputNamesW1133_count,
    currentFullDataInputNamesW1134_count,
    branchFullDataInputNamesW1142_count]
  exact ⟨rfl, rfl, rfl, rfl⟩

theorem repeatedDirectRouteAliasesDoNotReduceW1288 :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      componentFieldsInputNamesW1126.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      unitStrictExactIsoDataInputNamesW1127.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      localizedUnitChoiceInputNamesW1128.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      endpointLocalizedUnitInputNamesW1129.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      normalizedSourceEndpointLocalizedUnitInputNamesW1130.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessInputNamesW1131.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1132.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      componentFieldsInputNamesW1135.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      unitStrictExactIsoDataInputNamesW1136.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      localizedUnitChoiceInputNamesW1137.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      endpointLocalizedUnitInputNamesW1138.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      normalizedSourceEndpointLocalizedUnitInputNamesW1139.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessInputNamesW1140.length ∧
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length <
      targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1141.length := by
  rw [currentFullDataPayloadFromBranchFullDataInputNamesW1270_count,
    componentFieldsInputNamesW1126_count,
    unitStrictExactIsoDataInputNamesW1127_count,
    localizedUnitChoiceInputNamesW1128_count,
    endpointLocalizedUnitInputNamesW1129_count,
    normalizedSourceEndpointLocalizedUnitInputNamesW1130_count,
    targetClosedEmbeddingClosednessInputNamesW1131_count,
    targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1132_count,
    componentFieldsInputNamesW1135_count,
    unitStrictExactIsoDataInputNamesW1136_count,
    localizedUnitChoiceInputNamesW1137_count,
    endpointLocalizedUnitInputNamesW1138_count,
    normalizedSourceEndpointLocalizedUnitInputNamesW1139_count,
    targetClosedEmbeddingClosednessInputNamesW1140_count,
    targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1141_count]
  norm_num

structure MetrizableRepeatedDirectRouteAliasGuardStateW1288 : Type where
  seed : String
  inspectedRoutes : List String
  routeInputCounts : List (String × Nat)
  providerSearchResult : String
  remainingInputs : List String
  productSuccessClaimed : Bool

def currentMetrizableRepeatedDirectRouteAliasGuardStateW1288 :
    MetrizableRepeatedDirectRouteAliasGuardStateW1288 where
  seed := "w1288-repeated-direct-route-alias-guard"
  inspectedRoutes :=
    ["W1125-W1133 direct-route alias band", "W1134-W1142 direct-route alias band"]
  routeInputCounts :=
    [("W1125 current-full-data wrapper", 1), ("W1133 branch-full-data wrapper", 1),
      ("W1134 current-full-data wrapper", 1), ("W1142 branch-full-data wrapper", 1),
      ("each middle band", 18), ("each middle band", 7), ("each middle band", 6),
      ("each middle band", 5), ("each middle band", 4), ("each middle band", 3),
      ("each middle band", 2)]
  providerSearchResult :=
    "proved: W1125/W1133/W1134/W1142 preserve the current W1270 one-input\
      surface, while W1126-W1132 and W1135-W1141 expand"
  remainingInputs := currentFullDataPayloadFromBranchFullDataInputNamesW1270
  productSuccessClaimed := false

theorem currentW1288RepeatedDirectRouteAliasGuard_productSuccess :
    (let state :=
        currentMetrizableRepeatedDirectRouteAliasGuardStateW1288;
      state.productSuccessClaimed) =
      false :=
  rfl

end Dbounded

end LeanLCAExactChallenge
