import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromTargetClosedEmbeddingClosednessW1267
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitW1268
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromTargetNormalizedEndpointW1269
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromBranchFullDataW1270
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataBranchFullDataCurrentFullDataCycleGuardW1271
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceFullDataStableConvergenceFieldSplitGuardW1424
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceProjectionStableConvergenceFieldSplitGuardW1425
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceNestedProjectionStableConvergenceFieldSplitGuardW1430
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceDeepProjectionStableConvergenceFieldSplitGuardW1431
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapEndpointLocalizedUnitStableConvergenceFieldSplitGuardW1432
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapNormalizedSourceEndpointLocalizedUnitStableConvergenceFieldSplitGuardW1433
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapTargetClosedEmbeddingClosednessStableConvergenceFieldSplitGuardW1434
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapTargetClosedEmbeddingClosednessNormalizedSourceEndpointStableConvergenceFieldSplitGuardW1435
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataStableConvergenceFieldSplitGuardW1436
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataOneInputCycleGuardW1437
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW987UnpackBoundaryGuardW1438
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW986UnpackBoundaryGuardW1439
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW984TargetClosednessUnpackBoundaryGuardW1440
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW950NormalizedEndpointUnpackBoundaryGuardW1441
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW948NormalizedSourceUnpackBoundaryGuardW1442
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW949EndpointLocalizedUnitUnpackBoundaryGuardW1443

namespace LeanLCAExactChallenge
namespace Dbounded

/-- Current original-four-task completion witness surface audited by the contract gates.

This packages the checked W1267-W1271 route evidence that remains nonterminal:
it records the current reduction counts and explicitly does not claim product
success. -/
structure OriginalFourTaskContractCompletion where
  targetClosedEmbeddingClosednessInputCount :
    currentFullDataPayloadFromTargetClosedEmbeddingClosednessInputNamesW1267.length = 4
  normalizedSourceEndpointLocalizedUnitInputCount :
    currentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitInputNamesW1268.length = 3
  targetNormalizedEndpointInputCount :
    currentFullDataPayloadFromTargetNormalizedEndpointInputNamesW1269.length = 2
  branchFullDataInputCount :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length = 1
  branchFullDataCurrentFullDataCycleInputCount :
    branchFullDataCurrentFullDataCycleInputNamesW1271.length = 1
  localizedUnitChoiceBridgeInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceNestedProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceDeepProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  endpointLocalizedUnitBridgeInputCount :
    endpointLocalizedUnitInputNamesW1165.length = 5
  normalizedSourceEndpointLocalizedUnitBridgeInputCount :
    normalizedSourceEndpointLocalizedUnitInputNamesW1166.length = 4
  targetClosedEmbeddingClosednessBridgeInputCount :
    targetClosedEmbeddingClosednessInputNamesW1167.length = 3
  targetClosedEmbeddingClosednessNormalizedSourceEndpointBridgeInputCount :
    targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1168.length = 2
  branchFullDataBridgeInputCount :
    branchFullDataInputNamesW1169.length = 1
  branchFullDataUnderlyingW987InputCount :
    branchFullDataInputNamesW1007.length = 1
  branchFullDataBridgeMatchesW987InputCount :
    branchFullDataInputNamesW1169.length = branchFullDataInputNamesW1007.length
  branchFullDataBridgeMatchesCurrentPayloadInputCount :
    branchFullDataInputNamesW1169.length =
      currentFullDataPayloadFromBranchFullDataInputNamesW1270.length
  branchFullDataBridgeMatchesCurrentFullDataCycleInputCount :
    branchFullDataInputNamesW1169.length =
      branchFullDataCurrentFullDataCycleInputNamesW1271.length
  branchFullDataUnpackedW730W986InputCount :
    canonicalFullDataUnpackedInputNamesW1298.length = 2
  branchFullDataW1007UnpackExpandsInputCount :
    branchFullDataInputNamesW1007.length <
      canonicalFullDataUnpackedInputNamesW1298.length
  branchFullDataBridgeUnpackExpandsInputCount :
    branchFullDataInputNamesW1169.length <
      canonicalFullDataUnpackedInputNamesW1298.length
  branchFullDataUnpackedW730W984W950InputCount :
    canonicalW986InnerUnpackedInputNamesW1299.length = 3
  branchFullDataW987UnpackExpandsToW986InnerInputCount :
    canonicalFullDataUnpackedInputNamesW1298.length <
      canonicalW986InnerUnpackedInputNamesW1299.length
  branchFullDataBridgeUnpackExpandsToW986InnerInputCount :
    branchFullDataInputNamesW1169.length <
      canonicalW986InnerUnpackedInputNamesW1299.length
  branchFullDataUnpackedW730W944W973W950InputCount :
    w1007W985TargetClosednessUnpackedInputNamesW1440.length = 4
  branchFullDataW984TargetClosednessInnerInputCount :
    canonicalW984TargetClosednessUnpackedInputNamesW1300.length = 2
  branchFullDataW986InnerUnpackExpandsToW984TargetClosednessInputCount :
    canonicalW986InnerUnpackedInputNamesW1299.length <
      w1007W985TargetClosednessUnpackedInputNamesW1440.length
  branchFullDataBridgeUnpackExpandsToW984TargetClosednessInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W985TargetClosednessUnpackedInputNamesW1440.length
  branchFullDataUnpackedW730W944W973W948W949InputCount :
    w1007W950NormalizedEndpointUnpackedInputNamesW1441.length = 5
  branchFullDataW950NormalizedEndpointInnerInputCount :
    canonicalW950NormalizedEndpointInnerInputNamesW1302.length = 2
  branchFullDataW984TargetClosednessUnpackExpandsToW950NormalizedEndpointInputCount :
    w1007W985TargetClosednessUnpackedInputNamesW1440.length <
      w1007W950NormalizedEndpointUnpackedInputNamesW1441.length
  branchFullDataBridgeUnpackExpandsToW950NormalizedEndpointInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W950NormalizedEndpointUnpackedInputNamesW1441.length
  branchFullDataUnpackedW730W944W973W719W722W949InputCount :
    w1007W948NormalizedSourceUnpackedInputNamesW1442.length = 6
  branchFullDataW948NormalizedSourceInnerInputCount :
    canonicalW948NormalizedSourceTriangulationInnerInputNamesW1303.length = 2
  branchFullDataW950NormalizedEndpointUnpackExpandsToW948NormalizedSourceInputCount :
    w1007W950NormalizedEndpointUnpackedInputNamesW1441.length <
      w1007W948NormalizedSourceUnpackedInputNamesW1442.length
  branchFullDataBridgeUnpackExpandsToW948NormalizedSourceInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W948NormalizedSourceUnpackedInputNamesW1442.length
  branchFullDataUnpackedW730W944W973W719W722EndpointW945InputCount :
    w1007W949EndpointLocalizedUnitUnpackedInputNamesW1443.length = 7
  branchFullDataW949EndpointLocalizedUnitInnerInputCount :
    w1007W949EndpointLocalizedUnitInnerInputNamesW1443.length = 2
  branchFullDataW948NormalizedSourceUnpackExpandsToW949EndpointLocalizedUnitInputCount :
    w1007W948NormalizedSourceUnpackedInputNamesW1442.length <
      w1007W949EndpointLocalizedUnitUnpackedInputNamesW1443.length
  branchFullDataBridgeUnpackExpandsToW949EndpointLocalizedUnitInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W949EndpointLocalizedUnitUnpackedInputNamesW1443.length
  productSuccessClaimed : Bool

/-- The current original-four-task completion witness surface is still nonterminal. -/
def originalFourTaskContractCompletion : OriginalFourTaskContractCompletion where
  targetClosedEmbeddingClosednessInputCount :=
    currentFullDataPayloadFromTargetClosedEmbeddingClosednessInputNamesW1267_count
  normalizedSourceEndpointLocalizedUnitInputCount :=
    currentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitInputNamesW1268_count
  targetNormalizedEndpointInputCount :=
    currentFullDataPayloadFromTargetNormalizedEndpointInputNamesW1269_count
  branchFullDataInputCount :=
    currentFullDataPayloadFromBranchFullDataInputNamesW1270_count
  branchFullDataCurrentFullDataCycleInputCount :=
    branchFullDataCurrentFullDataCycleInputNamesW1271_count
  localizedUnitChoiceBridgeInputCount :=
    w1424ClosedMapLocalizedUnitChoiceFullDataInputCount
  localizedUnitChoiceProjectionInputCount :=
    w1424ClosedMapLocalizedUnitChoiceFullDataInputCount
  localizedUnitChoiceNestedProjectionInputCount :=
    w1430ClosedMapLocalizedUnitChoiceNestedProjectionInputCount
  localizedUnitChoiceDeepProjectionInputCount :=
    w1431ClosedMapLocalizedUnitChoiceDeepProjectionInputCount
  endpointLocalizedUnitBridgeInputCount :=
    w1432ClosedMapEndpointLocalizedUnitInputCount
  normalizedSourceEndpointLocalizedUnitBridgeInputCount :=
    w1433ClosedMapNormalizedSourceEndpointLocalizedUnitInputCount
  targetClosedEmbeddingClosednessBridgeInputCount :=
    w1434ClosedMapTargetClosedEmbeddingClosednessInputCount
  targetClosedEmbeddingClosednessNormalizedSourceEndpointBridgeInputCount :=
    w1435ClosedMapTargetClosedEmbeddingClosednessNormalizedSourceEndpointInputCount
  branchFullDataBridgeInputCount :=
    w1436ClosedMapBranchFullDataInputCount
  branchFullDataUnderlyingW987InputCount :=
    w1437ClosedMapBranchFullDataUnderlyingW987InputCount
  branchFullDataBridgeMatchesW987InputCount :=
    w1169BranchFullDataInputCountMatchesW1007W1437
  branchFullDataBridgeMatchesCurrentPayloadInputCount :=
    w1169BranchFullDataInputCountMatchesW1270W1437
  branchFullDataBridgeMatchesCurrentFullDataCycleInputCount :=
    w1169BranchFullDataInputCountMatchesW1271W1437
  branchFullDataUnpackedW730W986InputCount :=
    w1438BranchFullDataUnpackedW730W986InputCount
  branchFullDataW1007UnpackExpandsInputCount :=
    w1438W1007UnpackExpandsOneInputSurface
  branchFullDataBridgeUnpackExpandsInputCount :=
    w1438W1169UnpackExpandsOneInputSurface
  branchFullDataUnpackedW730W984W950InputCount :=
    w1439BranchFullDataUnpackedW730W984W950InputCount
  branchFullDataW987UnpackExpandsToW986InnerInputCount :=
    w1439W1298UnpackExpandsToW1299
  branchFullDataBridgeUnpackExpandsToW986InnerInputCount :=
    w1439W1169UnpackExpandsToW1299
  branchFullDataUnpackedW730W944W973W950InputCount :=
    w1440BranchFullDataUnpackedW730W944W973W950InputCount
  branchFullDataW984TargetClosednessInnerInputCount :=
    w1440W984TargetClosednessInnerInputCount
  branchFullDataW986InnerUnpackExpandsToW984TargetClosednessInputCount :=
    w1440W1299UnpackExpandsToW984TargetClosedness
  branchFullDataBridgeUnpackExpandsToW984TargetClosednessInputCount :=
    w1440W1169UnpackExpandsToW984TargetClosedness
  branchFullDataUnpackedW730W944W973W948W949InputCount :=
    w1441BranchFullDataUnpackedW730W944W973W948W949InputCount
  branchFullDataW950NormalizedEndpointInnerInputCount :=
    w1441W950NormalizedEndpointInnerInputCount
  branchFullDataW984TargetClosednessUnpackExpandsToW950NormalizedEndpointInputCount :=
    w1441W1440UnpackExpandsToW950NormalizedEndpoint
  branchFullDataBridgeUnpackExpandsToW950NormalizedEndpointInputCount :=
    w1441W1169UnpackExpandsToW950NormalizedEndpoint
  branchFullDataUnpackedW730W944W973W719W722W949InputCount :=
    w1442BranchFullDataUnpackedW730W944W973W719W722W949InputCount
  branchFullDataW948NormalizedSourceInnerInputCount :=
    w1442W948NormalizedSourceInnerInputCount
  branchFullDataW950NormalizedEndpointUnpackExpandsToW948NormalizedSourceInputCount :=
    w1442W1441UnpackExpandsToW948NormalizedSource
  branchFullDataBridgeUnpackExpandsToW948NormalizedSourceInputCount :=
    w1442W1169UnpackExpandsToW948NormalizedSource
  branchFullDataUnpackedW730W944W973W719W722EndpointW945InputCount :=
    w1443BranchFullDataUnpackedW730W944W973W719W722EndpointW945InputCount
  branchFullDataW949EndpointLocalizedUnitInnerInputCount :=
    w1443W949EndpointLocalizedUnitInnerInputCount
  branchFullDataW948NormalizedSourceUnpackExpandsToW949EndpointLocalizedUnitInputCount :=
    w1443W1442UnpackExpandsToW949EndpointLocalizedUnit
  branchFullDataBridgeUnpackExpandsToW949EndpointLocalizedUnitInputCount :=
    w1443W1169UnpackExpandsToW949EndpointLocalizedUnit
  productSuccessClaimed := false

theorem originalFourTaskContractCompletion_productSuccessClaimed :
    originalFourTaskContractCompletion.productSuccessClaimed = false :=
  rfl

end Dbounded
end LeanLCAExactChallenge
