import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromTargetClosedEmbeddingClosednessW1267
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitW1268
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromTargetNormalizedEndpointW1269
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromBranchFullDataW1270
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataBranchFullDataCurrentFullDataCycleGuardW1271
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceFullDataStableConvergenceFieldSplitGuardW1424
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceProjectionStableConvergenceFieldSplitGuardW1425
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceNestedProjectionStableConvergenceFieldSplitGuardW1430
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceDeepProjectionStableConvergenceFieldSplitGuardW1431
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapEndpointLocalizedUnitStableConvergenceFieldSplitGuardW1432
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapNormalizedSourceEndpointLocalizedUnitStableConvergenceFieldSplitGuardW1433
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapTargetClosedEmbeddingClosednessStableConvergenceFieldSplitGuardW1434
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapTargetClosedEmbeddingClosednessNormalizedSourceEndpointStableConvergenceFieldSplitGuardW1435
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataStableConvergenceFieldSplitGuardW1436
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataOneInputCycleGuardW1437
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW987UnpackBoundaryGuardW1438
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW986UnpackBoundaryGuardW1439
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW984TargetClosednessUnpackBoundaryGuardW1440
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW950NormalizedEndpointUnpackBoundaryGuardW1441
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW948NormalizedSourceUnpackBoundaryGuardW1442
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW949EndpointLocalizedUnitUnpackBoundaryGuardW1443
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW945LocalizedUnitUnpackBoundaryGuardW1444
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW990PrimitiveUnitComponentsAlignmentGuardW1445
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW990UnitStrictExactIsoPackagingGuardW1446
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW989LocalizedUnitChoiceFullDataPackagingGuardW1447
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW987RewrapCycleGuardW1448
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW987RewrappedStableRouteGuardW1449
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987FieldDataConstructionGuardW1450
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryFieldDataConstructionGuardW1451
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationFieldDataConstructionGuardW1452
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetFieldDataConstructionGuardW1453
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionGuardW1454
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionGuardW1455
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionGuardW1456
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionGuardW1457
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionGuardW1458
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionGuardW1459
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionGuardW1460
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionGuardW1461
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionGuardW1462
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionGuardW1463
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionGuardW1464

namespace LeanLCAExactChallenge
namespace Dbounded

/-- Current original-four-task completion witness surface audited by the contract gates.

This packages the checked W1267-W1271 route evidence that remains nonterminal:
it records the current reduction counts and explicitly does not claim product
success. -/
structure OriginalFourTaskContractCompletion where
  targetClosedEmbeddingClosednessInputCount :
    currentFullDataPayloadFromTargetClosedEmbeddingClosednessInputNamesW1267.length = 4
  normalizedSourceEndpointLocalizedUnitInputCount :
    currentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitInputNamesW1268.length = 3
  targetNormalizedEndpointInputCount :
    currentFullDataPayloadFromTargetNormalizedEndpointInputNamesW1269.length = 2
  branchFullDataInputCount :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length = 1
  branchFullDataCurrentFullDataCycleInputCount :
    branchFullDataCurrentFullDataCycleInputNamesW1271.length = 1
  localizedUnitChoiceBridgeInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceNestedProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceDeepProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  endpointLocalizedUnitBridgeInputCount :
    endpointLocalizedUnitInputNamesW1165.length = 5
  normalizedSourceEndpointLocalizedUnitBridgeInputCount :
    normalizedSourceEndpointLocalizedUnitInputNamesW1166.length = 4
  targetClosedEmbeddingClosednessBridgeInputCount :
    targetClosedEmbeddingClosednessInputNamesW1167.length = 3
  targetClosedEmbeddingClosednessNormalizedSourceEndpointBridgeInputCount :
    targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1168.length = 2
  branchFullDataBridgeInputCount :
    branchFullDataInputNamesW1169.length = 1
  branchFullDataUnderlyingW987InputCount :
    branchFullDataInputNamesW1007.length = 1
  branchFullDataBridgeMatchesW987InputCount :
    branchFullDataInputNamesW1169.length = branchFullDataInputNamesW1007.length
  branchFullDataBridgeMatchesCurrentPayloadInputCount :
    branchFullDataInputNamesW1169.length =
      currentFullDataPayloadFromBranchFullDataInputNamesW1270.length
  branchFullDataBridgeMatchesCurrentFullDataCycleInputCount :
    branchFullDataInputNamesW1169.length =
      branchFullDataCurrentFullDataCycleInputNamesW1271.length
  branchFullDataUnpackedW730W986InputCount :
    canonicalFullDataUnpackedInputNamesW1298.length = 2
  branchFullDataW1007UnpackExpandsInputCount :
    branchFullDataInputNamesW1007.length <
      canonicalFullDataUnpackedInputNamesW1298.length
  branchFullDataBridgeUnpackExpandsInputCount :
    branchFullDataInputNamesW1169.length <
      canonicalFullDataUnpackedInputNamesW1298.length
  branchFullDataUnpackedW730W984W950InputCount :
    canonicalW986InnerUnpackedInputNamesW1299.length = 3
  branchFullDataW987UnpackExpandsToW986InnerInputCount :
    canonicalFullDataUnpackedInputNamesW1298.length <
      canonicalW986InnerUnpackedInputNamesW1299.length
  branchFullDataBridgeUnpackExpandsToW986InnerInputCount :
    branchFullDataInputNamesW1169.length <
      canonicalW986InnerUnpackedInputNamesW1299.length
  branchFullDataUnpackedW730W944W973W950InputCount :
    w1007W985TargetClosednessUnpackedInputNamesW1440.length = 4
  branchFullDataW984TargetClosednessInnerInputCount :
    canonicalW984TargetClosednessUnpackedInputNamesW1300.length = 2
  branchFullDataW986InnerUnpackExpandsToW984TargetClosednessInputCount :
    canonicalW986InnerUnpackedInputNamesW1299.length <
      w1007W985TargetClosednessUnpackedInputNamesW1440.length
  branchFullDataBridgeUnpackExpandsToW984TargetClosednessInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W985TargetClosednessUnpackedInputNamesW1440.length
  branchFullDataUnpackedW730W944W973W948W949InputCount :
    w1007W950NormalizedEndpointUnpackedInputNamesW1441.length = 5
  branchFullDataW950NormalizedEndpointInnerInputCount :
    canonicalW950NormalizedEndpointInnerInputNamesW1302.length = 2
  branchFullDataW984TargetClosednessUnpackExpandsToW950NormalizedEndpointInputCount :
    w1007W985TargetClosednessUnpackedInputNamesW1440.length <
      w1007W950NormalizedEndpointUnpackedInputNamesW1441.length
  branchFullDataBridgeUnpackExpandsToW950NormalizedEndpointInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W950NormalizedEndpointUnpackedInputNamesW1441.length
  branchFullDataUnpackedW730W944W973W719W722W949InputCount :
    w1007W948NormalizedSourceUnpackedInputNamesW1442.length = 6
  branchFullDataW948NormalizedSourceInnerInputCount :
    canonicalW948NormalizedSourceTriangulationInnerInputNamesW1303.length = 2
  branchFullDataW950NormalizedEndpointUnpackExpandsToW948NormalizedSourceInputCount :
    w1007W950NormalizedEndpointUnpackedInputNamesW1441.length <
      w1007W948NormalizedSourceUnpackedInputNamesW1442.length
  branchFullDataBridgeUnpackExpandsToW948NormalizedSourceInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W948NormalizedSourceUnpackedInputNamesW1442.length
  branchFullDataUnpackedW730W944W973W719W722EndpointW945InputCount :
    w1007W949EndpointLocalizedUnitUnpackedInputNamesW1443.length = 7
  branchFullDataW949EndpointLocalizedUnitInnerInputCount :
    w1007W949EndpointLocalizedUnitInnerInputNamesW1443.length = 2
  branchFullDataW948NormalizedSourceUnpackExpandsToW949EndpointLocalizedUnitInputCount :
    w1007W948NormalizedSourceUnpackedInputNamesW1442.length <
      w1007W949EndpointLocalizedUnitUnpackedInputNamesW1443.length
  branchFullDataBridgeUnpackExpandsToW949EndpointLocalizedUnitInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W949EndpointLocalizedUnitUnpackedInputNamesW1443.length
  branchFullDataUnpackedW730W944W973W719W722EndpointRightAdjointAdjunctionW939InputCount :
    w1007W945LocalizedUnitUnpackedInputNamesW1444.length = 9
  branchFullDataW945LocalizedUnitInnerInputCount :
    canonicalW945LocalizedUnitInnerInputNamesW1306.length = 3
  branchFullDataW949EndpointLocalizedUnitUnpackExpandsToW945LocalizedUnitInputCount :
    w1007W949EndpointLocalizedUnitUnpackedInputNamesW1443.length <
      w1007W945LocalizedUnitUnpackedInputNamesW1444.length
  branchFullDataBridgeUnpackExpandsToW945LocalizedUnitInputCount :
    branchFullDataInputNamesW1169.length <
      w1007W945LocalizedUnitUnpackedInputNamesW1444.length
  branchFullDataW990PrimitiveUnitComponentsInputCount :
    w1007W990PrimitiveUnitComponentsAlignedInputNamesW1445.length = 8
  branchFullDataCanonicalW990PrimitiveUnitComponentsRouteInputCount :
    canonicalW990PrimitiveUnitComponentsInputNamesW1321.length = 8
  branchFullDataW945LocalizedUnitAlignsWithW990PrimitiveUnitComponentsInputCount :
    w1007W990PrimitiveUnitComponentsAlignedInputNamesW1445.length <
      w1007W945LocalizedUnitUnpackedInputNamesW1444.length
  branchFullDataW990UnitStrictExactIsoInputCount :
    w1007W990UnitStrictExactIsoPackagedInputNamesW1446.length = 7
  branchFullDataW981UnitStrictExactIsoDataInputCount :
    unitStrictExactIsoDataInputNamesW981.length = 3
  branchFullDataW990PrimitiveUnitComponentsPackagesToW989InputCount :
    w1007W990UnitStrictExactIsoPackagedInputNamesW1446.length <
      w1007W990PrimitiveUnitComponentsAlignedInputNamesW1445.length
  branchFullDataW989LocalizedUnitChoiceInputCount :
    w1007W989LocalizedUnitChoiceInputNamesW1447.length = 6
  branchFullDataW989UnitStrictExactIsoPackagesToW988InputCount :
    w1007W989LocalizedUnitChoiceInputNamesW1447.length <
      w1007W990UnitStrictExactIsoPackagedInputNamesW1446.length
  branchFullDataW987RewrappedInputCount :
    w1007W987RewrappedInputNamesW1448.length = 1
  branchFullDataW989LocalizedUnitChoicePackagesToW987InputCount :
    w1007W987RewrappedInputNamesW1448.length <
      w1007W989LocalizedUnitChoiceInputNamesW1447.length
  branchFullDataW987RewrappedStableRouteInputCount :
    w1007W987RewrappedInputNamesW1448.length = 1
  branchFullDataW987FieldDataConstructionInputCount :
    w987FieldDataConstructionInputNamesW1450.length = 4
  branchFullDataW987FieldDataConstructionExpandsCurrentProviderInputCount :
    w1007W987RewrappedInputNamesW1448.length <
      w987FieldDataConstructionInputNamesW1450.length
  branchFullDataW987BoundaryFieldDataConstructionInputCount :
    w987BoundaryFieldDataConstructionInputNamesW1451.length = 5
  branchFullDataW987BoundaryFieldDataConstructionBoundaryInputCount :
    w987BoundaryFieldDataConstructionBoundaryInputNamesW1451.length = 2
  branchFullDataW987BoundaryFieldDataConstructionSplitsW716InputCount :
    w987BoundaryFieldDataConstructionBundledBoundaryInputNamesW1451.length <
      w987BoundaryFieldDataConstructionBoundaryInputNamesW1451.length
  branchFullDataW987BoundaryFieldDataConstructionExpandsW1450InputCount :
    w987FieldDataConstructionInputNamesW1450.length <
      w987BoundaryFieldDataConstructionInputNamesW1451.length
  branchFullDataW987BoundaryRelationFieldDataConstructionInputCount :
    w987BoundaryRelationFieldDataConstructionInputNamesW1452.length = 6
  branchFullDataW987BoundaryRelationFieldDataConstructionRelationInputCount :
    w987BoundaryRelationFieldDataConstructionRelationInputNamesW1452.length =
      2
  branchFullDataW987BoundaryRelationFieldDataConstructionSplitsW717InputCount :
    w987BoundaryRelationFieldDataConstructionBundledRelationInputNamesW1452.length <
      w987BoundaryRelationFieldDataConstructionRelationInputNamesW1452.length
  branchFullDataW987BoundaryRelationFieldDataConstructionExpandsW1451InputCount :
    w987BoundaryFieldDataConstructionInputNamesW1451.length <
      w987BoundaryRelationFieldDataConstructionInputNamesW1452.length
  branchFullDataW987BoundaryRelationTargetFieldDataConstructionInputCount :
    w987BoundaryRelationTargetFieldDataConstructionInputNamesW1453.length = 7
  branchFullDataW987BoundaryRelationTargetFieldDataConstructionTargetInputCount :
    w987BoundaryRelationTargetFieldDataConstructionTargetInputNamesW1453.length =
      2
  branchFullDataW987BoundaryRelationTargetFieldDataConstructionSplitsW984InputCount :
    w987BoundaryRelationTargetFieldDataConstructionBundledTargetInputNamesW1453.length <
      w987BoundaryRelationTargetFieldDataConstructionTargetInputNamesW1453.length
  branchFullDataW987BoundaryRelationTargetFieldDataConstructionExpandsW1452InputCount :
    w987BoundaryRelationFieldDataConstructionInputNamesW1452.length <
      w987BoundaryRelationTargetFieldDataConstructionInputNamesW1453.length
  branchFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionInputCount :
    w987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionInputNamesW1454.length =
      8
  branchFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionNormalizedEndpointInputCount :
    w987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionNormalizedEndpointInputNamesW1454.length =
      2
  branchFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionSplitsW950InputCount :
    w987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionBundledNormalizedEndpointInputNamesW1454.length <
      w987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionNormalizedEndpointInputNamesW1454.length
  branchFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionExpandsW1453InputCount :
    w987BoundaryRelationTargetFieldDataConstructionInputNamesW1453.length <
      w987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionInputNamesW1454.length
  branchFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionInputCount :
    w987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionInputNamesW1455.length =
      9
  branchFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionEndpointInputCount :
    w987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionEndpointInputNamesW1455.length =
      2
  branchFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionSplitsW949InputCount :
    w987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionBundledEndpointInputNamesW1455.length <
      w987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionEndpointInputNamesW1455.length
  branchFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionExpandsW1454InputCount :
    w987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionInputNamesW1454.length <
      w987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionInputNamesW1455.length
  branchFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionInputCount :
    w987BoundaryRelationTargetNormalizedSourceFieldDataConstructionInputNamesW1456.length =
      10
  branchFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionNormalizedSourceInputCount :
    w987BoundaryRelationTargetNormalizedSourceFieldDataConstructionNormalizedSourceInputNamesW1456.length =
      2
  branchFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionSplitsW948InputCount :
    w987BoundaryRelationTargetNormalizedSourceFieldDataConstructionBundledNormalizedSourceInputNamesW1456.length <
      w987BoundaryRelationTargetNormalizedSourceFieldDataConstructionNormalizedSourceInputNamesW1456.length
  branchFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionExpandsW1455InputCount :
    w987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionInputNamesW1455.length <
      w987BoundaryRelationTargetNormalizedSourceFieldDataConstructionInputNamesW1456.length
  branchFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionInputCount :
    w987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionInputNamesW1457.length =
      12
  branchFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionFixedTargetInputCount :
    w987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionFixedTargetInputNamesW1457.length =
      3
  branchFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionSplitsW719InputCount :
    w987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionBundledFixedTargetInputNamesW1457.length <
      w987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionFixedTargetInputNamesW1457.length
  branchFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionExpandsW1456InputCount :
    w987BoundaryRelationTargetNormalizedSourceFieldDataConstructionInputNamesW1456.length <
      w987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionInputNamesW1457.length
  branchFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionInputCount :
    w987BoundaryRelationTargetSourceTriangulationFieldDataConstructionInputNamesW1458.length =
      14
  branchFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionSourceTriangulationInputCount :
    w987BoundaryRelationTargetSourceTriangulationFieldDataConstructionSourceTriangulationInputNamesW1458.length =
      3
  branchFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionSplitsW722InputCount :
    w987BoundaryRelationTargetSourceTriangulationFieldDataConstructionBundledSourceTriangulationInputNamesW1458.length <
      w987BoundaryRelationTargetSourceTriangulationFieldDataConstructionSourceTriangulationInputNamesW1458.length
  branchFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionExpandsW1457InputCount :
    w987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionInputNamesW1457.length <
      w987BoundaryRelationTargetSourceTriangulationFieldDataConstructionInputNamesW1458.length
  branchFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionInputCount :
    w987BoundaryRelationTargetLocalizedUnitFieldDataConstructionInputNamesW1459.length =
      16
  branchFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionLocalizedUnitInputCount :
    w987BoundaryRelationTargetLocalizedUnitFieldDataConstructionLocalizedUnitInputNamesW1459.length =
      3
  branchFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionSplitsW945InputCount :
    w987BoundaryRelationTargetLocalizedUnitFieldDataConstructionBundledLocalizedUnitInputNamesW1459.length <
      w987BoundaryRelationTargetLocalizedUnitFieldDataConstructionLocalizedUnitInputNamesW1459.length
  branchFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionExpandsW1458InputCount :
    w987BoundaryRelationTargetSourceTriangulationFieldDataConstructionInputNamesW1458.length <
      w987BoundaryRelationTargetLocalizedUnitFieldDataConstructionInputNamesW1459.length
  branchFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionInputCount :
    w987BoundaryRelationTargetUnitMappingConeFieldDataConstructionInputNamesW1460.length =
      18
  branchFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionUnitMappingConeInputCount :
    w987BoundaryRelationTargetUnitMappingConeFieldDataConstructionUnitMappingConeInputNamesW1460.length =
      3
  branchFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionSplitsW939InputCount :
    w987BoundaryRelationTargetUnitMappingConeFieldDataConstructionBundledUnitComponentInputNamesW1460.length <
      w987BoundaryRelationTargetUnitMappingConeFieldDataConstructionUnitMappingConeInputNamesW1460.length
  branchFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionExpandsW1459InputCount :
    w987BoundaryRelationTargetLocalizedUnitFieldDataConstructionInputNamesW1459.length <
      w987BoundaryRelationTargetUnitMappingConeFieldDataConstructionInputNamesW1460.length
  branchFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionInputCount :
    w987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionInputNamesW1461.length =
      21
  branchFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionCoreInputCount :
    w987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionCoreInputNamesW1461.length =
      4
  branchFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionSplitsAdjunctionInputCount :
    w987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionBundledAdjunctionInputNamesW1461.length <
      w987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionCoreInputNamesW1461.length
  branchFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionExpandsW1460InputCount :
    w987BoundaryRelationTargetUnitMappingConeFieldDataConstructionInputNamesW1460.length <
      w987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionInputNamesW1461.length
  branchFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionInputCount :
    w987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionInputNamesW1462.length =
      24
  branchFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionComponentInputCount :
    w987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionComponentInputNamesW1462.length =
      4
  branchFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionSplitsStrictExactInputCount :
    w987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionStrictExactInputNamesW1462.length <
      w987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionComponentInputNamesW1462.length
  branchFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionExpandsW1461InputCount :
    w987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionInputNamesW1461.length <
      w987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionInputNamesW1462.length
  branchFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionInputCount :
    w987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionInputNamesW1463.length =
      27
  branchFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionComponentInputCount :
    w987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionComponentInputNamesW1463.length =
      4
  branchFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionSplitsStrictExactInputCount :
    w987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionStrictExactInputNamesW1463.length <
      w987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionComponentInputNamesW1463.length
  branchFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionExpandsW1462InputCount :
    w987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionInputNamesW1462.length <
      w987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionInputNamesW1463.length
  branchFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionInputCount :
    w987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionInputNamesW1464.length =
      30
  branchFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionComponentInputCount :
    w987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionComponentInputNamesW1464.length =
      4
  branchFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionSplitsIsoInputCount :
    w987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionIsoInputNamesW1464.length <
      w987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionComponentInputNamesW1464.length
  branchFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionExpandsW1463InputCount :
    w987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionInputNamesW1463.length <
      w987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionInputNamesW1464.length
  productSuccessClaimed : Bool

/-- The current original-four-task completion witness surface is still nonterminal. -/
def originalFourTaskContractCompletion : OriginalFourTaskContractCompletion where
  targetClosedEmbeddingClosednessInputCount :=
    currentFullDataPayloadFromTargetClosedEmbeddingClosednessInputNamesW1267_count
  normalizedSourceEndpointLocalizedUnitInputCount :=
    currentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitInputNamesW1268_count
  targetNormalizedEndpointInputCount :=
    currentFullDataPayloadFromTargetNormalizedEndpointInputNamesW1269_count
  branchFullDataInputCount :=
    currentFullDataPayloadFromBranchFullDataInputNamesW1270_count
  branchFullDataCurrentFullDataCycleInputCount :=
    branchFullDataCurrentFullDataCycleInputNamesW1271_count
  localizedUnitChoiceBridgeInputCount :=
    w1424ClosedMapLocalizedUnitChoiceFullDataInputCount
  localizedUnitChoiceProjectionInputCount :=
    w1424ClosedMapLocalizedUnitChoiceFullDataInputCount
  localizedUnitChoiceNestedProjectionInputCount :=
    w1430ClosedMapLocalizedUnitChoiceNestedProjectionInputCount
  localizedUnitChoiceDeepProjectionInputCount :=
    w1431ClosedMapLocalizedUnitChoiceDeepProjectionInputCount
  endpointLocalizedUnitBridgeInputCount :=
    w1432ClosedMapEndpointLocalizedUnitInputCount
  normalizedSourceEndpointLocalizedUnitBridgeInputCount :=
    w1433ClosedMapNormalizedSourceEndpointLocalizedUnitInputCount
  targetClosedEmbeddingClosednessBridgeInputCount :=
    w1434ClosedMapTargetClosedEmbeddingClosednessInputCount
  targetClosedEmbeddingClosednessNormalizedSourceEndpointBridgeInputCount :=
    w1435ClosedMapTargetClosedEmbeddingClosednessNormalizedSourceEndpointInputCount
  branchFullDataBridgeInputCount :=
    w1436ClosedMapBranchFullDataInputCount
  branchFullDataUnderlyingW987InputCount :=
    w1437ClosedMapBranchFullDataUnderlyingW987InputCount
  branchFullDataBridgeMatchesW987InputCount :=
    w1169BranchFullDataInputCountMatchesW1007W1437
  branchFullDataBridgeMatchesCurrentPayloadInputCount :=
    w1169BranchFullDataInputCountMatchesW1270W1437
  branchFullDataBridgeMatchesCurrentFullDataCycleInputCount :=
    w1169BranchFullDataInputCountMatchesW1271W1437
  branchFullDataUnpackedW730W986InputCount :=
    w1438BranchFullDataUnpackedW730W986InputCount
  branchFullDataW1007UnpackExpandsInputCount :=
    w1438W1007UnpackExpandsOneInputSurface
  branchFullDataBridgeUnpackExpandsInputCount :=
    w1438W1169UnpackExpandsOneInputSurface
  branchFullDataUnpackedW730W984W950InputCount :=
    w1439BranchFullDataUnpackedW730W984W950InputCount
  branchFullDataW987UnpackExpandsToW986InnerInputCount :=
    w1439W1298UnpackExpandsToW1299
  branchFullDataBridgeUnpackExpandsToW986InnerInputCount :=
    w1439W1169UnpackExpandsToW1299
  branchFullDataUnpackedW730W944W973W950InputCount :=
    w1440BranchFullDataUnpackedW730W944W973W950InputCount
  branchFullDataW984TargetClosednessInnerInputCount :=
    w1440W984TargetClosednessInnerInputCount
  branchFullDataW986InnerUnpackExpandsToW984TargetClosednessInputCount :=
    w1440W1299UnpackExpandsToW984TargetClosedness
  branchFullDataBridgeUnpackExpandsToW984TargetClosednessInputCount :=
    w1440W1169UnpackExpandsToW984TargetClosedness
  branchFullDataUnpackedW730W944W973W948W949InputCount :=
    w1441BranchFullDataUnpackedW730W944W973W948W949InputCount
  branchFullDataW950NormalizedEndpointInnerInputCount :=
    w1441W950NormalizedEndpointInnerInputCount
  branchFullDataW984TargetClosednessUnpackExpandsToW950NormalizedEndpointInputCount :=
    w1441W1440UnpackExpandsToW950NormalizedEndpoint
  branchFullDataBridgeUnpackExpandsToW950NormalizedEndpointInputCount :=
    w1441W1169UnpackExpandsToW950NormalizedEndpoint
  branchFullDataUnpackedW730W944W973W719W722W949InputCount :=
    w1442BranchFullDataUnpackedW730W944W973W719W722W949InputCount
  branchFullDataW948NormalizedSourceInnerInputCount :=
    w1442W948NormalizedSourceInnerInputCount
  branchFullDataW950NormalizedEndpointUnpackExpandsToW948NormalizedSourceInputCount :=
    w1442W1441UnpackExpandsToW948NormalizedSource
  branchFullDataBridgeUnpackExpandsToW948NormalizedSourceInputCount :=
    w1442W1169UnpackExpandsToW948NormalizedSource
  branchFullDataUnpackedW730W944W973W719W722EndpointW945InputCount :=
    w1443BranchFullDataUnpackedW730W944W973W719W722EndpointW945InputCount
  branchFullDataW949EndpointLocalizedUnitInnerInputCount :=
    w1443W949EndpointLocalizedUnitInnerInputCount
  branchFullDataW948NormalizedSourceUnpackExpandsToW949EndpointLocalizedUnitInputCount :=
    w1443W1442UnpackExpandsToW949EndpointLocalizedUnit
  branchFullDataBridgeUnpackExpandsToW949EndpointLocalizedUnitInputCount :=
    w1443W1169UnpackExpandsToW949EndpointLocalizedUnit
  branchFullDataUnpackedW730W944W973W719W722EndpointRightAdjointAdjunctionW939InputCount :=
    w1444BranchFullDataUnpackedW730W944W973W719W722EndpointRightAdjointAdjunctionW939InputCount
  branchFullDataW945LocalizedUnitInnerInputCount :=
    w1444W945LocalizedUnitInnerInputCount
  branchFullDataW949EndpointLocalizedUnitUnpackExpandsToW945LocalizedUnitInputCount :=
    w1444W1443UnpackExpandsToW945LocalizedUnit
  branchFullDataBridgeUnpackExpandsToW945LocalizedUnitInputCount :=
    w1444W1169UnpackExpandsToW945LocalizedUnit
  branchFullDataW990PrimitiveUnitComponentsInputCount :=
    w1445BranchFullDataW990PrimitiveUnitComponentsInputCount
  branchFullDataCanonicalW990PrimitiveUnitComponentsRouteInputCount :=
    w1445CanonicalW990PrimitiveUnitComponentsRouteInputCount
  branchFullDataW945LocalizedUnitAlignsWithW990PrimitiveUnitComponentsInputCount :=
    w1445W1444SurfaceAlignsWithW990PrimitiveUnitComponents
  branchFullDataW990UnitStrictExactIsoInputCount :=
    w1446W989UnitStrictExactIsoInputCount
  branchFullDataW981UnitStrictExactIsoDataInputCount :=
    w1446W981UnitStrictExactIsoDataInputCount
  branchFullDataW990PrimitiveUnitComponentsPackagesToW989InputCount :=
    w1446W990PrimitiveUnitComponentsPackagesToW989UnitStrictExactIso
  branchFullDataW989LocalizedUnitChoiceInputCount :=
    w1447W988LocalizedUnitChoiceInputCount
  branchFullDataW989UnitStrictExactIsoPackagesToW988InputCount :=
    w1447W989UnitStrictExactIsoPackagesToW988LocalizedUnitChoice
  branchFullDataW987RewrappedInputCount :=
    w1448W987RewrappedInputCount
  branchFullDataW989LocalizedUnitChoicePackagesToW987InputCount :=
    w1448W989LocalizedUnitChoicePackagesToW987FullData
  branchFullDataW987RewrappedStableRouteInputCount :=
    w1449W987RewrappedStableRouteInputCount
  branchFullDataW987FieldDataConstructionInputCount :=
    w987FieldDataConstructionInputNamesW1450_count
  branchFullDataW987FieldDataConstructionExpandsCurrentProviderInputCount :=
    w1450W987FieldDataConstructionExpandsCurrentProvider
  branchFullDataW987BoundaryFieldDataConstructionInputCount :=
    w987BoundaryFieldDataConstructionInputNamesW1451_count
  branchFullDataW987BoundaryFieldDataConstructionBoundaryInputCount :=
    w987BoundaryFieldDataConstructionBoundaryInputNamesW1451_count
  branchFullDataW987BoundaryFieldDataConstructionSplitsW716InputCount :=
    w1451BoundaryFieldDataConstructionSplitsW716Input
  branchFullDataW987BoundaryFieldDataConstructionExpandsW1450InputCount :=
    w1451BoundaryFieldDataConstructionExpandsW1450InputCount
  branchFullDataW987BoundaryRelationFieldDataConstructionInputCount :=
    w987BoundaryRelationFieldDataConstructionInputNamesW1452_count
  branchFullDataW987BoundaryRelationFieldDataConstructionRelationInputCount :=
    w987BoundaryRelationFieldDataConstructionRelationInputNamesW1452_count
  branchFullDataW987BoundaryRelationFieldDataConstructionSplitsW717InputCount :=
    w1452BoundaryRelationFieldDataConstructionSplitsW717Input
  branchFullDataW987BoundaryRelationFieldDataConstructionExpandsW1451InputCount :=
    w1452BoundaryRelationFieldDataConstructionExpandsW1451InputCount
  branchFullDataW987BoundaryRelationTargetFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetFieldDataConstructionInputNamesW1453_count
  branchFullDataW987BoundaryRelationTargetFieldDataConstructionTargetInputCount :=
    w987BoundaryRelationTargetFieldDataConstructionTargetInputNamesW1453_count
  branchFullDataW987BoundaryRelationTargetFieldDataConstructionSplitsW984InputCount :=
    w1453BoundaryRelationTargetFieldDataConstructionSplitsW984Input
  branchFullDataW987BoundaryRelationTargetFieldDataConstructionExpandsW1452InputCount :=
    w1453BoundaryRelationTargetFieldDataConstructionExpandsW1452InputCount
  branchFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionInputNamesW1454_count
  branchFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionNormalizedEndpointInputCount :=
    w987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionNormalizedEndpointInputNamesW1454_count
  branchFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionSplitsW950InputCount :=
    w1454BoundaryRelationTargetNormalizedEndpointFieldDataConstructionSplitsW950Input
  branchFullDataW987BoundaryRelationTargetNormalizedEndpointFieldDataConstructionExpandsW1453InputCount :=
    w1454BoundaryRelationTargetNormalizedEndpointFieldDataConstructionExpandsW1453InputCount
  branchFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionInputNamesW1455_count
  branchFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionEndpointInputCount :=
    w987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionEndpointInputNamesW1455_count
  branchFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionSplitsW949InputCount :=
    w1455BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionSplitsW949Input
  branchFullDataW987BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionExpandsW1454InputCount :=
    w1455BoundaryRelationTargetEndpointLocalizedUnitFieldDataConstructionExpandsW1454InputCount
  branchFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetNormalizedSourceFieldDataConstructionInputNamesW1456_count
  branchFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionNormalizedSourceInputCount :=
    w987BoundaryRelationTargetNormalizedSourceFieldDataConstructionNormalizedSourceInputNamesW1456_count
  branchFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionSplitsW948InputCount :=
    w1456BoundaryRelationTargetNormalizedSourceFieldDataConstructionSplitsW948Input
  branchFullDataW987BoundaryRelationTargetNormalizedSourceFieldDataConstructionExpandsW1455InputCount :=
    w1456BoundaryRelationTargetNormalizedSourceFieldDataConstructionExpandsW1455InputCount
  branchFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionInputNamesW1457_count
  branchFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionFixedTargetInputCount :=
    w987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionFixedTargetInputNamesW1457_count
  branchFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionSplitsW719InputCount :=
    w1457BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionSplitsW719Input
  branchFullDataW987BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionExpandsW1456InputCount :=
    w1457BoundaryRelationTargetNormalizedFixedTargetFieldDataConstructionExpandsW1456InputCount
  branchFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetSourceTriangulationFieldDataConstructionInputNamesW1458_count
  branchFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionSourceTriangulationInputCount :=
    w987BoundaryRelationTargetSourceTriangulationFieldDataConstructionSourceTriangulationInputNamesW1458_count
  branchFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionSplitsW722InputCount :=
    w1458BoundaryRelationTargetSourceTriangulationFieldDataConstructionSplitsW722Input
  branchFullDataW987BoundaryRelationTargetSourceTriangulationFieldDataConstructionExpandsW1457InputCount :=
    w1458BoundaryRelationTargetSourceTriangulationFieldDataConstructionExpandsW1457InputCount
  branchFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetLocalizedUnitFieldDataConstructionInputNamesW1459_count
  branchFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionLocalizedUnitInputCount :=
    w987BoundaryRelationTargetLocalizedUnitFieldDataConstructionLocalizedUnitInputNamesW1459_count
  branchFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionSplitsW945InputCount :=
    w1459BoundaryRelationTargetLocalizedUnitFieldDataConstructionSplitsW945Input
  branchFullDataW987BoundaryRelationTargetLocalizedUnitFieldDataConstructionExpandsW1458InputCount :=
    w1459BoundaryRelationTargetLocalizedUnitFieldDataConstructionExpandsW1458InputCount
  branchFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetUnitMappingConeFieldDataConstructionInputNamesW1460_count
  branchFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionUnitMappingConeInputCount :=
    w987BoundaryRelationTargetUnitMappingConeFieldDataConstructionUnitMappingConeInputNamesW1460_count
  branchFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionSplitsW939InputCount :=
    w1460BoundaryRelationTargetUnitMappingConeFieldDataConstructionSplitsW939Input
  branchFullDataW987BoundaryRelationTargetUnitMappingConeFieldDataConstructionExpandsW1459InputCount :=
    w1460BoundaryRelationTargetUnitMappingConeFieldDataConstructionExpandsW1459InputCount
  branchFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionInputNamesW1461_count
  branchFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionCoreInputCount :=
    w987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionCoreInputNamesW1461_count
  branchFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionSplitsAdjunctionInputCount :=
    w1461BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionSplitsAdjunctionInput
  branchFullDataW987BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionExpandsW1460InputCount :=
    w1461BoundaryRelationTargetLocalizedAdjunctionCoreFieldDataConstructionExpandsW1460InputCount
  branchFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionInputNamesW1462_count
  branchFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionComponentInputCount :=
    w987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionComponentInputNamesW1462_count
  branchFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionSplitsStrictExactInputCount :=
    w1462BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionSplitsStrictExactInput
  branchFullDataW987BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionExpandsW1461InputCount :=
    w1462BoundaryRelationTargetUnitKernelCokernelTopFieldDataConstructionExpandsW1461InputCount
  branchFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionInputNamesW1463_count
  branchFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionComponentInputCount :=
    w987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionComponentInputNamesW1463_count
  branchFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionSplitsStrictExactInputCount :=
    w1463BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionSplitsStrictExactInput
  branchFullDataW987BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionExpandsW1462InputCount :=
    w1463BoundaryRelationTargetEndpointKernelCokernelTopFieldDataConstructionExpandsW1462InputCount
  branchFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionInputCount :=
    w987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionInputNamesW1464_count
  branchFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionComponentInputCount :=
    w987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionComponentInputNamesW1464_count
  branchFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionSplitsIsoInputCount :=
    w1464BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionSplitsIsoInput
  branchFullDataW987BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionExpandsW1463InputCount :=
    w1464BoundaryRelationTargetUnitIsoHomInvFieldDataConstructionExpandsW1463InputCount
  productSuccessClaimed := false

theorem originalFourTaskContractCompletion_productSuccessClaimed :
    originalFourTaskContractCompletion.productSuccessClaimed = false :=
  rfl

end Dbounded
end LeanLCAExactChallenge
