import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromTargetClosedEmbeddingClosednessW1267
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitW1268
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromTargetNormalizedEndpointW1269
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataCurrentFullDataPayloadFromBranchFullDataW1270
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataBranchFullDataCurrentFullDataCycleGuardW1271
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceFullDataStableConvergenceFieldSplitGuardW1424
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceProjectionStableConvergenceFieldSplitGuardW1425
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceNestedProjectionStableConvergenceFieldSplitGuardW1430
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapLocalizedUnitChoiceDeepProjectionStableConvergenceFieldSplitGuardW1431
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapEndpointLocalizedUnitStableConvergenceFieldSplitGuardW1432
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapNormalizedSourceEndpointLocalizedUnitStableConvergenceFieldSplitGuardW1433
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapTargetClosedEmbeddingClosednessStableConvergenceFieldSplitGuardW1434
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapTargetClosedEmbeddingClosednessNormalizedSourceEndpointStableConvergenceFieldSplitGuardW1435
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataStableConvergenceFieldSplitGuardW1436
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataOneInputCycleGuardW1437
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW987UnpackBoundaryGuardW1438
import LeanLCAExactChallenge.Derived.ClosedMapBoundaryRelationTargetSurjectiveCompactClosedEmbeddingClosednessNormalizedSourceEndpointLocalizedUnitFullDataClosedMapBranchFullDataW986UnpackBoundaryGuardW1439

namespace LeanLCAExactChallenge
namespace Dbounded

/-- Current original-four-task completion witness surface audited by the contract gates.

This packages the checked W1267-W1271 route evidence that remains nonterminal:
it records the current reduction counts and explicitly does not claim product
success. -/
structure OriginalFourTaskContractCompletion where
  targetClosedEmbeddingClosednessInputCount :
    currentFullDataPayloadFromTargetClosedEmbeddingClosednessInputNamesW1267.length = 4
  normalizedSourceEndpointLocalizedUnitInputCount :
    currentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitInputNamesW1268.length = 3
  targetNormalizedEndpointInputCount :
    currentFullDataPayloadFromTargetNormalizedEndpointInputNamesW1269.length = 2
  branchFullDataInputCount :
    currentFullDataPayloadFromBranchFullDataInputNamesW1270.length = 1
  branchFullDataCurrentFullDataCycleInputCount :
    branchFullDataCurrentFullDataCycleInputNamesW1271.length = 1
  localizedUnitChoiceBridgeInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceNestedProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  localizedUnitChoiceDeepProjectionInputCount :
    localizedUnitChoiceInputNamesW1164.length = 6
  endpointLocalizedUnitBridgeInputCount :
    endpointLocalizedUnitInputNamesW1165.length = 5
  normalizedSourceEndpointLocalizedUnitBridgeInputCount :
    normalizedSourceEndpointLocalizedUnitInputNamesW1166.length = 4
  targetClosedEmbeddingClosednessBridgeInputCount :
    targetClosedEmbeddingClosednessInputNamesW1167.length = 3
  targetClosedEmbeddingClosednessNormalizedSourceEndpointBridgeInputCount :
    targetClosedEmbeddingClosednessNormalizedSourceEndpointInputNamesW1168.length = 2
  branchFullDataBridgeInputCount :
    branchFullDataInputNamesW1169.length = 1
  branchFullDataUnderlyingW987InputCount :
    branchFullDataInputNamesW1007.length = 1
  branchFullDataBridgeMatchesW987InputCount :
    branchFullDataInputNamesW1169.length = branchFullDataInputNamesW1007.length
  branchFullDataBridgeMatchesCurrentPayloadInputCount :
    branchFullDataInputNamesW1169.length =
      currentFullDataPayloadFromBranchFullDataInputNamesW1270.length
  branchFullDataBridgeMatchesCurrentFullDataCycleInputCount :
    branchFullDataInputNamesW1169.length =
      branchFullDataCurrentFullDataCycleInputNamesW1271.length
  branchFullDataUnpackedW730W986InputCount :
    canonicalFullDataUnpackedInputNamesW1298.length = 2
  branchFullDataW1007UnpackExpandsInputCount :
    branchFullDataInputNamesW1007.length <
      canonicalFullDataUnpackedInputNamesW1298.length
  branchFullDataBridgeUnpackExpandsInputCount :
    branchFullDataInputNamesW1169.length <
      canonicalFullDataUnpackedInputNamesW1298.length
  branchFullDataUnpackedW730W984W950InputCount :
    canonicalW986InnerUnpackedInputNamesW1299.length = 3
  branchFullDataW987UnpackExpandsToW986InnerInputCount :
    canonicalFullDataUnpackedInputNamesW1298.length <
      canonicalW986InnerUnpackedInputNamesW1299.length
  branchFullDataBridgeUnpackExpandsToW986InnerInputCount :
    branchFullDataInputNamesW1169.length <
      canonicalW986InnerUnpackedInputNamesW1299.length
  productSuccessClaimed : Bool

/-- The current original-four-task completion witness surface is still nonterminal. -/
def originalFourTaskContractCompletion : OriginalFourTaskContractCompletion where
  targetClosedEmbeddingClosednessInputCount :=
    currentFullDataPayloadFromTargetClosedEmbeddingClosednessInputNamesW1267_count
  normalizedSourceEndpointLocalizedUnitInputCount :=
    currentFullDataPayloadFromNormalizedSourceEndpointLocalizedUnitInputNamesW1268_count
  targetNormalizedEndpointInputCount :=
    currentFullDataPayloadFromTargetNormalizedEndpointInputNamesW1269_count
  branchFullDataInputCount :=
    currentFullDataPayloadFromBranchFullDataInputNamesW1270_count
  branchFullDataCurrentFullDataCycleInputCount :=
    branchFullDataCurrentFullDataCycleInputNamesW1271_count
  localizedUnitChoiceBridgeInputCount :=
    w1424ClosedMapLocalizedUnitChoiceFullDataInputCount
  localizedUnitChoiceProjectionInputCount :=
    w1424ClosedMapLocalizedUnitChoiceFullDataInputCount
  localizedUnitChoiceNestedProjectionInputCount :=
    w1430ClosedMapLocalizedUnitChoiceNestedProjectionInputCount
  localizedUnitChoiceDeepProjectionInputCount :=
    w1431ClosedMapLocalizedUnitChoiceDeepProjectionInputCount
  endpointLocalizedUnitBridgeInputCount :=
    w1432ClosedMapEndpointLocalizedUnitInputCount
  normalizedSourceEndpointLocalizedUnitBridgeInputCount :=
    w1433ClosedMapNormalizedSourceEndpointLocalizedUnitInputCount
  targetClosedEmbeddingClosednessBridgeInputCount :=
    w1434ClosedMapTargetClosedEmbeddingClosednessInputCount
  targetClosedEmbeddingClosednessNormalizedSourceEndpointBridgeInputCount :=
    w1435ClosedMapTargetClosedEmbeddingClosednessNormalizedSourceEndpointInputCount
  branchFullDataBridgeInputCount :=
    w1436ClosedMapBranchFullDataInputCount
  branchFullDataUnderlyingW987InputCount :=
    w1437ClosedMapBranchFullDataUnderlyingW987InputCount
  branchFullDataBridgeMatchesW987InputCount :=
    w1169BranchFullDataInputCountMatchesW1007W1437
  branchFullDataBridgeMatchesCurrentPayloadInputCount :=
    w1169BranchFullDataInputCountMatchesW1270W1437
  branchFullDataBridgeMatchesCurrentFullDataCycleInputCount :=
    w1169BranchFullDataInputCountMatchesW1271W1437
  branchFullDataUnpackedW730W986InputCount :=
    w1438BranchFullDataUnpackedW730W986InputCount
  branchFullDataW1007UnpackExpandsInputCount :=
    w1438W1007UnpackExpandsOneInputSurface
  branchFullDataBridgeUnpackExpandsInputCount :=
    w1438W1169UnpackExpandsOneInputSurface
  branchFullDataUnpackedW730W984W950InputCount :=
    w1439BranchFullDataUnpackedW730W984W950InputCount
  branchFullDataW987UnpackExpandsToW986InnerInputCount :=
    w1439W1298UnpackExpandsToW1299
  branchFullDataBridgeUnpackExpandsToW986InnerInputCount :=
    w1439W1169UnpackExpandsToW1299
  productSuccessClaimed := false

theorem originalFourTaskContractCompletion_productSuccessClaimed :
    originalFourTaskContractCompletion.productSuccessClaimed = false :=
  rfl

end Dbounded
end LeanLCAExactChallenge
