import LeanLCAExactChallenge.Derived.W987NormalizedLiftBlueprintFieldsComparisonGuardW1503
import LeanLCAExactChallenge.Derived.StrictRepresentativeLiftFieldsComparisonStableExactAtRoute

/-!
W1504 feeds the W1503/W1498 surface through the W890 explicit
strict-representative-lift-fields comparison route. W1498 recovered W719
normalized fixed-target data from W948; W1504 exposes the object, map,
identity, and composition fields of its strict-representative lift blueprint
and checks that W890 rebuilds the same W889 normalized lift-blueprint leaves
reached by W1503.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace LeanLCAExactChallenge

open CategoryTheory
open CategoryTheory.Limits
open Topology
open DirectWppLimitFiniteShapeTransfer
open WppOpW426W318LegCompatibilityAlignmentV370SupportW439
open WppOpSelectedW461TransportedPointIsoProviderV370SupportW506
open WppOpClosedNatTransOrdinaryRelationTopologyV370SupportW511
open WppOpClosedNatTransOrdinaryRelationFieldsV370SupportW512
open WppOpW461BridgeComponentwiseClosedRangeProjectionV370SupportW481
open WppOpClosedRangeOnlyComponentwiseProjectionV370SupportW484
open WppOpClosedRangeMappedCokernelPreservationV370SupportW519

namespace Dbounded

noncomputable section

/-- W1504 reuses the W1503 74-field normalized lift-blueprint comparison surface. -/
abbrev W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504 :
    Type 2 :=
  W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedLiftBlueprintFieldsComparisonInputW1503

/-- W1504 assembles the W890 explicit strict-representative lift leaves from W1498 data. -/
def strictRepresentativeLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    MetrizableWppStrictRepresentativeLiftBlueprintFieldLeavesW890 where
  boundaryData :=
    (boundaryRelationDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).boundaryData
  relationData :=
    (boundaryRelationDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).relationData
  targetSurjectiveCompactForTargetProvider :=
    targetSurjectiveCompactDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input
  diagramAndMappedCokernelClosednessData :=
    diagramAndMappedCokernelClosednessDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input
  strictRepresentativeObjectData :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).normalizedLiftBlueprint.blueprint.objData
  strictRepresentativeMapData :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).normalizedLiftBlueprint.blueprint.mapData
  strictRepresentativeMapId :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).normalizedLiftBlueprint.blueprint.map_id
  strictRepresentativeMapComp :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).normalizedLiftBlueprint.blueprint.map_comp
  sourceImageObjectNormalization :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).normalizedLiftBlueprint.obj_image
  sourceImageMapNormalization :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).normalizedLiftBlueprint.map_image
  targetFixedTargetUniq :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).targetFixedTargetUniq
  localizationModelFixedTargetUniq :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).localizationModelFixedTargetUniq
  sourcePretriangulated := input.sourcePretriangulated
  sourceTriangulated := input.sourceTriangulated
  triangleCompletion := input.triangleCompletion
  endpointForgetPreservesHomology :=
    endpointForgetPreservesHomologyOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3EndpointFieldsComparisonW1500
      input
  endpointClosedEmbedding :=
    (endpointTopologyFactsOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).endpointClosedEmbedding
  endpointOpenMap :=
    (endpointTopologyFactsOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).endpointOpenMap
  endpointEpiOfExactAt :=
    (endpointTopologyFactsOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).endpointEpiOfExactAt
  boundedHomotopyLocalizedRightAdjoint :=
    (localizedRightAdjointDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).boundedHomotopyLocalizedRightAdjoint
  boundedHomotopyLocalizedAdjunction :=
    (localizedRightAdjointDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).boundedHomotopyLocalizedAdjunction
  boundedHomotopyLocalizedUnitMem :=
    (localizedRightAdjointDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).boundedHomotopyLocalizedUnitMem

/-- W1504 rebuilds the strict-representative lift blueprint through W890 fields. -/
def strictRepresentativeLiftBlueprintOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    Dbounded.MetrizableWalkingParallelPairLiftBlueprint :=
  strictRepresentativeLiftBlueprintOfFieldsW890
    (strictRepresentativeLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1504
      input)

/-- W1504 rebuilds W889 normalized lift-blueprint leaves through W890 fields. -/
def normalizedLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    MetrizableWppNormalizedLiftBlueprintFieldLeavesW889 :=
  normalizedLiftBlueprintFieldLeavesOfStrictRepresentativeFieldsW890
    (strictRepresentativeLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1504
      input)

/-- W1504 rebuilds the normalized lift blueprint after the W890 decomposition. -/
def normalizedLiftBlueprintOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    Dbounded.MetrizableWalkingParallelPairNormalizedLiftBlueprint :=
  normalizedLiftBlueprintOfFieldsW889
    (normalizedLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
      input)

/-- W1504 rebuilds W888 normalized fixed-target leaves through W890 fields. -/
def normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    MetrizableWppNormalizedFixedTargetFieldLeavesW888 :=
  normalizedFixedTargetFieldLeavesOfNormalizedLiftBlueprintFieldsW889
    (normalizedLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
      input)

/-- W1504 rebuilds W719 normalized fixed-target data after the W890 decomposition. -/
def normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    MetrizableWppNormalizedFixedTargetDataProviderW719 :=
  normalizedFixedTargetDataOfFieldsW888
    (normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
      input)

/-- W1504 rebuilds W887 localized-right-adjoint leaves through W890 fields. -/
def localizedRightAdjointFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    MetrizableWppLocalizedRightAdjointFieldLeavesW887 :=
  localizedRightAdjointFieldLeavesOfNormalizedFixedTargetFieldsW888
    (normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
      input)

/-- W1504 exposes W890's concrete leaves. -/
def concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    MetrizableWppBoundaryRelationTargetClosednessNormalizedConcreteLeavesW733 :=
  concreteLeavesOfStrictRepresentativeFieldsComparisonW890
    (strictRepresentativeLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1504
      input)

/-- W1504 exposes W890's W732 route data. -/
def routeDataProviderOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    MetrizableWppBoundaryRelationTargetClosednessNormalizedDataProviderW732 :=
  routeDataProviderOfStrictRepresentativeFieldsComparisonW890
    (strictRepresentativeLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1504
      input)

/-- W1504 feeds W890 explicit strict-representative lift fields to direct bounded left calculus. -/
theorem directBoundedLeftCalculusOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    (boundedExactWeakEquivalence MetrizableLCA.{0}).HasLeftCalculusOfFractions :=
  directBoundedLeftCalculusOfStrictRepresentativeFieldsComparisonStableExactAtW890
    (strictRepresentativeLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1504
      input)

/-- W1504 exposes W890's bounded derived infinity-category package. -/
def boundedDerivedInfinityCategoryOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    BoundedDerivedInfinityCategory MetrizableLCA.{0}
      (Dbounded.infinityCategory MetrizableLCA.{0}) :=
  boundedDerivedInfinityCategoryOfStrictRepresentativeFieldsComparisonStableExactAtW890
    (strictRepresentativeLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1504
      input)

/-- W1504's W890 strict-representative blueprint is definitionally W1498's blueprint. -/
theorem w1504StrictRepresentativeLiftBlueprintMatchesW1498
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    strictRepresentativeLiftBlueprintOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
        input =
      (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
        input).normalizedLiftBlueprint.blueprint :=
  rfl

/-- W1504's W890-to-W889 leaves are definitionally W1503's W889 leaves. -/
theorem w1504NormalizedLiftBlueprintFieldLeavesMatchW1503
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    normalizedLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
        input =
      normalizedLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1503
        input :=
  rfl

/-- W1504's W890 concrete leaves are definitionally W1503's W889 concrete leaves. -/
theorem w1504ConcreteLeavesMatchW1503
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504) :
    concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504
        input =
      concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedLiftBlueprintFieldsComparisonW1503
        input :=
  rfl

/-- W1504 keeps the W1503 constructor-ledger input names. -/
def w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputNamesW1504 :
    List String :=
  w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedLiftBlueprintFieldsComparisonInputNamesW1503

theorem w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputNamesW1504_count :
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputNamesW1504.length =
      74 := by
  simpa [
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputNamesW1504]
    using
      w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedLiftBlueprintFieldsComparisonInputNamesW1503_count

/-- Current W1504 nonterminal explicit strict-representative-lift-fields route state. -/
structure W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonStateW1504 :
    Type where
  seed : String
  declarations : List String
  strictRepresentativeLiftFieldAssemblyResult : String
  comparisonResult : String
  remainingInputs : List String
  productSuccessClaimed : Bool

/-- W1504 records the W890 explicit strict-representative-lift route reached from W1503. -/
def currentW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonStateW1504 :
    W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonStateW1504 where
  seed :=
    "w1504-w987-boundary-relation-target-strict-preimage-object-image-right-adjoint-target-compactness-mapped-cokernel-pi1-pi2-pi3-strict-representative-lift-fields-comparison"
  declarations :=
    ["W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputW1504",
      "strictRepresentativeLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1504",
      "strictRepresentativeLiftBlueprintOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "normalizedLiftBlueprintFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "normalizedLiftBlueprintOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "localizedRightAdjointFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "routeDataProviderOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "directBoundedLeftCalculusOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "boundedDerivedInfinityCategoryOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonW1504",
      "w1504StrictRepresentativeLiftBlueprintMatchesW1498",
      "w1504NormalizedLiftBlueprintFieldLeavesMatchW1503",
      "w1504ConcreteLeavesMatchW1503",
      "w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputNamesW1504_count"]
  strictRepresentativeLiftFieldAssemblyResult :=
    "proved: W1498's W948 normalized-source branch supplies the four explicit\
      W890 strict-representative lift fields"
  comparisonResult :=
    "proved: W1504's W890 strict-representative-lift-field route rebuilds the\
      same W889 normalized lift-blueprint leaves and concrete leaves reached by W1503"
  remainingInputs :=
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonInputNamesW1504
  productSuccessClaimed := false

theorem currentW1504W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparison_productSuccess :
    currentW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictRepresentativeLiftFieldsComparisonStateW1504.productSuccessClaimed =
      false :=
  rfl

end

end Dbounded

end LeanLCAExactChallenge
