/-
Copyright (c) 2026 Rokurolize. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rokurolize
-/

import LeanLCAExactChallenge.Infinity.CoherentNerveMappingComparison
import LeanLCAExactChallenge.Infinity.NerveRetractInternalHom

/-! # The extraction path category as a categorical deformation retract

The top prism used by coherent-Hom extraction has one nonzero interval vertex. Its path category
therefore retracts onto the ordered set of source coordinates by selecting the last zero vertex.
This identifies functor quasicategories out of the two indexing categories for every Kan target.
-/

set_option autoImplicit false

noncomputable section

universe u

namespace LeanLCAExactChallenge.Infinity.CoherentNerveMappingComparison

open CategoryTheory Opposite Simplicial
open scoped Bicategory MonoidalCategory MonoidalClosed

/-- The source coordinate selected by the last zero vertex of one extraction path. -/
def extractionLastZeroCoordinate (n : ℕ)
    (P : extractionFirst.{u} n ⟶ extractionLast.{u} n) : Fin (n + 1) :=
  ⟨(lastZero (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl P).down.val, by
    have hzero :=
      (lastZero_mem (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl P).2
    change (if (lastZero
      (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl P).down.val = n + 1
        then 1 else 0) = 0 at hzero
    split at hzero
    · omega
    · omega⟩

/-- The canonical increasing path attached to one source coordinate. -/
def extractionPathFunctor (n : ℕ) :
    CoherentOrdinal.{u} n ⥤ (extractionFirst.{u} n ⟶ extractionLast.{u} n) where
  obj a := extractionPath.{u} a.down
  map {a b} f :=
    ⟨⟨⟨(extractionPathChain.{u} n).monotone'
      (show a.down ≤ b.down by simpa using (leOfHom f))⟩⟩⟩
  map_id a :=
    (CoherentNervePathFiltration.Path.thickPathHomSubsingleton
      (extractionPath.{u} a.down) (extractionPath a.down)).elim _ _
  map_comp f g :=
    (CoherentNervePathFiltration.Path.thickPathHomSubsingleton
      (extractionPath.{u} _) (extractionPath _)).elim _ _

/-- Select the source coordinate of the last zero vertex functorially. -/
def extractionCoordinateFunctor (n : ℕ) :
    (extractionFirst.{u} n ⟶ extractionLast.{u} n) ⥤ CoherentOrdinal.{u} n where
  obj P := ULift.up (extractionLastZeroCoordinate n P)
  map {P Q} f := homOfLE (by
    change (lastZero
      (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl P).down.val ≤
        (lastZero
          (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl Q).down.val
    exact lastZero_mono (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl f)
  map_id _ := Subsingleton.elim _ _
  map_comp _ _ := Subsingleton.elim _ _

/-- Canonical extraction followed by last-zero selection is strictly the identity on source
coordinates. -/
theorem extractionPathFunctor_comp_coordinateFunctor (n : ℕ) :
    extractionPathFunctor.{u} n ⋙ extractionCoordinateFunctor.{u} n =
      𝟭 (CoherentOrdinal.{u} n) := by
  exact CategoryTheory.Functor.ext
    (h_obj := fun a ↦ by
      apply ULift.ext
      apply Fin.ext
      change (lastZero
        (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl
          (extractionPath.{u} a.down)).down.val = a.down.val
      rw [lastZero_extractionPath]
      rfl)
    (h_map := fun _ _ _ ↦ Subsingleton.elim _ _)

/-- Every extraction path is included in the canonical path generated by its last zero
coordinate. -/
theorem extractionPath_le_canonical (n : ℕ)
    (P : extractionFirst.{u} n ⟶ extractionLast.{u} n) :
    P.I ⊆ (extractionPath.{u} (extractionLastZeroCoordinate n P)).I := by
  intro k hk
  by_cases hkLast : k.down = Fin.last (n + 1)
  · exact Or.inr hkLast
  · apply Or.inl
    have hkVal : k.down.val ≠ n + 1 := by
      intro h
      apply hkLast
      apply Fin.ext
      exact h
    have hkzero : intervalValue
        (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) k = 0 := by
      change (if k.down.val = n + 1 then 1 else 0) = 0
      simp [hkVal]
    have hkle : k ≤ lastZero
        (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl P := by
      apply Finset.le_max'
      simp only [zeroVertices, Finset.mem_filter, Finset.mem_univ, true_and]
      exact ⟨hk, hkzero⟩
    change k.down ≤ (extractionLastZeroCoordinate n P).castSucc
    change k.down.val ≤
      (lastZero (SSet.stdSimplex.objMk.{u} (finalStepOrderHom n)) rfl P).down.val
    exact hkle

/-- The identity path functor maps naturally into the canonical last-zero closure. -/
def extractionPathClosureNatTrans (n : ℕ) :
    𝟭 (extractionFirst.{u} n ⟶ extractionLast.{u} n) ⟶
      extractionCoordinateFunctor.{u} n ⋙ extractionPathFunctor.{u} n where
  app P := ⟨⟨⟨extractionPath_le_canonical n P⟩⟩⟩
  naturality {_ _} _ := by
    exact (CoherentNervePathFiltration.Path.thickPathHomSubsingleton _ _).elim _ _

/-- Restriction along the canonical extraction paths is an adjoint equivalence of functor
quasicategories with every Kan target. -/
noncomputable def extractionPathPrecompBicategoricalEquivalence
    (n : ℕ) (Q : SSet.{u}) [SSet.KanComplex Q] :
    Bicategory.Equivalence
      (internalHomQCat
        (CategoryTheory.nerve
          (extractionFirst.{u} n ⟶ extractionLast.{u} n)) Q inferInstance)
      (internalHomQCat
        (CategoryTheory.nerve (CoherentOrdinal.{u} n)) Q inferInstance) :=
  internalHomPrecompBicategoricalEquivalenceOfRetractNatTrans
    (extractionPathFunctor.{u} n) (extractionCoordinateFunctor.{u} n)
    (extractionPathFunctor_comp_coordinateFunctor.{u} n)
    (extractionPathClosureNatTrans.{u} n) Q

end LeanLCAExactChallenge.Infinity.CoherentNerveMappingComparison
