import Mathlib.AlgebraicTopology.SimplicialSet.AnodyneExtensions.Inner.Basic
import LeanLCAExactChallenge.Infinity.Basic

/-!
# Inner-fibrant replacement of simplicial sets

This file extracts from mathlib's small-object argument a functorial replacement of any
simplicial set by a quasicategory. The unit is an inner anodyne extension. This is the
fibrant-replacement layer needed before a dg nerve or simplicial localization can be used as
an infinity-categorical carrier.
-/

set_option autoImplicit false

noncomputable section

universe u

namespace LeanLCAExactChallenge
namespace Infinity

open CategoryTheory
open CategoryTheory.Limits
open CategoryTheory.MorphismProperty

/-- The functorial small-object factorization generated by the inner horn inclusions. -/
def innerFibrantReplacementFactorization :=
  functorialFactorizationData SSet.innerHornInclusions.rlp.llp
    SSet.innerHornInclusions.rlp

/-- Regard the canonical map from a simplicial set to the terminal simplicial set as an
object of the arrow category. -/
def toTerminalArrow : SSet.{u} ⥤ Arrow SSet.{u} where
  obj X := Arrow.mk (terminalIsTerminal.from X)
  map {X Y} f := Arrow.homMk f (𝟙 _) (terminalIsTerminal.hom_ext _ _)
  map_id X := by ext <;> simp
  map_comp f g := by ext <;> simp

/-- Functorial inner-fibrant replacement of simplicial sets. -/
def innerFibrantReplacementFunctor : SSet.{u} ⥤ SSet.{u} :=
  toTerminalArrow ⋙ innerFibrantReplacementFactorization.Z

/-- The chosen inner-fibrant replacement of a simplicial set. -/
abbrev innerFibrantReplacement (X : SSet.{u}) : SSet.{u} :=
  innerFibrantReplacementFunctor.obj X

/-- The unit from a simplicial set to its inner-fibrant replacement. -/
def toInnerFibrantReplacement (X : SSet.{u}) :
    X ⟶ innerFibrantReplacement X :=
  innerFibrantReplacementFactorization.i.app (toTerminalArrow.obj X)

/-- The units into the inner-fibrant replacements form a natural transformation. -/
def toInnerFibrantReplacementNatTrans :
    Functor.id SSet.{u} ⟶ innerFibrantReplacementFunctor where
  app := toInnerFibrantReplacement
  naturality {X Y} f := by
    exact innerFibrantReplacementFactorization.i.naturality (toTerminalArrow.map f)

/-- The unit into the inner-fibrant replacement is inner anodyne. -/
theorem toInnerFibrantReplacement_innerAnodyne (X : SSet.{u}) :
    SSet.innerAnodyneExtensions (toInnerFibrantReplacement X) :=
  innerFibrantReplacementFactorization.hi (toTerminalArrow.obj X)

/-- The map from the replacement to the terminal simplicial set is an inner fibration. -/
theorem innerFibrantReplacement_to_terminal_innerFibration (X : SSet.{u}) :
    SSet.innerFibrations (terminalIsTerminal.from (innerFibrantReplacement X)) := by
  rw [terminalIsTerminal.hom_ext
    (terminalIsTerminal.from (innerFibrantReplacement X))
    (innerFibrantReplacementFactorization.p.app (toTerminalArrow.obj X))]
  exact innerFibrantReplacementFactorization.hp (toTerminalArrow.obj X)

/-- Every chosen inner-fibrant replacement is a quasicategory. -/
instance (X : SSet.{u}) : SSet.Quasicategory (innerFibrantReplacement X) :=
  SSet.quasicategory_of_from_innerFibrations _ terminalIsTerminal
    (innerFibrantReplacement_to_terminal_innerFibration X)

/-- The chosen inner-fibrant replacement, bundled as an object of `SSet.QCat`. -/
def innerFibrantReplacementQCat (X : SSet.{u}) : SSet.QCat :=
  ⟨innerFibrantReplacement X, inferInstance⟩

/-- The bundled replacement has the expected underlying simplicial set. -/
theorem innerFibrantReplacementQCat_obj (X : SSet.{u}) :
    (innerFibrantReplacementQCat X).1 = innerFibrantReplacement X :=
  rfl

end Infinity
end LeanLCAExactChallenge
