import LeanLCAExactChallenge.Infinity.JoyalSlices

/-! # Joyal's special left outer horn theorem -/

set_option autoImplicit false

noncomputable section

universe u

namespace LeanLCAExactChallenge.Infinity

open CategoryTheory Opposite Simplicial

def underSliceVertexMap {Q : SSet.{u}} {x : Q _⦋0⦌}
    (v : (underSlice Q x) _⦋0⦌) :
    (Δ[0] : SSet.{u}) ⟶ underSlice Q x :=
  SSet.yonedaEquiv.symm v

def underSliceVertexCone {Q : SSet.{u}} {x : Q _⦋0⦌}
    (v : (underSlice Q x) _⦋0⦌) :
    simplicialJoin (Δ[0] : SSet.{u}) Δ[0] ⟶ Q :=
  forgetAugmentation.{u}.map
    ((relativeDaySliceOverMapFixedBaseEquiv
      (emptyAugmentation.{u}.obj (Δ[0] : SSet.{u}))
      (emptyAugmentation.{u}.obj Q) (Δ[0] : SSet.{u})
      (emptyAugmentation.{u}.map (SSet.yonedaEquiv.symm x)))
        (underSliceVertexMap v)).1

def underSliceVertexEdgeSimplex {Q : SSet.{u}} {x : Q _⦋0⦌}
    (v : (underSlice Q x) _⦋0⦌) : Q _⦋1⦌ :=
  SSet.yonedaEquiv
    ((simplicialJoinStdSimplexIsoNat 0 0).inv ≫ underSliceVertexCone v)

def underSliceVertexEdge {Q : SSet.{u}} {x : Q _⦋0⦌}
    (v : (underSlice Q x) _⦋0⦌) :
    SSet.Edge (Q.δ 1 (underSliceVertexEdgeSimplex v))
      (Q.δ 0 (underSliceVertexEdgeSimplex v)) :=
  SSet.Edge.mk' (underSliceVertexEdgeSimplex v)

@[simp]
theorem underSliceVertexEdge_edge {Q : SSet.{u}} {x : Q _⦋0⦌}
    (v : (underSlice Q x) _⦋0⦌) :
    (underSliceVertexEdge v).edge = underSliceVertexEdgeSimplex v := rfl

/-- The zeroth vertex of a positive-dimensional standard boundary.  It is
displayed through the final face, which always contains vertex zero. -/
def boundaryZeroVertex (k : ℕ) :
    (Δ[0] : SSet.{u}) ⟶ (SSet.boundary (k + 1) : SSet.{u}) :=
  SSet.yonedaEquiv.symm
      (SSet.stdSimplex.obj₀Equiv.symm (0 : Fin (k + 1))) ≫
    SSet.boundary.ι (Fin.last (k + 1))

/-- The first vertex of a boundary diagram in an under-slice. -/
def underSliceBoundaryFirstVertex {Q : SSet.{u}} {x : Q _⦋0⦌}
    (k : ℕ) (c : (SSet.boundary (k + 1) : SSet.{u}) ⟶ underSlice Q x) :
    (underSlice Q x) _⦋0⦌ :=
  SSet.yonedaEquiv (boundaryZeroVertex k ≫ c)

/-- A relative boundary problem whose first cone edge is an equivalence.
The index `k = 0` is the two-vertex boundary used in the special outer
`2`-horn theorem. -/
structure UnderSliceEquivalenceBoundaryProblem
    (Q : SSet.{u}) (x : Q _⦋0⦌) (k : ℕ) where
  boundary : (SSet.boundary (k + 1) : SSet.{u}) ⟶ underSlice Q x
  source : ∀ v : (SSet.boundary (k + 1) : SSet.{u}) _⦋0⦌,
    Q.δ 1 (underSliceVertexEdgeSimplex (boundary.app (Opposite.op ⦋0⦌) v)) = x
  target : ∀ v : (SSet.boundary (k + 1) : SSet.{u}) _⦋0⦌,
    Q.δ 0 (underSliceVertexEdgeSimplex (boundary.app (Opposite.op ⦋0⦌) v)) =
      (underSliceProjection Q x).app (Opposite.op ⦋0⦌)
        (boundary.app (Opposite.op ⦋0⦌) v)
  firstIsEquivalence : EdgeIsEquivalence
    (underSliceVertexEdge (underSliceBoundaryFirstVertex k boundary))

def UnderSliceEquivalenceBoundaryProblem.edgeAt
    {Q : SSet.{u}} {x : Q _⦋0⦌} {k : ℕ}
    (P : UnderSliceEquivalenceBoundaryProblem Q x k)
    (v : (SSet.boundary (k + 1) : SSet.{u}) _⦋0⦌) :
    SSet.Edge x ((underSliceProjection Q x).app (Opposite.op ⦋0⦌)
      (P.boundary.app (Opposite.op ⦋0⦌) v)) :=
  SSet.Edge.castEndpoints (P.source v).symm (P.target v).symm
    (underSliceVertexEdge (P.boundary.app (Opposite.op ⦋0⦌) v))

def boundaryOneVertex :
    (Δ[0] : SSet.{u}) ⟶ (SSet.boundary 1 : SSet.{u}) :=
  SSet.boundary.ι (0 : Fin 2)

def boundaryZeroVertexElement : (SSet.boundary 1 : SSet.{u}) _⦋0⦌ :=
  SSet.yonedaEquiv (boundaryZeroVertex 0)

def boundaryOneVertexElement : (SSet.boundary 1 : SSet.{u}) _⦋0⦌ :=
  SSet.yonedaEquiv boundaryOneVertex

theorem underSliceBoundaryFirstVertex_zero
    {Q : SSet.{u}} {x : Q _⦋0⦌}
    (c : (SSet.boundary 1 : SSet.{u}) ⟶ underSlice Q x) :
    underSliceBoundaryFirstVertex 0 c =
      c.app (Opposite.op ⦋0⦌) boundaryZeroVertexElement := by
  simp [underSliceBoundaryFirstVertex, boundaryZeroVertexElement,
    SSet.yonedaEquiv_comp]

theorem UnderSliceEquivalenceBoundaryProblem.firstFixedIsEquivalence
    {Q : SSet.{u}} {x : Q _⦋0⦌}
    (P : UnderSliceEquivalenceBoundaryProblem Q x 0) :
    EdgeIsEquivalence (P.edgeAt boundaryZeroVertexElement) := by
  have he : EdgeIsEquivalence (underSliceVertexEdge
      (P.boundary.app (Opposite.op ⦋0⦌) boundaryZeroVertexElement)) := by
    rw [← underSliceBoundaryFirstVertex_zero P.boundary]
    exact P.firstIsEquivalence
  exact he.castEndpoints (P.source boundaryZeroVertexElement).symm
    (P.target boundaryZeroVertexElement).symm

/-- A solution extends the entire boundary, while allowing the missing
opposite face in `Q` to be generated by the slice projection. -/
def UnderSliceEquivalenceBoundaryProblem.HasExtension
    {Q : SSet.{u}} {x : Q _⦋0⦌} {k : ℕ}
    (P : UnderSliceEquivalenceBoundaryProblem Q x k) : Prop :=
  ∃ l : (Δ[k + 1] : SSet.{u}) ⟶ underSlice Q x,
    (SSet.boundary (k + 1)).ι ≫ l = P.boundary

def UnderSliceEquivalenceBoundaryProblem.faceBoundary
    {Q : SSet.{u}} {x : Q _⦋0⦌} {k : ℕ}
    (P : UnderSliceEquivalenceBoundaryProblem Q x (k + 1))
    (i : Fin (k + 3)) :
    (SSet.boundary (k + 1) : SSet.{u}) ⟶ underSlice Q x :=
  (SSet.boundary (k + 1)).ι ≫ SSet.boundary.ι i ≫ P.boundary

structure UnderSliceEquivalenceBoundaryProblem.SuccessorState
    {Q : SSet.{u}} {x : Q _⦋0⦌} {k : ℕ}
    (P : UnderSliceEquivalenceBoundaryProblem Q x (k + 1)) where
  face : ∀ i : Fin (k + 3), 0 < i →
    ((Δ[k + 1] : SSet.{u}) ⟶ underSlice Q x)
  face_boundary : ∀ (i : Fin (k + 3)) (hi : 0 < i),
    (SSet.boundary (k + 1)).ι ≫ face i hi = P.faceBoundary i

end LeanLCAExactChallenge.Infinity
