import LeanLCAExactChallenge.Infinity.EquivalenceForcing
import LeanLCAExactChallenge.Infinity.MetrizableRelative

/-!
# Equivalence forcing for corrected metrizable weak equivalences

This specializes the generic ordinary-nerve cell presentation to bounded complexes of
metrizable LCA groups. The resulting quasicategory provably inverts the generated corrected
weak equivalences. Its infinity-localization universal property and stability are not yet
asserted.
-/

set_option autoImplicit false

noncomputable section

namespace LeanLCAExactChallenge
namespace Infinity
namespace MetrizableBoundedComplexes

open CategoryTheory

/-- A generated corrected weak equivalence, including its source and target. -/
abbrev GeneratedWeakEquivalenceArrow :=
  WeakEquivalenceArrow ComplexCategory relativeCategory

def generatedWeakEquivalenceArrow {K L : ComplexCategory}
    (f : K ⟶ L) (hf : GeneratedWeakEquivalence f) :
    GeneratedWeakEquivalenceArrow where
  source := K
  target := L
  hom := f
  weak := hf

/-- A raw corrected weak equivalence determines an arrow in the generated class. -/
def correctedWeakEquivalenceArrow {K L : ComplexCategory}
    (f : K ⟶ L) (hf : CorrectedWeakEquivalence f) :
    GeneratedWeakEquivalenceArrow :=
  generatedWeakEquivalenceArrow f
    (correctedWeakEquivalence_le_generated f hf)

/-- The ordinary-nerve presentation with inverses attached to generated weak arrows. -/
abbrev metrizableEquivalenceForcingPresentation : SSet.{1} :=
  relativeCategory.equivalenceForcingPresentation

/-- A genuine quasicategory obtained from the equivalence-forcing presentation. -/
def metrizableEquivalenceForcingQCat : SSet.QCat.{1} :=
  relativeCategory.equivalenceForcingQCat

/-- The canonical ordinary-nerve map into the equivalence-forcing quasicategory. -/
def metrizableEquivalenceForcingMap :
    CategoryTheory.nerve ComplexCategory ⟶
      metrizableEquivalenceForcingQCat.obj :=
  relativeCategory.equivalenceForcingMap

/-- A generated weak arrow has a specified coherent free-equivalence extension. -/
def metrizableEquivalenceForcingMap_generatedExtension
    {K L : ComplexCategory} (f : K ⟶ L)
    (hf : GeneratedWeakEquivalence f) :
    EquivalenceIntervalExtension
      ((CategoryTheory.nerve.edgeMk f).map
        metrizableEquivalenceForcingMap) :=
  relativeCategory.equivalenceForcingMap_weakEquivalenceExtension
    (generatedWeakEquivalenceArrow f hf)

/-- A raw corrected weak arrow has a specified coherent free-equivalence extension. -/
def metrizableEquivalenceForcingMap_correctedExtension
    {K L : ComplexCategory} (f : K ⟶ L)
    (hf : CorrectedWeakEquivalence f) :
    EquivalenceIntervalExtension
      ((CategoryTheory.nerve.edgeMk f).map
        metrizableEquivalenceForcingMap) :=
  metrizableEquivalenceForcingMap_generatedExtension f
    (correctedWeakEquivalence_le_generated f hf)

/-- The ordinary nerve of bounded complexes, bundled as a quasicategory. -/
def metrizableComplexNerveQCat : SSet.QCat.{1} :=
  ⟨CategoryTheory.nerve ComplexCategory, inferInstance⟩

/-- The equivalence-forcing map, bundled as a map of quasicategories. -/
def metrizableEquivalenceForcingQCatMap :
    metrizableComplexNerveQCat ⟶ metrizableEquivalenceForcingQCat :=
  ObjectProperty.homMk metrizableEquivalenceForcingMap

/-- The canonical map inverts the full marking generated by corrected weak arrows. -/
theorem metrizableEquivalenceForcingMap_invertsMarkedEdges :
    InvertsMarkedEdges (relativeNerveEdgeMarking relativeCategory)
      metrizableEquivalenceForcingMap :=
  relativeCategory.equivalenceForcingMap_invertsMarkedEdges

/-- The full localization statement still required of the equivalence-forcing carrier. -/
abbrev MetrizableEquivalenceForcingMappingLocalizationProperty : Prop :=
  MappingQuasicategoryLocalizationProperty
    (relativeNerveEdgeMarking relativeCategory)
    metrizableEquivalenceForcingQCatMap

/-- Once the targetwise mapping universal property is proved, inversion completes the
localization package. -/
theorem metrizableEquivalenceForcingMappingLocalizationProperty_of_universal
    (h : ∀ Q : SSet.QCat.{1},
      Nonempty (MappingQuasicategoryLocalizationAt
        (relativeNerveEdgeMarking relativeCategory)
        metrizableEquivalenceForcingQCatMap Q)) :
    MetrizableEquivalenceForcingMappingLocalizationProperty where
  inverts := metrizableEquivalenceForcingMap_invertsMarkedEdges
  universal := h

/-- The canonical targetwise comparison into marking-inverting functors. -/
def metrizableEquivalenceForcingMappingComparison (Q : SSet.QCat.{1}) :
    (ihom metrizableEquivalenceForcingQCat.obj).obj Q.obj ⟶
      (relativeInternalHom (relativeNerveEdgeMarking relativeCategory) Q.obj :
        SSet.{1}) :=
  internalHomPrecompToRelative
    (relativeNerveEdgeMarking relativeCategory)
    metrizableEquivalenceForcingMap Q.obj
    metrizableEquivalenceForcingMap_invertsMarkedEdges

/-- The canonical comparison factors ordinary internal-Hom precomposition. -/
@[reassoc (attr := simp)]
theorem metrizableEquivalenceForcingMappingComparison_comp_inclusion
    (Q : SSet.QCat.{1}) :
    metrizableEquivalenceForcingMappingComparison Q ≫
        (relativeInternalHom
          (relativeNerveEdgeMarking relativeCategory) Q.obj).ι =
      internalHomPrecomp metrizableEquivalenceForcingMap Q.obj :=
  internalHomPrecompToRelative_comp_inclusion _ _ _ _

/-- The single targetwise equivalence assertion left after the v4.30 closure hypothesis. -/
def MetrizableEquivalenceForcingCanonicalComparisonIsEquivalence
    (hprod : InnerHornPushoutProductIsInnerAnodyne.{1})
    (Q : SSet.QCat.{1}) : Prop :=
  IsBicategoricalEquivalence
    (ObjectProperty.homMk
      (metrizableEquivalenceForcingMappingComparison Q) :
        internalHomQCat metrizableEquivalenceForcingQCat.obj Q.obj
            (@quasicategory_ihom_of_innerHornPushoutProduct
              hprod metrizableEquivalenceForcingQCat.obj Q.obj Q.property) ⟶
          relativeInternalHomQCat
            (relativeNerveEdgeMarking relativeCategory) Q.obj
            (@relativeInternalHom_quasicategory_of_innerHornPushoutProduct
              hprod (CategoryTheory.nerve ComplexCategory) Q.obj Q.property
              (relativeNerveEdgeMarking relativeCategory)))

/-- Pushout-product closure and equivalence of the canonical comparisons imply the full
mapping-quasicategory localization property. -/
theorem metrizableEquivalenceForcingMappingLocalizationProperty_of_comparisons
    (hprod : InnerHornPushoutProductIsInnerAnodyne.{1})
    (hEquiv : ∀ Q : SSet.QCat.{1},
      MetrizableEquivalenceForcingCanonicalComparisonIsEquivalence hprod Q) :
    MetrizableEquivalenceForcingMappingLocalizationProperty :=
  metrizableEquivalenceForcingMappingLocalizationProperty_of_universal
    (fun Q => ⟨MappingQuasicategoryLocalizationAt.ofCanonicalOfInnerHornPushoutProduct
      hprod (relativeNerveEdgeMarking relativeCategory)
      metrizableEquivalenceForcingQCatMap Q
      metrizableEquivalenceForcingMap_invertsMarkedEdges (by
        simpa only [MetrizableEquivalenceForcingCanonicalComparisonIsEquivalence,
          metrizableEquivalenceForcingMappingComparison,
          metrizableEquivalenceForcingQCatMap] using hEquiv Q)⟩)

/-- The presentation-to-quasicategory map is inner anodyne. -/
theorem metrizableToEquivalenceForcingQCat_innerAnodyne :
    SSet.innerAnodyneExtensions
      (relativeCategory.toEquivalenceForcingQCat) :=
  relativeCategory.toEquivalenceForcingQCat_innerAnodyne

/-- The equivalence-forcing map sends every generated weak equivalence to an equivalence. -/
theorem metrizableEquivalenceForcingMap_generated
    {K L : ComplexCategory} (f : K ⟶ L)
    (hf : GeneratedWeakEquivalence f) :
    EdgeIsEquivalence
      ((CategoryTheory.nerve.edgeMk f).map
        metrizableEquivalenceForcingMap) :=
  relativeCategory.equivalenceForcingMap_weakEquivalence
    (generatedWeakEquivalenceArrow f hf)

/-- In particular, every raw corrected cone weak equivalence becomes an equivalence. -/
theorem metrizableEquivalenceForcingMap_corrected
    {K L : ComplexCategory} (f : K ⟶ L)
    (hf : CorrectedWeakEquivalence f) :
    EdgeIsEquivalence
      ((CategoryTheory.nerve.edgeMk f).map
        metrizableEquivalenceForcingMap) :=
  metrizableEquivalenceForcingMap_generated f
    (correctedWeakEquivalence_le_generated f hf)

/-- The proved inversion data, packaged as a relative infinity functor. -/
def metrizableEquivalenceForcingRelativeInfinityFunctor :
    RelativeInfinityFunctor ComplexCategory relativeCategory
      metrizableEquivalenceForcingQCat where
  map := metrizableEquivalenceForcingMap
  map_weakEquivalence f hf :=
    metrizableEquivalenceForcingMap_generated f hf

end MetrizableBoundedComplexes
end Infinity
end LeanLCAExactChallenge
