import LeanLCAExactChallenge.Derived.BoundedDerivedWithCycles
import LeanLCAExactChallenge.Infinity.Relative

/-!
# The corrected metrizable relative category

The raw corrected weak equivalences are enlarged to their multiplicative closure.  This is
the smallest wide subcategory containing them and is therefore a valid relative-category
input.  Mapping into any multiplicative class inverts the closure exactly when it inverts
the original arrows.
-/

set_option autoImplicit false

noncomputable section

namespace LeanLCAExactChallenge
namespace Infinity
namespace MetrizableBoundedComplexes

open CategoryTheory

/-- Bounded complexes of default-universe metrizable LCA groups. -/
abbrev ComplexCategory : Type 1 :=
  BoundedComplexCategory MetrizableLCA.{0}

/-- The corrected mapping-cone weak equivalences before closing under composition. -/
abbrev CorrectedWeakEquivalence : MorphismProperty ComplexCategory :=
  boundedExactWeakEquivalenceWithCycles MetrizableLCA.{0}

/-- The relative subcategory generated by the corrected mapping-cone weak equivalences. -/
abbrev GeneratedWeakEquivalence : MorphismProperty ComplexCategory :=
  CorrectedWeakEquivalence.multiplicativeClosure

/-- The generated weak equivalences define a genuine ordinary relative category. -/
def relativeCategory : RelativeCategoryData ComplexCategory where
  weakEquivalences := GeneratedWeakEquivalence
  isMultiplicative := inferInstance

/-- Every raw corrected weak equivalence belongs to the generated relative subcategory. -/
theorem correctedWeakEquivalence_le_generated :
    CorrectedWeakEquivalence ≤ GeneratedWeakEquivalence :=
  CorrectedWeakEquivalence.le_multiplicativeClosure

/-- A functor sends the generated class into any multiplicative target class exactly when
it sends the raw corrected weak equivalences into that class. -/
theorem generated_le_inverseImage_iff
    {D : Type*} [Category D] (V : MorphismProperty D) [V.IsMultiplicative]
    (F : ComplexCategory ⥤ D) :
    GeneratedWeakEquivalence ≤ V.inverseImage F ↔
      CorrectedWeakEquivalence ≤ V.inverseImage F := by
  apply MorphismProperty.multiplicativeClosure_le_iff

end MetrizableBoundedComplexes
end Infinity
end LeanLCAExactChallenge
