import LeanLCAExactChallenge.Infinity.EquivalenceForcing
import Mathlib.AlgebraicTopology.SimplicialSet.HornColimits
import Mathlib.CategoryTheory.SmallObject.TransfiniteCompositionLifting

/-!
# The alternating filtration of the free-living equivalence

This file records the elementary simplicial filtration used in the thick-simplex proof
of coherent extension of equivalence edges.  Its `n`th term is generated by the alternating
simplex with vertex word `0, 1, 0, 1, ...` of length `n + 1`.
-/

set_option autoImplicit false

noncomputable section

universe u

namespace LeanLCAExactChallenge
namespace Infinity

open CategoryTheory
open CategoryTheory.Limits
open Opposite
open Simplicial

private theorem monotone_parity_eq_of_covers_positive
    {d N : ℕ} (f g : Fin (d + 1) → ℕ)
    (hf : Monotone f) (hg : Monotone g)
    (hfN : ∀ i, f i ≤ N) (hgN : ∀ i, g i ≤ N)
    (hfcover : ∀ q, 1 ≤ q → q ≤ N → ∃ i, f i = q)
    (hgcover : ∀ q, 1 ≤ q → q ≤ N → ∃ i, g i = q)
    (hparity : ∀ i, Even (f i) ↔ Even (g i)) : f = g := by
  have hstart (a : Fin (d + 1) → ℕ) (ha : Monotone a) (haN : ∀ i, a i ≤ N)
      (hacover : ∀ q, 1 ≤ q → q ≤ N → ∃ i, a i = q) :
      a 0 ≤ 1 := by
    by_cases hN : N = 0
    · subst N
      have := haN 0
      omega
    · obtain ⟨i, hi⟩ := hacover 1 (by omega) (by omega)
      have := ha (Fin.zero_le i)
      omega
  have hstep (a : Fin (d + 1) → ℕ) (ha : Monotone a) (haN : ∀ i, a i ≤ N)
      (hacover : ∀ q, 1 ≤ q → q ≤ N → ∃ i, a i = q)
      (i : Fin d) : a i.succ ≤ a i.castSucc + 1 := by
    by_contra h
    have hqN : a i.castSucc + 1 ≤ N := by
      exact (Nat.succ_le_iff.mpr (lt_of_lt_of_le (by omega) (haN i.succ)))
    obtain ⟨k, hk⟩ := hacover (a i.castSucc + 1) (by omega) hqN
    by_cases hki : k ≤ i.castSucc
    · have := ha hki
      omega
    · have hik : i.succ ≤ k := by
        exact Fin.castSucc_lt_iff_succ_le.mp (lt_of_not_ge hki)
      have := ha hik
      omega
  apply funext
  intro i
  induction i using Fin.induction with
  | zero =>
      have hf0 := hstart f hf hfN hfcover
      have hg0 := hstart g hg hgN hgcover
      have hp := hparity 0
      have hfz : f 0 = 0 ∨ f 0 = 1 := by omega
      have hgz : g 0 = 0 ∨ g 0 = 1 := by omega
      rcases hfz with hfz | hfz <;> rcases hgz with hgz | hgz
      · exact hfz.trans hgz.symm
      · exfalso
        have he : Even (f 0) := hfz.symm ▸ ⟨0, rfl⟩
        obtain ⟨a, ha⟩ := hp.mp he
        omega
      · exfalso
        have he : Even (g 0) := hgz.symm ▸ ⟨0, rfl⟩
        obtain ⟨a, ha⟩ := hp.mpr he
        omega
      · exact hfz.trans hgz.symm
  | succ i hi =>
      have hfm := hf i.castSucc_le_succ
      have hgm := hg i.castSucc_le_succ
      have hfs := hstep f hf hfN hfcover i
      have hgs := hstep g hg hgN hgcover i
      have hp := hparity i.succ
      by_contra hne
      obtain hlt | hgt := lt_or_gt_of_ne hne
      · have hfEq : f i.succ = f i.castSucc := by omega
        have hgEq : g i.succ = g i.castSucc + 1 := by omega
        rw [hfEq, hgEq, hi, Nat.even_add_one] at hp
        tauto
      · have hfEq : f i.succ = f i.castSucc + 1 := by omega
        have hgEq : g i.succ = g i.castSucc := by omega
        rw [hfEq, hgEq, hi, Nat.even_add_one] at hp
        tauto

private theorem monotone_parity_eq_of_left_covers_positive
    {d N : ℕ} (f g : Fin (d + 1) → ℕ)
    (hf : Monotone f) (hg : Monotone g)
    (hfN : ∀ i, f i ≤ N) (hgN : ∀ i, g i ≤ N)
    (hfcover : ∀ q, 1 ≤ q → q ≤ N → ∃ i, f i = q)
    (hparity : ∀ i, Even (f i) ↔ Even (g i)) : f = g := by
  have hfstart : f 0 ≤ 1 := by
    by_cases hN : N = 0
    · subst N
      have := hfN 0
      omega
    · obtain ⟨i, hi⟩ := hfcover 1 (by omega) (by omega)
      have := hf (Fin.zero_le i)
      omega
  have hfstep (i : Fin d) : f i.succ ≤ f i.castSucc + 1 := by
    by_contra h
    have hqN : f i.castSucc + 1 ≤ N := by
      exact Nat.succ_le_iff.mpr (lt_of_lt_of_le (by omega) (hfN i.succ))
    obtain ⟨k, hk⟩ := hfcover (f i.castSucc + 1) (by omega) hqN
    by_cases hki : k ≤ i.castSucc
    · have := hf hki
      omega
    · have hik : i.succ ≤ k :=
        Fin.castSucc_lt_iff_succ_le.mp (lt_of_not_ge hki)
      have := hf hik
      omega
  have hfg : ∀ i, f i ≤ g i := by
    intro i
    induction i using Fin.induction with
    | zero =>
        by_cases hf0 : f 0 = 0
        · omega
        · have hf1 : f 0 = 1 := by omega
          have hp := hparity 0
          rw [hf1] at hp
          by_contra h
          have hg0 : g 0 = 0 := by omega
          rw [hg0] at hp
          have he : Even 0 := ⟨0, rfl⟩
          obtain ⟨a, ha⟩ := hp.mpr he
          omega
    | succ i hi =>
        have hfm := hf i.castSucc_le_succ
        have hgm := hg i.castSucc_le_succ
        have hfs := hfstep i
        by_contra h
        have hfEq : f i.succ = f i.castSucc + 1 := by omega
        have hgEq : g i.succ = g i.castSucc := by omega
        have hprev : f i.castSucc = g i.castSucc := by omega
        have hp := hparity i.succ
        rw [hfEq, hgEq, hprev, Nat.even_add_one] at hp
        tauto
  let δ : Fin (d + 1) → ℕ := fun i ↦ g i - f i
  have hδ : Monotone δ := by
    rw [Fin.monotone_iff_le_succ]
    intro i
    change g i.castSucc - f i.castSucc ≤ g i.succ - f i.succ
    have hfm := hf i.castSucc_le_succ
    have hgm := hg i.castSucc_le_succ
    have hfs := hfstep i
    have hle0 := hfg i.castSucc
    have hle1 := hfg i.succ
    by_contra h
    have hfEq : f i.succ = f i.castSucc + 1 := by omega
    have hgEq : g i.succ = g i.castSucc := by omega
    have hp0 := hparity i.castSucc
    have hp1 := hparity i.succ
    rw [hfEq, hgEq, Nat.even_add_one] at hp1
    tauto
  have hflast : f (Fin.last d) = N := by
    by_cases hN : N = 0
    · subst N
      exact Nat.eq_zero_of_le_zero (hfN _)
    · obtain ⟨i, hi⟩ := hfcover N (by omega) (by omega)
      have := hf (Fin.le_last i)
      have hle := hfN (Fin.last d)
      rw [hi] at this
      exact le_antisymm hle this
  have hglast : g (Fin.last d) = N := by
    have := hfg (Fin.last d)
    have := hgN (Fin.last d)
    omega
  apply funext
  intro i
  have hd := hδ (Fin.le_last i)
  dsimp [δ] at hd
  rw [hflast, hglast] at hd
  have := hfg i
  omega

/-- The alternating `n`-simplex of the nerve of the free-living equivalence. -/
def alternatingEquivalenceSimplex (n : ℕ) :
    (CategoryTheory.nerve EquivalenceInterval.{u}) _⦋n⦌ :=
  { obj := fun i ↦ if Even i.val then EquivalenceInterval.zero else EquivalenceInterval.one
    map := fun _ ↦ PUnit.unit
    map_id := fun _ ↦ rfl
    map_comp := fun _ _ ↦ rfl }

@[simp]
theorem alternatingEquivalenceSimplex_obj (n : ℕ) (i : Fin (n + 1)) :
    (alternatingEquivalenceSimplex n).obj i =
      if Even i.val then EquivalenceInterval.zero else EquivalenceInterval.one :=
  rfl

/-- Deleting the final vertex of an alternating simplex gives the preceding one. -/
theorem alternatingEquivalenceSimplex_delta_last (n : ℕ) :
    (CategoryTheory.nerve EquivalenceInterval.{u}).δ (Fin.last (n + 1))
        (alternatingEquivalenceSimplex (n + 1)) =
      alternatingEquivalenceSimplex n := by
  apply ComposableArrows.ext
  · intro _ _
    rfl
  · intro i
    simp only [CategoryTheory.nerve.δ_obj, alternatingEquivalenceSimplex_obj]
    rw [Fin.succAbove_of_castSucc_lt _ _ (by simp)]
    simp

/-- The first alternating edge is the distinguished forward edge. -/
theorem alternatingEquivalenceSimplex_one :
    alternatingEquivalenceSimplex 1 =
      (CategoryTheory.nerve.edgeMk equivalenceIntervalForward.{u}).edge := by
  apply ComposableArrows.ext
  · intro _ _
    rfl
  · intro i
    fin_cases i <;> rfl

/-- The `n`th term of the alternating filtration of the thick `1`-simplex. -/
def alternatingEquivalenceSubcomplex (n : ℕ) :
    (CategoryTheory.nerve EquivalenceInterval.{u}).Subcomplex :=
  SSet.Subcomplex.ofSimplex (alternatingEquivalenceSimplex n)

/-- The initial edge inclusion has image the first nontrivial filtration term. -/
theorem range_equivalenceIntervalInclusion :
    SSet.Subcomplex.range equivalenceIntervalInclusion.{u} =
      alternatingEquivalenceSubcomplex 1 := by
  rw [equivalenceIntervalInclusion, SSet.Subcomplex.range_eq_ofSimplex,
    Equiv.apply_symm_apply, alternatingEquivalenceSubcomplex,
    alternatingEquivalenceSimplex_one]

/-- The endomorphism which folds the two vertices adjacent to a deleted interior vertex. -/
def alternatingFaceFold {n : ℕ} (j : Fin (n + 2)) : ⦋n⦌ ⟶ ⦋n⦌ :=
  SimplexCategory.mkHom
    { toFun := fun k ↦ ⟨if k.val < j.val then k.val else k.val - 1, by
        split_ifs <;> omega⟩
      monotone' := by
        intro a b hab
        simp only [Fin.le_iff_val_le_val] at hab ⊢
        split_ifs <;> omega }

/-- Every noninitial face of an alternating simplex lies in the preceding filtration term. -/
theorem alternatingEquivalenceSimplex_delta_mem
    {n : ℕ} (j : Fin (n + 2)) (hj : j ≠ 0) :
    (CategoryTheory.nerve EquivalenceInterval.{u}).δ j
        (alternatingEquivalenceSimplex (n + 1)) ∈
      (alternatingEquivalenceSubcomplex n).obj (op ⦋n⦌) := by
  rw [alternatingEquivalenceSubcomplex, SSet.Subcomplex.mem_ofSimplex_obj_iff]
  by_cases hjlast : j = Fin.last (n + 1)
  · subst j
    exact ⟨𝟙 ⦋n⦌, by simp [alternatingEquivalenceSimplex_delta_last]⟩
  · refine ⟨alternatingFaceFold j, ?_⟩
    apply ComposableArrows.ext
    · intro _ _
      rfl
    · intro k
      simp only [CategoryTheory.nerve.δ_obj, alternatingEquivalenceSimplex_obj]
      change (if Even ((alternatingFaceFold j).toOrderHom k).val then _ else _) =
        if Even (j.succAbove k).val then _ else _
      have hjpos : 0 < j.val := Fin.pos_iff_ne_zero.mpr hj
      have hjlt : j.val < n + 1 := Fin.lt_last_iff_ne_last.mpr hjlast
      rcases j with ⟨j, hj'⟩
      rcases k with ⟨k, hk⟩
      change 0 < j at hjpos
      by_cases hkj : k < j
      · rw [Fin.succAbove_of_castSucc_lt _ _ (by exact hkj)]
        change (if Even (if k < j then k else k - 1) then _ else _) =
          if Even k then _ else _
        simp only [hkj, ↓reduceIte]
      · rw [Fin.succAbove_of_le_castSucc _ _ (by exact Nat.le_of_not_gt hkj)]
        change (if Even (if k < j then k else k - 1) then _ else _) =
          if Even (k + 1) then _ else _
        simp only [hkj, ↓reduceIte]
        have heven : Even (k - 1) ↔ Even (k + 1) := by
          simp only [Even]
          constructor <;> rintro ⟨a, ha⟩
          · exact ⟨a + 1, by omega⟩
          · have ha0 : 0 < a := by omega
            exact ⟨a - 1, by omega⟩
        simp only [heven]

/-- The classifying map of the alternating simplex. -/
def alternatingEquivalenceSimplexMap (n : ℕ) :
    (Δ[n] : SSet.{u}) ⟶ CategoryTheory.nerve EquivalenceInterval.{u} :=
  SSet.yonedaEquiv.symm (alternatingEquivalenceSimplex n)

@[simp]
theorem alternatingEquivalenceSimplexMap_app_id (n : ℕ) :
    (alternatingEquivalenceSimplexMap n).app _
        (SSet.stdSimplex.objEquiv.symm (𝟙 ⦋n⦌)) =
      alternatingEquivalenceSimplex n := by
  change SSet.yonedaEquiv (alternatingEquivalenceSimplexMap n) = _
  exact Equiv.apply_symm_apply _ _

/-- Although the alternating classifying map is not monic, it is injective on the
complement of the noninitial outer horn in every simplicial degree. -/
theorem alternatingEquivalenceSimplexMap_injective_outside_horn
    {n d : ℕ} (x y : (Δ[n + 1] : SSet.{u}) _⦋d⦌)
    (hx : x ∉ (SSet.horn (n + 1) (0 : Fin (n + 2))).obj (op ⦋d⦌))
    (hxy : (alternatingEquivalenceSimplexMap (n + 1)).app _ x =
      (alternatingEquivalenceSimplexMap (n + 1)).app _ y) : x = y := by
  let f : Fin (d + 1) → ℕ := fun i ↦ (SSet.stdSimplex.objEquiv x).toOrderHom i
  let g : Fin (d + 1) → ℕ := fun i ↦ (SSet.stdSimplex.objEquiv y).toOrderHom i
  have hf : Monotone f := fun _ _ h ↦ (SSet.stdSimplex.objEquiv x).toOrderHom.monotone h
  have hg : Monotone g := fun _ _ h ↦ (SSet.stdSimplex.objEquiv y).toOrderHom.monotone h
  have hfN : ∀ i, f i ≤ n + 1 := fun i ↦ Nat.le_of_lt_succ (SSet.stdSimplex.objEquiv x i).2
  have hgN : ∀ i, g i ≤ n + 1 := fun i ↦ Nat.le_of_lt_succ (SSet.stdSimplex.objEquiv y i).2
  have hfcover : ∀ q, 1 ≤ q → q ≤ n + 1 → ∃ i, f i = q := by
    intro q hq hq'
    let j : Fin (n + 2) := ⟨q, by omega⟩
    have hj : j ≠ 0 := by
      intro h
      have hv := congrArg Fin.val h
      simp [j] at hv
      omega
    have hjrange : j ∈ Set.range (SSet.stdSimplex.objEquiv x) := by
      by_contra h
      exact hx ((SSet.mem_horn_iff_notMem_range x 0).2 ⟨j, hj, h⟩)
    obtain ⟨i, hi⟩ := hjrange
    exact ⟨i, congrArg Fin.val hi⟩
  have hparity : ∀ i, Even (f i) ↔ Even (g i) := by
    intro i
    have hi := congrArg (fun z ↦ z.obj i) hxy
    change (if Even (f i) then EquivalenceInterval.zero else EquivalenceInterval.one) =
      if Even (g i) then EquivalenceInterval.zero else EquivalenceInterval.one at hi
    constructor
    · intro hfi
      by_contra hgi
      simp [hfi, hgi] at hi
    · intro hgi
      by_contra hfi
      simp [hfi, hgi] at hi
  have hfg := monotone_parity_eq_of_left_covers_positive f g hf hg hfN hgN
    hfcover hparity
  apply SSet.stdSimplex.objEquiv.injective
  apply SimplexCategory.Hom.ext
  apply OrderHom.ext
  exact funext (fun i ↦ Fin.ext (congrFun hfg i))

/-- The image of the noninitial outer horn under the alternating classifying map is
exactly the preceding filtration term. -/
theorem image_horn_alternatingEquivalenceSimplexMap (n : ℕ) :
    (Λ[n + 1, (0 : Fin (n + 2))] : (Δ[n + 1] : SSet.{u}).Subcomplex).image
        (alternatingEquivalenceSimplexMap (n + 1)) =
      alternatingEquivalenceSubcomplex n := by
  apply le_antisymm
  · rw [SSet.horn_eq_iSup, SSet.Subcomplex.image_iSup, iSup_le_iff]
    rintro ⟨j, hj⟩
    rw [SSet.stdSimplex.face_singleton_compl, SSet.Subcomplex.image_ofSimplex]
    rw [SSet.Subcomplex.ofSimplex_le_iff]
    change (SSet.yonedaEquiv.symm (alternatingEquivalenceSimplex (n + 1))).app _
        (SSet.stdSimplex.objEquiv.symm (SimplexCategory.δ j)) ∈ _
    rw [SSet.yonedaEquiv_symm_app_objEquiv_symm]
    exact alternatingEquivalenceSimplex_delta_mem j hj
  · have hface :
        (SSet.stdSimplex.face {(Fin.last (n + 1))}ᶜ).image
            (alternatingEquivalenceSimplexMap (n + 1)) =
          alternatingEquivalenceSubcomplex n := by
      rw [SSet.stdSimplex.face_singleton_compl, SSet.Subcomplex.image_ofSimplex,
        alternatingEquivalenceSubcomplex]
      congr 1
      change (SSet.yonedaEquiv.symm (alternatingEquivalenceSimplex (n + 1))).app _
          (SSet.stdSimplex.objEquiv.symm
            (SimplexCategory.δ (Fin.last (n + 1)))) = _
      rw [SSet.yonedaEquiv_symm_app_objEquiv_symm]
      exact alternatingEquivalenceSimplex_delta_last n
    rw [← hface]
    exact (SSet.Subcomplex.image_monotone
      (alternatingEquivalenceSimplexMap (n + 1)))
        (SSet.face_le_horn (Fin.last (n + 1)) 0 (by simp))

/-- The inverse image of the preceding filtration term is exactly the outer horn.
This is the quotient-sensitive statement which replaces monicity of the alternating
classifying map. -/
theorem preimage_alternatingEquivalenceSubcomplex (n : ℕ) :
    (alternatingEquivalenceSubcomplex n).preimage
        (alternatingEquivalenceSimplexMap (n + 1)) =
      Λ[n + 1, (0 : Fin (n + 2))] := by
  apply le_antisymm
  · intro U x hx
    by_contra hxhorn
    rw [← image_horn_alternatingEquivalenceSimplexMap] at hx
    obtain ⟨y, hy, hyx⟩ := hx
    have hxy : x = y := alternatingEquivalenceSimplexMap_injective_outside_horn
      x y hxhorn hyx.symm
    exact hxhorn (hxy ▸ hy)
  · rw [← SSet.Subcomplex.image_le_iff,
      image_horn_alternatingEquivalenceSimplexMap]

/-- The alternating simplex, corestricted to the filtration term it generates. -/
def alternatingSimplexToSubcomplex (n : ℕ) :
    (Δ[n] : SSet.{u}) ⟶ alternatingEquivalenceSubcomplex n :=
  SSet.Subcomplex.lift (alternatingEquivalenceSimplexMap n) (by
    rw [SSet.Subcomplex.range_eq_ofSimplex, alternatingEquivalenceSimplexMap,
      Equiv.apply_symm_apply]
    rfl)

/-- The outer horn map into the preceding alternating filtration term. -/
def alternatingHornToSubcomplex (n : ℕ) :
    (Λ[n + 1, (0 : Fin (n + 2))] : SSet.{u}) ⟶
      alternatingEquivalenceSubcomplex n :=
  SSet.Subcomplex.lift
    ((SSet.horn (n + 1) (0 : Fin (n + 2))).ι ≫
      alternatingEquivalenceSimplexMap (n + 1)) (by
        rw [SSet.Subcomplex.range_comp, SSet.Subcomplex.image_le_iff,
          preimage_alternatingEquivalenceSubcomplex]
        exact (Subfunctor.range_ι
          (SSet.horn (n + 1) (0 : Fin (n + 2)))).le)

@[reassoc (attr := simp)]
theorem alternatingSimplexToSubcomplex_ι (n : ℕ) :
    alternatingSimplexToSubcomplex n ≫ (alternatingEquivalenceSubcomplex n).ι =
      alternatingEquivalenceSimplexMap n :=
  rfl

@[reassoc (attr := simp)]
theorem alternatingHornToSubcomplex_ι (n : ℕ) :
    alternatingHornToSubcomplex n ≫ (alternatingEquivalenceSubcomplex n).ι =
      (SSet.horn (n + 1) (0 : Fin (n + 2))).ι ≫
        alternatingEquivalenceSimplexMap (n + 1) :=
  rfl

theorem alternatingSimplexToSubcomplex_app_surjective (n : ℕ)
    (U : SimplexCategoryᵒᵖ) :
    Function.Surjective ((alternatingSimplexToSubcomplex n).app U) := by
  rintro ⟨z, hz⟩
  rw [alternatingEquivalenceSubcomplex,
    SSet.Subcomplex.mem_ofSimplex_obj_iff] at hz
  obtain ⟨f, rfl⟩ := hz
  refine ⟨SSet.stdSimplex.objEquiv.symm f, ?_⟩
  apply Subtype.ext
  change (SSet.yonedaEquiv.symm (alternatingEquivalenceSimplex n)).app U
      (SSet.stdSimplex.objEquiv.symm f) = _
  rw [SSet.yonedaEquiv_symm_app_objEquiv_symm]

/-- Each step of the alternating filtration is the actual pushout of one special
outer horn, despite the non-monic classifying map. -/
theorem alternatingEquivalenceSubcomplex_isPushout (n : ℕ) :
    IsPushout (alternatingHornToSubcomplex n)
      (SSet.horn (n + 1) (0 : Fin (n + 2))).ι
      (SSet.Subcomplex.homOfLE (by
        rw [alternatingEquivalenceSubcomplex, alternatingEquivalenceSubcomplex,
          ← alternatingEquivalenceSimplex_delta_last n]
        exact SSet.Subcomplex.ofSimplex_map_le
          (SimplexCategory.δ (Fin.last (n + 1)))
          (alternatingEquivalenceSimplex (n + 1))))
      (alternatingSimplexToSubcomplex (n + 1)) := by
  refine ⟨?_, ⟨evaluationJointlyReflectsColimits _ (fun U ↦ ?_)⟩⟩
  · refine ⟨?_⟩
    apply (cancel_mono (alternatingEquivalenceSubcomplex (n + 1)).ι).1
    simp
  · refine (isColimitMapCoconePushoutCoconeEquiv _ _).2
      (IsPushout.isColimit ?_)
    refine Types.isPushout_of_isPullback_of_mono' ?_ ?_ ?_
    · rw [Types.isPullback_iff]
      refine ⟨by ext x; rfl, ?_, ?_⟩
      · intro x y h
        exact (mono_iff_injective _).mp inferInstance h.2
      · intro x₂ x₃ h
        have hx₃ : x₃ ∈ (SSet.horn (n + 1) (0 : Fin (n + 2))).obj U := by
          rw [← preimage_alternatingEquivalenceSubcomplex n]
          change (alternatingEquivalenceSimplexMap (n + 1)).app U x₃ ∈
            (alternatingEquivalenceSubcomplex n).obj U
          change ((alternatingSimplexToSubcomplex (n + 1)).app U x₃).val ∈ _
          exact h ▸ x₂.property
        refine ⟨⟨x₃, hx₃⟩, ?_, rfl⟩
        apply Subtype.ext
        change ((alternatingSimplexToSubcomplex (n + 1)).app U x₃).val = x₂.val
        exact congrArg Subtype.val h.symm
    · apply Set.eq_univ_of_forall
      intro x
      right
      exact alternatingSimplexToSubcomplex_app_surjective (n + 1) U x
    · intro x y hx hy h
      apply alternatingEquivalenceSimplexMap_injective_outside_horn x y
      · intro hxhorn
        exact hx ⟨⟨x, hxhorn⟩, rfl⟩
      · exact congrArg Subtype.val h

/-- The range of the new alternating simplex meets the preceding filtration term in
exactly the image of its noninitial outer horn. -/
theorem range_inf_alternatingEquivalenceSubcomplex (n : ℕ) :
    SSet.Subcomplex.range (alternatingEquivalenceSimplexMap (n + 1)) ⊓
        alternatingEquivalenceSubcomplex n =
      (Λ[n + 1, (0 : Fin (n + 2))] : (Δ[n + 1] : SSet.{u}).Subcomplex).image
        (alternatingEquivalenceSimplexMap (n + 1)) := by
  rw [image_horn_alternatingEquivalenceSimplexMap]
  apply inf_eq_right.mpr
  rw [SSet.Subcomplex.range_eq_ofSimplex, alternatingEquivalenceSimplexMap,
    Equiv.apply_symm_apply]
  rw [alternatingEquivalenceSubcomplex,
    ← alternatingEquivalenceSimplex_delta_last n]
  exact SSet.Subcomplex.ofSimplex_map_le
    (SimplexCategory.δ (Fin.last (n + 1))) (alternatingEquivalenceSimplex (n + 1))

/-- The alternating filtration is increasing. -/
theorem alternatingEquivalenceSubcomplex_monotone :
    Monotone alternatingEquivalenceSubcomplex := by
  refine monotone_nat_of_le_succ (fun n ↦ ?_)
  rw [alternatingEquivalenceSubcomplex, alternatingEquivalenceSubcomplex,
    ← alternatingEquivalenceSimplex_delta_last n]
  exact SSet.Subcomplex.ofSimplex_map_le
    (SimplexCategory.δ (Fin.last (n + 1))) (alternatingEquivalenceSimplex (n + 1))

/-- Binary code of a vertex of the free-living equivalence. -/
def equivalenceIntervalCode : EquivalenceInterval.{u} → ℕ
  | .zero => 0
  | .one => 1

theorem equivalenceIntervalCode_le_one (x : EquivalenceInterval.{u}) :
    equivalenceIntervalCode x ≤ 1 := by
  cases x <;> simp [equivalenceIntervalCode]

theorem equivalenceIntervalCode_even_iff (x : EquivalenceInterval.{u}) :
    Even (equivalenceIntervalCode x) ↔ x = EquivalenceInterval.zero := by
  cases x
  · constructor
    · intro
      rfl
    · intro
      exact ⟨0, rfl⟩
  · constructor
    · rintro ⟨r, h⟩
      simp only [equivalenceIntervalCode] at h
      omega
    · intro h
      cases h

/-- Embed an arbitrary vertex word into a sufficiently long alternating word. -/
def alternatingWordEmbedding {d : ℕ}
    (x : (CategoryTheory.nerve EquivalenceInterval.{u}) _⦋d⦌) :
    ⦋d⦌ ⟶ ⦋2 * d + 1⦌ :=
  SimplexCategory.mkHom
    { toFun := fun i ↦
        ⟨2 * i.val + equivalenceIntervalCode (x.obj i), by
          have := equivalenceIntervalCode_le_one (x.obj i)
          omega⟩
      monotone' := by
        intro i j hij
        simp only [Fin.le_iff_val_le_val] at hij ⊢
        by_cases h : i = j
        · subst j
          rfl
        · have hij' : i.val < j.val := lt_of_le_of_ne hij (by
            intro hval
            exact h (Fin.ext hval))
          have hi := equivalenceIntervalCode_le_one (x.obj i)
          omega }

/-- Every simplex of the free-living equivalence is a simplex of an alternating
filtration term. -/
theorem mem_alternatingEquivalenceSubcomplex (d : ℕ)
    (x : (CategoryTheory.nerve EquivalenceInterval.{u}) _⦋d⦌) :
    x ∈ (alternatingEquivalenceSubcomplex (2 * d + 1)).obj (op ⦋d⦌) := by
  rw [alternatingEquivalenceSubcomplex, SSet.Subcomplex.mem_ofSimplex_obj_iff]
  refine ⟨alternatingWordEmbedding x, ?_⟩
  apply ComposableArrows.ext
  · intro _ _
    rfl
  · intro i
    change (if Even (2 * i.val + equivalenceIntervalCode (x.obj i)) then
        EquivalenceInterval.zero else EquivalenceInterval.one) = x.obj i
    have heven : Even (2 * i.val + equivalenceIntervalCode (x.obj i)) ↔
        Even (equivalenceIntervalCode (x.obj i)) := by
      simp only [Even]
      constructor
      · rintro ⟨r, h⟩
        refine ⟨r - i.val, ?_⟩
        omega
      · rintro ⟨r, h⟩
        exact ⟨i.val + r, by omega⟩
    by_cases h : Even (2 * i.val + equivalenceIntervalCode (x.obj i))
    · rw [if_pos h]
      exact (equivalenceIntervalCode_even_iff _).mp (heven.mp h) |>.symm
    · rw [if_neg h]
      cases hx : x.obj i
      · exfalso
        apply h
        exact heven.mpr ((equivalenceIntervalCode_even_iff _).mpr hx)
      · rfl

/-- The increasing alternating filtration exhausts the free-living equivalence. -/
theorem iSup_alternatingEquivalenceSubcomplex_succ :
    ⨆ n : ℕ, alternatingEquivalenceSubcomplex (n + 1) = ⊤ := by
  apply top_unique
  intro U x _
  induction U using Opposite.rec with
  | _ U =>
      induction U using SimplexCategory.rec with
      | _ d =>
          simp only [Subfunctor.iSup_obj, Set.mem_iUnion]
          exact ⟨2 * d, mem_alternatingEquivalenceSubcomplex d x⟩

/-- The monotone sequence of nonempty alternating filtration terms. -/
def alternatingEquivalenceFiltrationMonotone :
    Monotone (fun n : ℕ ↦ alternatingEquivalenceSubcomplex (n + 1)) := by
  intro n m h
  exact alternatingEquivalenceSubcomplex_monotone (Nat.add_le_add_right h 1)

/-- The inclusion of the first filtration term into the free-living equivalence. -/
def alternatingEquivalenceFiltrationInclusion :
    (alternatingEquivalenceSubcomplex 1 : SSet.{u}) ⟶
      CategoryTheory.nerve EquivalenceInterval.{u} :=
  (alternatingEquivalenceSubcomplex 1).ι

/-- The free-living equivalence is the sequential colimit of its nonempty alternating
filtration. -/
noncomputable def alternatingEquivalenceTransfiniteComposition :
    CategoryTheory.TransfiniteCompositionOfShape ℕ
      alternatingEquivalenceFiltrationInclusion.{u} where
  F := alternatingEquivalenceFiltrationMonotone.functor ⋙
    SSet.Subcomplex.toSSetFunctor
  isoBot := Iso.refl _
  incl.app n := (alternatingEquivalenceSubcomplex (n + 1)).ι
  isColimit :=
    IsColimit.ofIsoColimit
      (isColimitOfPreserves SSet.Subcomplex.toSSetFunctor
        (Preorder.colimitCoconeOfIsLUB
          alternatingEquivalenceFiltrationMonotone.functor (pt := ⊤)
          (by rw [← iSup_alternatingEquivalenceSubcomplex_succ]; apply isLUB_iSup)).isColimit)
      (Cocone.ext (SSet.Subcomplex.topIso _))
  fac := rfl

instance alternatingSimplexToSubcomplex_epi (n : ℕ) :
    Epi (alternatingSimplexToSubcomplex n) := by
  rw [NatTrans.epi_iff_epi_app]
  intro U
  rw [epi_iff_surjective]
  exact alternatingSimplexToSubcomplex_app_surjective n U

private theorem stdSimplex_one_eq_of_mem_horn_zero
    {U : SimplexCategoryᵒᵖ} (x y : (Δ[1] : SSet.{u}).obj U)
    (hx : x ∈ (SSet.horn 1 (0 : Fin 2)).obj U)
    (hy : y ∈ (SSet.horn 1 (0 : Fin 2)).obj U) : x = y := by
  apply SSet.stdSimplex.objEquiv.injective
  apply SimplexCategory.Hom.ext
  apply OrderHom.ext
  funext i
  apply Fin.ext
  have hx' := (SSet.mem_horn_iff_notMem_range x 0).mp hx
  have hy' := (SSet.mem_horn_iff_notMem_range y 0).mp hy
  obtain ⟨jx, hjx0, hjx⟩ := hx'
  obtain ⟨jy, hjy0, hjy⟩ := hy'
  have hjx : jx = (1 : Fin 2) := by fin_cases jx <;> simp_all
  have hjy : jy = (1 : Fin 2) := by fin_cases jy <;> simp_all
  subst jx
  subst jy
  have hxi : (SSet.stdSimplex.objEquiv x).toOrderHom i ≠ (1 : Fin 2) := by
    intro h
    exact hjx ⟨i, h⟩
  have hyi : (SSet.stdSimplex.objEquiv y).toOrderHom i ≠ (1 : Fin 2) := by
    intro h
    exact hjy ⟨i, h⟩
  have hxv : ((SSet.stdSimplex.objEquiv x).toOrderHom i).val ≠ 1 := by
    intro h
    exact hxi (Fin.ext h)
  have hyv : ((SSet.stdSimplex.objEquiv y).toOrderHom i).val ≠ 1 := by
    intro h
    exact hyi (Fin.ext h)
  have hxb := ((SSet.stdSimplex.objEquiv x).toOrderHom i).isLt
  have hyb := ((SSet.stdSimplex.objEquiv y).toOrderHom i).isLt
  change ((SSet.stdSimplex.objEquiv x).toOrderHom i).val < 2 at hxb
  change ((SSet.stdSimplex.objEquiv y).toOrderHom i).val < 2 at hyb
  omega

instance alternatingSimplexToSubcomplex_one_mono :
    Mono (alternatingSimplexToSubcomplex 1) := by
  rw [NatTrans.mono_iff_mono_app]
  intro U
  rw [mono_iff_injective]
  intro x y h
  by_cases hx : x ∈ (SSet.horn 1 (0 : Fin 2)).obj U
  · by_cases hy : y ∈ (SSet.horn 1 (0 : Fin 2)).obj U
    · exact stdSimplex_one_eq_of_mem_horn_zero x y hx hy
    · exact (alternatingEquivalenceSimplexMap_injective_outside_horn y x hy
        (congrArg Subtype.val h).symm).symm
  · exact alternatingEquivalenceSimplexMap_injective_outside_horn x y hx
      (congrArg Subtype.val h)

instance alternatingSimplexToSubcomplex_one_isIso :
    IsIso (alternatingSimplexToSubcomplex 1) :=
  isIso_of_mono_of_epi _

/-- Stagewise lifting along the alternating filtration. -/
def AlternatingFiltrationRLP (Q : SSet.{u}) : Prop :=
  ∀ n : ℕ, HasLiftingProperty
    (SSet.Subcomplex.homOfLE
      (alternatingEquivalenceFiltrationMonotone (Nat.le_succ n)))
    (terminal.from Q)

/-- Stagewise RLPs produce a coherent map out of the entire free-living equivalence. -/
noncomputable def alternatingFiltrationExtension
    {Q : SSet.{u}} (hQ : AlternatingFiltrationRLP Q)
    (f : (alternatingEquivalenceSubcomplex 1 : SSet.{u}) ⟶ Q) :
    CategoryTheory.nerve EquivalenceInterval.{u} ⟶ Q := by
  let c := alternatingEquivalenceTransfiniteComposition
  have hLift : HasLiftingProperty (c.incl.app ⊥) (terminal.from Q) :=
    HasLiftingProperty.transfiniteComposition.hasLiftingProperty_ι_app_bot
      (hc := c.isColimit) (fun n _ ↦ hQ n)
  let sq : CommSq f (c.incl.app ⊥) (terminal.from Q)
      (terminal.from (CategoryTheory.nerve EquivalenceInterval.{u})) :=
    ⟨Subsingleton.elim _ _⟩
  letI : sq.HasLift := hLift.sq_hasLift sq
  exact sq.lift

@[reassoc]
theorem alternatingFiltrationExtension_restrict
    {Q : SSet.{u}} (hQ : AlternatingFiltrationRLP Q)
    (f : (alternatingEquivalenceSubcomplex 1 : SSet.{u}) ⟶ Q) :
    alternatingEquivalenceFiltrationInclusion ≫
        alternatingFiltrationExtension hQ f = f := by
  let c := alternatingEquivalenceTransfiniteComposition
  let sq : CommSq f (c.incl.app ⊥) (terminal.from Q)
      (terminal.from (CategoryTheory.nerve EquivalenceInterval.{u})) :=
    ⟨Subsingleton.elim _ _⟩
  have hLift : HasLiftingProperty (c.incl.app ⊥) (terminal.from Q) :=
    HasLiftingProperty.transfiniteComposition.hasLiftingProperty_ι_app_bot
      (hc := c.isColimit) (fun n _ ↦ hQ n)
  letI : sq.HasLift := hLift.sq_hasLift sq
  change c.incl.app ⊥ ≫ sq.lift = f
  exact sq.fac_left

/-- Inclusion between two nonempty alternating filtration terms. -/
def alternatingFiltrationMap {n m : ℕ} (h : n ≤ m) :
    (alternatingEquivalenceSubcomplex (n + 1) : SSet.{u}) ⟶
      alternatingEquivalenceSubcomplex (m + 1) :=
  SSet.Subcomplex.homOfLE
    (alternatingEquivalenceFiltrationMonotone h)

@[simp]
theorem alternatingFiltrationMap_refl (n : ℕ) :
    alternatingFiltrationMap (le_refl n) = 𝟙 _ :=
  rfl

@[reassoc]
theorem alternatingFiltrationMap_comp {n m k : ℕ}
    (h₁ : n ≤ m) (h₂ : m ≤ k) :
    alternatingFiltrationMap h₁ ≫ alternatingFiltrationMap h₂ =
      alternatingFiltrationMap (h₁.trans h₂) :=
  rfl

/-- The exact successor-extension input used by special-horn recursion.  Unlike a
generic RLP, it only asks for maps whose restriction is the fixed initial edge. -/
def FixedAlternatingStageExtension {Q : SSet.{u}}
    (f₀ : (alternatingEquivalenceSubcomplex 1 : SSet.{u}) ⟶ Q) : Prop :=
  ∀ (n : ℕ) (f : (alternatingEquivalenceSubcomplex (n + 1) : SSet.{u}) ⟶ Q),
    alternatingFiltrationMap (Nat.zero_le n) ≫ f = f₀ →
      ∃ g : (alternatingEquivalenceSubcomplex (n + 2) : SSet.{u}) ⟶ Q,
        alternatingFiltrationMap (Nat.le_succ n) ≫ g = f

namespace FixedAlternatingStageExtension

variable {Q : SSet.{u}}
  {f₀ : (alternatingEquivalenceSubcomplex 1 : SSet.{u}) ⟶ Q}
  (h : FixedAlternatingStageExtension f₀)

/-- A stage map together with its fixed-edge equation. -/
structure State (n : ℕ) where
  map : (alternatingEquivalenceSubcomplex (n + 1) : SSet.{u}) ⟶ Q
  fixed : alternatingFiltrationMap (Nat.zero_le n) ≫ map = f₀

def initial : State (f₀ := f₀) 0 where
  map := f₀
  fixed := by simp [alternatingFiltrationMap]

noncomputable def next {n : ℕ} (s : State (f₀ := f₀) n) :
    State (f₀ := f₀) (n + 1) := by
  let g := Classical.choose (h n s.map s.fixed)
  have hg := Classical.choose_spec (h n s.map s.fixed)
  refine ⟨g, ?_⟩
  rw [← alternatingFiltrationMap_comp (Nat.zero_le n) (Nat.le_succ n),
    Category.assoc, hg, s.fixed]

noncomputable def state (h : FixedAlternatingStageExtension f₀) :
    (n : ℕ) → State (f₀ := f₀) n
  | 0 => initial
  | n + 1 => next h (state h n)

@[reassoc]
theorem state_succ (n : ℕ) :
    alternatingFiltrationMap (Nat.le_succ n) ≫ (state h (n + 1)).map =
      (state h n).map := by
  change alternatingFiltrationMap (Nat.le_succ n) ≫
      (next h (state h n)).map = _
  exact Classical.choose_spec (h n (state h n).map (state h n).fixed)

theorem state_compat {n m : ℕ} (hnm : n ≤ m) :
    alternatingFiltrationMap hnm ≫ (state h m).map = (state h n).map := by
  induction m, hnm using Nat.le_induction with
  | base => simp
  | succ m hnm ih =>
      rw [← alternatingFiltrationMap_comp hnm (Nat.le_succ m),
        Category.assoc, state_succ h m, ih]

/-- The compatible recursively chosen stages form a cocone. -/
noncomputable def cocone : Cocone
    (alternatingEquivalenceFiltrationMonotone.functor ⋙
      SSet.Subcomplex.toSSetFunctor) :=
  Cocone.mk Q
    { app n := (state h n).map
      naturality := by
        intro n m f
        exact state_compat h (CategoryTheory.leOfHom f) }

/-- Descend the compatible stages to the free-living equivalence. -/
noncomputable def extension : CategoryTheory.nerve EquivalenceInterval.{u} ⟶ Q :=
  alternatingEquivalenceTransfiniteComposition.isColimit.desc h.cocone

@[reassoc]
theorem extension_restrict :
    alternatingEquivalenceFiltrationInclusion ≫ h.extension = f₀ := by
  calc
    _ = (state h 0).map :=
      alternatingEquivalenceTransfiniteComposition.isColimit.fac h.cocone 0
    _ = f₀ := by simpa using (state h 0).fixed

end FixedAlternatingStageExtension

/-- The ordered edge on vertices `0,1` in `Δ[n+2]`. -/
def stdSimplexEdgeZeroOne (n : ℕ) : (Δ[1] : SSet.{u}) ⟶ Δ[n + 2] :=
  SSet.yonedaEquiv.symm (SSet.stdSimplex.objEquiv.symm
    (SimplexCategory.mkHom
      { toFun := fun i ↦ ⟨i.val, by omega⟩
        monotone' := fun _ _ h ↦ h }))

/-- The leading edge corestricted to the special left outer horn. -/
def specialLeftHornLeadingEdge (n : ℕ) :
    (Δ[1] : SSet.{u}) ⟶ Λ[n + 2, (0 : Fin (n + 3))] :=
  SSet.Subcomplex.lift (stdSimplexEdgeZeroOne n) (by
    rw [SSet.Subcomplex.range_eq_ofSimplex, SSet.Subcomplex.ofSimplex_le_iff]
    apply (SSet.mem_horn_iff_notMem_range _ 0).2
    refine ⟨Fin.last (n + 2), by simp, ?_⟩
    rintro ⟨i, hi⟩
    have hv := congrArg Fin.val hi
    change i.val = n + 2 at hv
    omega)

/-- The leading edge of a left outer horn map. -/
def specialLeftHornEdge {Q : SSet.{u}} {n : ℕ}
    (a : (Λ[n + 2, (0 : Fin (n + 3))] : SSet.{u}) ⟶ Q) : Q _⦋1⦌ :=
  SSet.yonedaEquiv (specialLeftHornLeadingEdge n ≫ a)

/-- All-dimensional Joyal special-left-horn filling property. -/
def HasAllSpecialLeftHornFillers (Q : SSet.{u}) : Prop :=
  ∀ (n : ℕ) (a : (Λ[n + 2, (0 : Fin (n + 3))] : SSet.{u}) ⟶ Q),
    EdgeIsEquivalence (SSet.Edge.mk' (specialLeftHornEdge a)) →
      ∃ b : (Δ[n + 2] : SSet.{u}) ⟶ Q,
        (SSet.horn (n + 2) (0 : Fin (n + 3))).ι ≫ b = a

theorem specialLeftHornLeadingEdge_comp_alternatingHornToSubcomplex (n : ℕ) :
    specialLeftHornLeadingEdge n ≫ alternatingHornToSubcomplex (n + 1) =
      alternatingSimplexToSubcomplex 1 ≫
        alternatingFiltrationMap (Nat.zero_le n) := by
  apply (cancel_mono (alternatingEquivalenceSubcomplex (n + 1)).ι).1
  apply SSet.yonedaEquiv.injective
  simp only [Category.assoc, alternatingHornToSubcomplex_ι,
    SSet.yonedaEquiv_comp]
  rfl

/-- Special left horn fillers give the exact fixed-edge successor extension input. -/
theorem fixedAlternatingStageExtension_of_specialLeftHornFillers
    {Q : SSet.{u}} (hQ : HasAllSpecialLeftHornFillers Q)
    (f₀ : (alternatingEquivalenceSubcomplex 1 : SSet.{u}) ⟶ Q)
    (hf₀ : EdgeIsEquivalence (SSet.Edge.mk'
      (SSet.yonedaEquiv (alternatingSimplexToSubcomplex 1 ≫ f₀)))) :
    FixedAlternatingStageExtension f₀ := by
  intro n f hf
  let a := alternatingHornToSubcomplex (n + 1) ≫ f
  have ha : EdgeIsEquivalence (SSet.Edge.mk' (specialLeftHornEdge a)) := by
    have hedge : specialLeftHornEdge a =
        SSet.yonedaEquiv (alternatingSimplexToSubcomplex 1 ≫ f₀) := by
      apply congrArg SSet.yonedaEquiv
      calc
        specialLeftHornLeadingEdge n ≫ a =
            (specialLeftHornLeadingEdge n ≫
              alternatingHornToSubcomplex (n + 1)) ≫ f := by rfl
        _ = (alternatingSimplexToSubcomplex 1 ≫
              alternatingFiltrationMap (Nat.zero_le n)) ≫ f := by
            rw [specialLeftHornLeadingEdge_comp_alternatingHornToSubcomplex]
        _ = alternatingSimplexToSubcomplex 1 ≫
              (alternatingFiltrationMap (Nat.zero_le n) ≫ f) := Category.assoc _ _ _
        _ = alternatingSimplexToSubcomplex 1 ≫ f₀ := by rw [hf]
    rw [hedge]
    exact hf₀
  obtain ⟨b, hb⟩ := hQ n a ha
  let sq := alternatingEquivalenceSubcomplex_isPushout (n + 1)
  let g := sq.desc f b (by simpa [a] using hb.symm)
  refine ⟨g, ?_⟩
  exact sq.inl_desc f b (by simpa [a] using hb.symm)

theorem alternatingSimplexToSubcomplex_one_comp_filtrationInclusion :
    alternatingSimplexToSubcomplex 1 ≫ alternatingEquivalenceFiltrationInclusion =
      equivalenceIntervalInclusion.{u} := by
  change alternatingSimplexToSubcomplex 1 ≫
      (alternatingEquivalenceSubcomplex 1).ι = equivalenceIntervalInclusion
  rw [alternatingSimplexToSubcomplex_ι]
  apply SSet.yonedaEquiv.injective
  rw [equivalenceIntervalInclusion, Equiv.apply_symm_apply,
    alternatingEquivalenceSimplexMap, Equiv.apply_symm_apply,
    alternatingEquivalenceSimplex_one]

/-- Joyal's all-dimensional special-left-horn theorem implies that every equivalence
edge extends coherently to the free-living equivalence. -/
theorem everyEquivalenceEdgeExtends_of_specialLeftHornFillers
    {Q : SSet.{u}} (hQ : HasAllSpecialLeftHornFillers Q) :
    ∀ s : Q _⦋1⦌, EdgeIsEquivalence (SSet.Edge.mk' s) →
      ∃ F : CategoryTheory.nerve EquivalenceInterval.{u} ⟶ Q,
        SSet.yonedaEquiv (equivalenceIntervalInclusion ≫ F) = s := by
  intro s hs
  let f₀ : (alternatingEquivalenceSubcomplex 1 : SSet.{u}) ⟶ Q :=
    inv (alternatingSimplexToSubcomplex 1) ≫ SSet.yonedaEquiv.symm s
  have hf₀edge :
      SSet.yonedaEquiv (alternatingSimplexToSubcomplex 1 ≫ f₀) = s := by
    simp [f₀]
  have hf₀ : EdgeIsEquivalence (SSet.Edge.mk'
      (SSet.yonedaEquiv (alternatingSimplexToSubcomplex 1 ≫ f₀))) := by
    rw [hf₀edge]
    exact hs
  let hstage := fixedAlternatingStageExtension_of_specialLeftHornFillers hQ f₀ hf₀
  refine ⟨hstage.extension, ?_⟩
  calc
    SSet.yonedaEquiv (equivalenceIntervalInclusion ≫ hstage.extension) =
        SSet.yonedaEquiv (alternatingSimplexToSubcomplex 1 ≫ f₀) := by
      congr 1
      rw [← alternatingSimplexToSubcomplex_one_comp_filtrationInclusion,
        Category.assoc, hstage.extension_restrict]
    _ = s := hf₀edge

end Infinity
end LeanLCAExactChallenge
