import LeanLCAExactChallenge.Derived.W987StrictPreimageMapFieldsComparisonGuardW1506
import LeanLCAExactChallenge.Derived.BoundaryFieldsComparisonStableExactAtRoute

/-!
W1507 feeds the W1506/W1498 surface through the W893 explicit WPP
boundary-fields comparison route. W1506 already reaches W892 strict-preimage
map-field leaves; W1507 splits its W716 boundary data into the right-open
quotient-cover boundary and source-pi-zero boundary fields consumed by W893,
then checks that W893 rebuilds the same W892 leaves and concrete route.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace LeanLCAExactChallenge

open CategoryTheory
open CategoryTheory.Limits

namespace Dbounded

noncomputable section

/-- W1507 reuses the W1506 74-field strict-preimage map comparison surface. -/
abbrev W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507 :
    Type 2 :=
  W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictPreimageMapFieldsComparisonInputW1506

/-- W1507 names the W1506 W892 strict-preimage map leaves used by the projections. -/
def strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    MetrizableWppStrictPreimageMapFieldLeavesW892 :=
  strictPreimageMapFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1506
    input

/-- W1507 assembles W893 boundary-field leaves by splitting W1506's W716 boundary data. -/
def boundaryFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1507
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    MetrizableWppBoundaryFieldLeavesW893 where
  rightOpenBoundary :=
    rightOpenBoundary_of_boundaryDataW716
      (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
        input).boundaryData
  sourcePiZeroBoundary :=
    sourcePiZeroBoundary_of_boundaryDataW716
      (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
        input).boundaryData
  relationData :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).relationData
  targetSurjectiveCompactForTargetProvider :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).targetSurjectiveCompactForTargetProvider
  diagramAndMappedCokernelClosednessData :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).diagramAndMappedCokernelClosednessData
  strictPreimageZeroSrc :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageZeroSrc
  strictPreimageOneSrc :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageOneSrc
  strictPreimageZeroIso :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageZeroIso
  strictPreimageOneIso :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageOneIso
  strictPreimageLeftSrc :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageLeftSrc
  strictPreimageRightSrc :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageRightSrc
  strictPreimageLeftFac :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageLeftFac
  strictPreimageRightFac :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageRightFac
  strictPreimageZeroMap :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageZeroMap
  strictPreimageOneMap :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageOneMap
  strictPreimageZeroMapFac :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageZeroMapFac
  strictPreimageOneMapFac :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageOneMapFac
  strictPreimageLeftNaturality :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageLeftNaturality
  strictPreimageRightNaturality :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictPreimageRightNaturality
  strictRepresentativeMapId :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictRepresentativeMapId
  strictRepresentativeMapComp :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).strictRepresentativeMapComp
  sourceImageObjectNormalization :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).sourceImageObjectNormalization
  sourceImageMapNormalization :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).sourceImageMapNormalization
  targetFixedTargetUniq :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).targetFixedTargetUniq
  localizationModelFixedTargetUniq :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).localizationModelFixedTargetUniq
  sourcePretriangulated :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).sourcePretriangulated
  sourceTriangulated :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).sourceTriangulated
  triangleCompletion :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).triangleCompletion
  endpointForgetPreservesHomology :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).endpointForgetPreservesHomology
  endpointClosedEmbedding :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).endpointClosedEmbedding
  endpointOpenMap :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).endpointOpenMap
  endpointEpiOfExactAt :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).endpointEpiOfExactAt
  boundedHomotopyLocalizedRightAdjoint :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).boundedHomotopyLocalizedRightAdjoint
  boundedHomotopyLocalizedAdjunction :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).boundedHomotopyLocalizedAdjunction
  boundedHomotopyLocalizedUnitMem :=
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).boundedHomotopyLocalizedUnitMem

/-- W1507 projects W893 back to the W892 leaves consumed by W1506. -/
def strictPreimageMapFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    MetrizableWppStrictPreimageMapFieldLeavesW892 :=
  strictPreimageMapFieldLeavesOfBoundaryFieldsW893
    (boundaryFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1507
      input)

/-- W1507 exposes W893's W733 concrete leaves. -/
def concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    MetrizableWppBoundaryRelationTargetClosednessNormalizedConcreteLeavesW733 :=
  concreteLeavesOfBoundaryFieldsComparisonW893
    (boundaryFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1507
      input)

/-- W1507 exposes W893's W732 route data. -/
def routeDataProviderOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    MetrizableWppBoundaryRelationTargetClosednessNormalizedDataProviderW732 :=
  routeDataProviderOfBoundaryFieldsComparisonW893
    (boundaryFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1507
      input)

/-- W1507 feeds W893 explicit boundary fields to direct bounded left calculus. -/
theorem directBoundedLeftCalculusOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    (boundedExactWeakEquivalence MetrizableLCA.{0}).HasLeftCalculusOfFractions :=
  directBoundedLeftCalculusOfBoundaryFieldsComparisonStableExactAtW893
    (boundaryFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1507
      input)

/-- W1507 exposes W893's bounded derived infinity-category package. -/
def boundedDerivedInfinityCategoryOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    BoundedDerivedInfinityCategory MetrizableLCA.{0}
      (Dbounded.infinityCategory MetrizableLCA.{0}) :=
  boundedDerivedInfinityCategoryOfBoundaryFieldsComparisonStableExactAtW893
    (boundaryFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1507
      input)

/-- W1507's split W893 boundary data rebuilds W1506's bundled W716 boundary data. -/
theorem w1507BoundaryDataMatchesW1506
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    boundaryDataOfFieldsW893
        (rightOpenBoundary_of_boundaryDataW716
          (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
            input).boundaryData)
        (sourcePiZeroBoundary_of_boundaryDataW716
          (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
            input).boundaryData) =
      (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
        input).boundaryData := by
  cases
    (strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
      input).boundaryData
  rfl

/-- W1507's W893-to-W892 projection carries W1506's bundled boundary data. -/
theorem w1507StrictPreimageMapFieldLeavesBoundaryDataMatchesW1506
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    (strictPreimageMapFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
        input).boundaryData =
      (strictPreimageMapFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1506
        input).boundaryData := by
  simpa [
    strictPreimageMapFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507,
    boundaryFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1507,
    strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507,
    strictPreimageMapFieldLeavesOfBoundaryFieldsW893]
    using w1507BoundaryDataMatchesW1506 input

/-- W1507's W893 concrete leaves delegate to W892 after boundary-field assembly. -/
theorem w1507ConcreteLeavesRunThroughW892
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507) :
    concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
        input =
      concreteLeavesOfStrictPreimageMapFieldsComparisonW892
        (strictPreimageMapFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507
          input) :=
  rfl

/-- W1507 keeps the W1506 constructor-ledger input names. -/
def w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputNamesW1507 :
    List String :=
  w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictPreimageMapFieldsComparisonInputNamesW1506

theorem w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputNamesW1507_count :
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputNamesW1507.length =
      74 := by
  simpa [
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputNamesW1507]
    using
      w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3StrictPreimageMapFieldsComparisonInputNamesW1506_count

/-- Current W1507 nonterminal explicit WPP boundary-fields route state. -/
structure W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonStateW1507 :
    Type where
  seed : String
  declarations : List String
  boundaryFieldAssemblyResult : String
  comparisonResult : String
  remainingInputs : List String
  productSuccessClaimed : Bool

/-- W1507 records the W893 explicit boundary-field route reached from W1506. -/
def currentW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonStateW1507 :
    W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonStateW1507 where
  seed :=
    "w1507-w987-boundary-relation-target-strict-preimage-object-image-right-adjoint-target-compactness-mapped-cokernel-pi1-pi2-pi3-boundary-fields-comparison"
  declarations :=
    ["W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputW1507",
      "strictPreimageMapFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507",
      "boundaryFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1507",
      "strictPreimageMapFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507",
      "concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507",
      "routeDataProviderOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507",
      "directBoundedLeftCalculusOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507",
      "boundedDerivedInfinityCategoryOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonW1507",
      "w1507BoundaryDataMatchesW1506",
      "w1507StrictPreimageMapFieldLeavesBoundaryDataMatchesW1506",
      "w1507ConcreteLeavesRunThroughW892",
      "w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputNamesW1507_count"]
  boundaryFieldAssemblyResult :=
    "proved: W1506's bundled W716 boundary data supplies the W893 right-open\
      and source-pi-zero boundary fields"
  comparisonResult :=
    "proved: W1507's W893 boundary-field route delegates to W892 while its\
      rebuilt boundary data matches W1506's bundled W716 boundary data"
  remainingInputs :=
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonInputNamesW1507
  productSuccessClaimed := false

theorem currentW1507W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparison_productSuccess :
    currentW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3BoundaryFieldsComparisonStateW1507.productSuccessClaimed =
      false :=
  rfl

end

end Dbounded

end LeanLCAExactChallenge
