import LeanLCAExactChallenge.Derived.W987LocalizedRightAdjointFieldsComparisonGuardW1501
import LeanLCAExactChallenge.Derived.NormalizedFixedTargetFieldsComparisonStableExactAtRoute

/-!
W1502 feeds the W1501/W1498 surface through the W888 explicit normalized
fixed-target-fields comparison route. W1498 recovered W719 normalized
fixed-target data from W948; W1502 exposes its three fields and checks that
W888 rebuilds the same W887 localized-right-adjoint leaves reached by W1501.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace LeanLCAExactChallenge

open CategoryTheory
open CategoryTheory.Limits
open Topology
open DirectWppLimitFiniteShapeTransfer
open WppOpW426W318LegCompatibilityAlignmentV370SupportW439
open WppOpSelectedW461TransportedPointIsoProviderV370SupportW506
open WppOpClosedNatTransOrdinaryRelationTopologyV370SupportW511
open WppOpClosedNatTransOrdinaryRelationFieldsV370SupportW512
open WppOpW461BridgeComponentwiseClosedRangeProjectionV370SupportW481
open WppOpClosedRangeOnlyComponentwiseProjectionV370SupportW484
open WppOpClosedRangeMappedCokernelPreservationV370SupportW519

namespace Dbounded

noncomputable section

/-- W1502 reuses the W1501 74-field localized-right-adjoint comparison surface. -/
abbrev W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502 :
    Type 2 :=
  W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3LocalizedRightAdjointFieldsComparisonInputW1501

/-- W1502 assembles the W888 explicit normalized fixed-target leaves from W1498 data. -/
def normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    MetrizableWppNormalizedFixedTargetFieldLeavesW888 where
  boundaryData :=
    (boundaryRelationDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).boundaryData
  relationData :=
    (boundaryRelationDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).relationData
  targetSurjectiveCompactForTargetProvider :=
    targetSurjectiveCompactDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input
  diagramAndMappedCokernelClosednessData :=
    diagramAndMappedCokernelClosednessDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input
  normalizedLiftBlueprint :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).normalizedLiftBlueprint
  targetFixedTargetUniq :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).targetFixedTargetUniq
  localizationModelFixedTargetUniq :=
    (normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).localizationModelFixedTargetUniq
  sourcePretriangulated := input.sourcePretriangulated
  sourceTriangulated := input.sourceTriangulated
  triangleCompletion := input.triangleCompletion
  endpointForgetPreservesHomology :=
    endpointForgetPreservesHomologyOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3EndpointFieldsComparisonW1500
      input
  endpointClosedEmbedding :=
    (endpointTopologyFactsOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).endpointClosedEmbedding
  endpointOpenMap :=
    (endpointTopologyFactsOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).endpointOpenMap
  endpointEpiOfExactAt :=
    (endpointTopologyFactsOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).endpointEpiOfExactAt
  boundedHomotopyLocalizedRightAdjoint :=
    (localizedRightAdjointDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).boundedHomotopyLocalizedRightAdjoint
  boundedHomotopyLocalizedAdjunction :=
    (localizedRightAdjointDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).boundedHomotopyLocalizedAdjunction
  boundedHomotopyLocalizedUnitMem :=
    (localizedRightAdjointDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
      input).boundedHomotopyLocalizedUnitMem

/-- W1502 rebuilds W719 normalized fixed-target data through W888 fields. -/
def normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    MetrizableWppNormalizedFixedTargetDataProviderW719 :=
  normalizedFixedTargetDataOfFieldsW888
    (normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1502
      input)

/-- W1502 rebuilds W887 localized-right-adjoint leaves through W888 fields. -/
def localizedRightAdjointFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    MetrizableWppLocalizedRightAdjointFieldLeavesW887 :=
  localizedRightAdjointFieldLeavesOfNormalizedFixedTargetFieldsW888
    (normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1502
      input)

/-- W1502 rebuilds W886 endpoint-field leaves through W888 fields. -/
def endpointStrictTopologyFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    MetrizableWppEndpointStrictTopologyFieldLeavesW886 :=
  endpointStrictTopologyFieldLeavesOfLocalizedRightAdjointFieldsW887
    (localizedRightAdjointFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
      input)

/-- W1502 exposes the W885 leaves obtained by passing W1498 data through W888. -/
def sourceTriangulationFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    MetrizableWppSourceTriangulationFieldComparisonLeavesW885 :=
  sourceTriangulationFieldLeavesOfEndpointFieldsW886
    (endpointStrictTopologyFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
      input)

/-- W1502 exposes W888's concrete leaves. -/
def concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    MetrizableWppBoundaryRelationTargetClosednessNormalizedConcreteLeavesW733 :=
  concreteLeavesOfNormalizedFixedTargetFieldsComparisonW888
    (normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1502
      input)

/-- W1502 exposes W888's W732 route data. -/
def routeDataProviderOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    MetrizableWppBoundaryRelationTargetClosednessNormalizedDataProviderW732 :=
  routeDataProviderOfNormalizedFixedTargetFieldsComparisonW888
    (normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1502
      input)

/-- W1502 feeds W888 explicit normalized fixed-target fields to direct bounded left calculus. -/
theorem directBoundedLeftCalculusOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    (boundedExactWeakEquivalence MetrizableLCA.{0}).HasLeftCalculusOfFractions :=
  directBoundedLeftCalculusOfNormalizedFixedTargetFieldsComparisonStableExactAtW888
    (normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1502
      input)

/-- W1502 exposes W888's bounded derived infinity-category package. -/
def boundedDerivedInfinityCategoryOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    BoundedDerivedInfinityCategory MetrizableLCA.{0}
      (Dbounded.infinityCategory MetrizableLCA.{0}) :=
  boundedDerivedInfinityCategoryOfNormalizedFixedTargetFieldsComparisonStableExactAtW888
    (normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1502
      input)

/-- W1502's W888-normalized fixed-target data is definitionally W1498's W719 data. -/
theorem w1502NormalizedFixedTargetDataMatchesW1498
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
        input =
      normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3SourceTriangulationComparisonLeavesW1498
        input :=
  rfl

/-- W1502's W888-to-W887 leaves are definitionally W1501's W887 leaves. -/
theorem w1502LocalizedRightAdjointFieldLeavesMatchW1501
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    localizedRightAdjointFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
        input =
      localizedRightAdjointFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1501
        input :=
  rfl

/-- W1502's W888 concrete leaves are definitionally W1501's W887 concrete leaves. -/
theorem w1502ConcreteLeavesMatchW1501
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502) :
    concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502
        input =
      concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3LocalizedRightAdjointFieldsComparisonW1501
        input :=
  rfl

/-- W1502 keeps the W1501 constructor-ledger input names. -/
def w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputNamesW1502 :
    List String :=
  w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3LocalizedRightAdjointFieldsComparisonInputNamesW1501

theorem w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputNamesW1502_count :
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputNamesW1502.length =
      74 := by
  simpa [
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputNamesW1502]
    using
      w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3LocalizedRightAdjointFieldsComparisonInputNamesW1501_count

/-- Current W1502 nonterminal explicit normalized fixed-target-fields route state. -/
structure W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonStateW1502 :
    Type where
  seed : String
  declarations : List String
  normalizedFixedTargetFieldAssemblyResult : String
  comparisonResult : String
  remainingInputs : List String
  productSuccessClaimed : Bool

/-- W1502 records the W888 explicit normalized fixed-target-field route reached from W1501. -/
def currentW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonStateW1502 :
    W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonStateW1502 where
  seed :=
    "w1502-w987-boundary-relation-target-strict-preimage-object-image-right-adjoint-target-compactness-mapped-cokernel-pi1-pi2-pi3-normalized-fixed-target-fields-comparison"
  declarations :=
    ["W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputW1502",
      "normalizedFixedTargetFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1502",
      "normalizedFixedTargetDataOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502",
      "localizedRightAdjointFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502",
      "endpointStrictTopologyFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502",
      "sourceTriangulationFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502",
      "concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502",
      "routeDataProviderOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502",
      "directBoundedLeftCalculusOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502",
      "boundedDerivedInfinityCategoryOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonW1502",
      "w1502NormalizedFixedTargetDataMatchesW1498",
      "w1502LocalizedRightAdjointFieldLeavesMatchW1501",
      "w1502ConcreteLeavesMatchW1501",
      "w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputNamesW1502_count"]
  normalizedFixedTargetFieldAssemblyResult :=
    "proved: W1498's W948 normalized-source branch supplies the three explicit\
      W888 normalized fixed-target fields"
  comparisonResult :=
    "proved: W1502's W888 normalized fixed-target-field route rebuilds the\
      same W887 localized-right-adjoint leaves and concrete leaves reached by W1501"
  remainingInputs :=
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonInputNamesW1502
  productSuccessClaimed := false

theorem currentW1502W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparison_productSuccess :
    currentW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3NormalizedFixedTargetFieldsComparisonStateW1502.productSuccessClaimed =
      false :=
  rfl

end

end Dbounded

end LeanLCAExactChallenge
