import LeanLCAExactChallenge.Derived.W987ClosedEmbeddingClosednessFieldsComparisonGuardW1510
import LeanLCAExactChallenge.Derived.ClosedEmbeddingEndpointHomologyFreeComparisonStableExactAtRoute

/-!
W1511 feeds the W1510/W1498 surface through the W898 explicit
closed-embedding endpoint-homology-free comparison route. W1510 already splits
W1498's W973 closed-embedding branch into the W897 selected-difference
closed-embedding components and W519 mapped-cokernel closed-embedding provider;
W1511 lets W898 reconstruct endpoint forgetful homology preservation from that
same W519 provider through W856.
-/

set_option autoImplicit false
set_option linter.style.longLine false

namespace LeanLCAExactChallenge

open CategoryTheory
open CategoryTheory.Limits
open WppOpClosedRangeMappedCokernelPreservationV370SupportW519

namespace Dbounded

noncomputable section

/-- W1511 reuses the W1510 74-field closed-embedding closedness comparison surface. -/
abbrev W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511 :
    Type 2 :=
  W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingClosednessFieldsComparisonInputW1510

/-- W1511 names the W1510 W897 closed-embedding closedness-field leaves. -/
def closedEmbeddingClosednessFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    MetrizableWppClosedEmbeddingClosednessFieldLeavesW897 :=
  closedEmbeddingClosednessFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1510
    input

/-- W1511 removes W897's explicit endpoint homology field for the W898 route. -/
def closedEmbeddingEndpointHomologyFreeLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1511
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    MetrizableWppClosedEmbeddingEndpointHomologyFreeLeavesW898 :=
  let closednessLeaves :=
    closedEmbeddingClosednessFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
      input
  { rightOpenBoundary := closednessLeaves.rightOpenBoundary
    sourcePiZeroBoundary := closednessLeaves.sourcePiZeroBoundary
    relationPullbackProvider := closednessLeaves.relationPullbackProvider
    targetRelationLiftsProvider := closednessLeaves.targetRelationLiftsProvider
    targetDifferenceSurjectiveForTargetProvider :=
      closednessLeaves.targetDifferenceSurjectiveForTargetProvider
    targetCodomainCompactSpaceProvider :=
      closednessLeaves.targetCodomainCompactSpaceProvider
    globalClosedEmbeddingComponents :=
      closednessLeaves.globalClosedEmbeddingComponents
    mappedCokernelClosedEmbeddingProvider :=
      closednessLeaves.mappedCokernelClosedEmbeddingProvider
    strictPreimageZeroSrc := closednessLeaves.strictPreimageZeroSrc
    strictPreimageOneSrc := closednessLeaves.strictPreimageOneSrc
    strictPreimageZeroIso := closednessLeaves.strictPreimageZeroIso
    strictPreimageOneIso := closednessLeaves.strictPreimageOneIso
    strictPreimageLeftSrc := closednessLeaves.strictPreimageLeftSrc
    strictPreimageRightSrc := closednessLeaves.strictPreimageRightSrc
    strictPreimageLeftFac := closednessLeaves.strictPreimageLeftFac
    strictPreimageRightFac := closednessLeaves.strictPreimageRightFac
    strictPreimageZeroMap := closednessLeaves.strictPreimageZeroMap
    strictPreimageOneMap := closednessLeaves.strictPreimageOneMap
    strictPreimageZeroMapFac := closednessLeaves.strictPreimageZeroMapFac
    strictPreimageOneMapFac := closednessLeaves.strictPreimageOneMapFac
    strictPreimageLeftNaturality := closednessLeaves.strictPreimageLeftNaturality
    strictPreimageRightNaturality := closednessLeaves.strictPreimageRightNaturality
    strictRepresentativeMapId := closednessLeaves.strictRepresentativeMapId
    strictRepresentativeMapComp := closednessLeaves.strictRepresentativeMapComp
    sourceImageObjectNormalization :=
      closednessLeaves.sourceImageObjectNormalization
    sourceImageMapNormalization := closednessLeaves.sourceImageMapNormalization
    targetFixedTargetUniq := closednessLeaves.targetFixedTargetUniq
    localizationModelFixedTargetUniq :=
      closednessLeaves.localizationModelFixedTargetUniq
    sourcePretriangulated := closednessLeaves.sourcePretriangulated
    sourceTriangulated := closednessLeaves.sourceTriangulated
    triangleCompletion := closednessLeaves.triangleCompletion
    endpointClosedEmbedding := closednessLeaves.endpointClosedEmbedding
    endpointOpenMap := closednessLeaves.endpointOpenMap
    endpointEpiOfExactAt := closednessLeaves.endpointEpiOfExactAt
    boundedHomotopyLocalizedRightAdjoint :=
      closednessLeaves.boundedHomotopyLocalizedRightAdjoint
    boundedHomotopyLocalizedAdjunction :=
      closednessLeaves.boundedHomotopyLocalizedAdjunction
    boundedHomotopyLocalizedUnitMem :=
      closednessLeaves.boundedHomotopyLocalizedUnitMem }

/-- W1511 projects W898's homology-free leaves back to W897 closedness-field leaves. -/
def closedEmbeddingClosednessFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    MetrizableWppClosedEmbeddingClosednessFieldLeavesW897 :=
  closedEmbeddingClosednessFieldLeavesOfEndpointHomologyFreeW898
    (closedEmbeddingEndpointHomologyFreeLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1511
      input)

/-- W1511 exposes W898's W733 concrete leaves. -/
def concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    MetrizableWppBoundaryRelationTargetClosednessNormalizedConcreteLeavesW733 :=
  concreteLeavesOfClosedEmbeddingEndpointHomologyFreeComparisonW898
    (closedEmbeddingEndpointHomologyFreeLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1511
      input)

/-- W1511 exposes W898's W732 route data. -/
def routeDataProviderOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    MetrizableWppBoundaryRelationTargetClosednessNormalizedDataProviderW732 :=
  routeDataProviderOfClosedEmbeddingEndpointHomologyFreeComparisonW898
    (closedEmbeddingEndpointHomologyFreeLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1511
      input)

/-- W1511 feeds W898 endpoint-homology-free leaves to direct bounded left calculus. -/
theorem directBoundedLeftCalculusOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    (boundedExactWeakEquivalence MetrizableLCA.{0}).HasLeftCalculusOfFractions :=
  directBoundedLeftCalculusOfClosedEmbeddingEndpointHomologyFreeComparisonStableExactAtW898
    (closedEmbeddingEndpointHomologyFreeLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1511
      input)

/-- W1511 exposes W898's bounded derived infinity-category package. -/
def boundedDerivedInfinityCategoryOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    BoundedDerivedInfinityCategory MetrizableLCA.{0}
      (Dbounded.infinityCategory MetrizableLCA.{0}) :=
  boundedDerivedInfinityCategoryOfClosedEmbeddingEndpointHomologyFreeComparisonStableExactAtW898
    (closedEmbeddingEndpointHomologyFreeLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1511
      input)

/-- W1511's W898 projection reconstructs the same W897 leaves as W1510. -/
theorem w1511ClosedEmbeddingClosednessFieldLeavesMatchW1510
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    closedEmbeddingClosednessFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
        input =
      closedEmbeddingClosednessFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
        input :=
  rfl

/-- W1511 records that W898 derives endpoint homology from W1510's W519 provider. -/
theorem w1511EndpointForgetPreservesHomologyMatchesW1510
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    (closedEmbeddingClosednessFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
        input).endpointForgetPreservesHomology =
      (closedEmbeddingClosednessFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
        input).endpointForgetPreservesHomology := by
  rw [w1511ClosedEmbeddingClosednessFieldLeavesMatchW1510 input]

/-- W1511's concrete leaves delegate to W897 after W898 derives endpoint homology. -/
theorem w1511ConcreteLeavesRunThroughW897
    (input :
      W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511) :
    concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
        input =
      concreteLeavesOfClosedEmbeddingClosednessFieldsComparisonW897
        (closedEmbeddingClosednessFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511
          input) :=
  rfl

/-- W1511 keeps the W1510 constructor-ledger input names. -/
def w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputNamesW1511 :
    List String :=
  w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingClosednessFieldsComparisonInputNamesW1510

theorem w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputNamesW1511_count :
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputNamesW1511.length =
      74 := by
  simpa [
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputNamesW1511]
    using
      w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingClosednessFieldsComparisonInputNamesW1510_count

/-- Current W1511 nonterminal endpoint-homology-free closed-embedding route state. -/
structure W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonStateW1511 :
    Type where
  seed : String
  declarations : List String
  endpointHomologyResult : String
  comparisonResult : String
  remainingInputs : List String
  productSuccessClaimed : Bool

/-- W1511 records the W898 endpoint-homology-free route reached from W1510. -/
def currentW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonStateW1511 :
    W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonStateW1511 where
  seed :=
    "w1511-w987-boundary-relation-target-strict-preimage-object-image-right-adjoint-target-compactness-mapped-cokernel-pi1-pi2-pi3-closed-embedding-endpoint-homology-free-comparison"
  declarations :=
    ["W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputW1511",
      "closedEmbeddingClosednessFieldLeavesForW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511",
      "closedEmbeddingEndpointHomologyFreeLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3W1511",
      "closedEmbeddingClosednessFieldLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511",
      "concreteLeavesOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511",
      "routeDataProviderOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511",
      "directBoundedLeftCalculusOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511",
      "boundedDerivedInfinityCategoryOfW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonW1511",
      "w1511ClosedEmbeddingClosednessFieldLeavesMatchW1510",
      "w1511EndpointForgetPreservesHomologyMatchesW1510",
      "w1511ConcreteLeavesRunThroughW897",
      "w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputNamesW1511_count"]
  endpointHomologyResult :=
    "proved: W898 reconstructs endpoint forgetful homology preservation from\
      W1510's W519 mapped-cokernel closed-embedding provider through W856"
  comparisonResult :=
    "proved: W1511's W898 endpoint-homology-free route projects back to the\
      same W897 closed-embedding closedness-field leaves used by W1510"
  remainingInputs :=
    w987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonInputNamesW1511
  productSuccessClaimed := false

theorem currentW1511W987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparison_productSuccess :
    currentW987BoundaryRelationTargetStrictPreimageObjectImageRightAdjointFunctorTargetSurjectivityCompactnessMappedCokernelPi1Pi2Pi3ClosedEmbeddingEndpointHomologyFreeComparisonStateW1511.productSuccessClaimed =
      false :=
  rfl

end

end Dbounded

end LeanLCAExactChallenge
